"""hereditary peripheral neuropathy (HEREDITARY_PERIPHERAL_NEUROPATHY) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "hereditary peripheral neuropathy (HEREDITARY_PERIPHERAL_NEUROPATHY)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of hereditary peripheral neuropathy
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(hereditary peripheral neuropathy[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(hereditary peripheral neuropathy[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(hereditary peripheral neuropathy[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(hereditary peripheral neuropathy[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "hereditary peripheral neuropathy OR hereditary"
GWAS_SEARCH_TERMS = ["hereditary peripheral neuropathy", "hereditary"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ADAR": 4.0,
        "CLDN19": 4.0,
        "DCUN1D2": 4.0,
        "EGR2": 4.0,
        "FIG4": 4.0,
        "GJB1": 4.0,
        "HADHB": 4.0,
        "HMBS": 4.0,
        "HSPB1": 4.0,
        "IGHMBP2": 4.0,
        "KIF1A": 4.0,
        "KIF5A": 4.0,
        "LAMA2": 4.0,
        "LMNA": 4.0,
        "LPIN1": 4.0,
        "MFN2": 4.0,
        "MPZ": 4.0,
        "NEFH": 4.0,
        "NHERF1": 4.0,
        "OPA1": 4.0,
        "PCBP1": 4.0,
        "PDXP": 4.0,
        "PLP1": 4.0,
        "PMP22": 4.0,
        "PNKP": 4.0,
        "PRDX5": 4.0,
        "PRPS1": 4.0,
        "PTHLH": 4.0,
        "RPLP0": 4.0,
        "SH3TC2": 4.0,
        "SPTLC1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "acetaminophen",
        "dexamethasone",
        "midazolam",
        "midazolam hydrochloride",
        "roflumilast",
        "rolipram",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "hereditary_peripheral_neuropathy-screening-v1",
    "pathway_keywords": [
        "dopamine",
        "interferon",
        "pathway",
        "serotonin",
        "signaling",
        "type",
    ],
    "mechanism_keywords": [
        "dopamine",
        "interferon",
        "pathway",
        "serotonin",
        "signaling",
        "type",
    ],
    "reference_drug_ids": [
        "CHEMBL112",
        "CHEMBL2108791",
        "CHEMBL63",
        "CHEMBL63",
        "CHEMBL1200420",
        "CHEMBL1200420",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_hereditary_peripheral_neuropathy_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
