"""vertebral disorder (VERTEBRAL_DISORDER) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "vertebral disorder (VERTEBRAL_DISORDER)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of vertebral disorder
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(vertebral disorder[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(vertebral disorder[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(vertebral disorder[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(vertebral disorder[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "vertebral disorder OR vertebral"
GWAS_SEARCH_TERMS = ["vertebral disorder", "vertebral"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AGMO": 4.0,
        "BPTF": 4.0,
        "C3orf33": 4.0,
        "CDC5L": 4.0,
        "CHRDL1": 4.0,
        "CHST3": 4.0,
        "CRIPTO3": 4.0,
        "CYP26B1": 4.0,
        "DCC": 4.0,
        "DCDC1": 4.0,
        "DIO3": 4.0,
        "DMP1": 4.0,
        "DYNC1I1": 4.0,
        "DYSF": 4.0,
        "EXOC6B": 4.0,
        "FAM161A": 4.0,
        "FANCL": 4.0,
        "FGFR3": 4.0,
        "GFPT1": 4.0,
        "GSDMC": 4.0,
        "IL6": 4.0,
        "INO80D": 4.0,
        "KLF3": 4.0,
        "LRP1": 4.0,
        "MAEA": 4.0,
        "MAFB": 4.0,
        "MPPED2": 4.0,
        "MST1": 4.0,
        "MTMR11": 4.0,
        "MTMR3": 4.0,
        "NAV1": 4.0,
        "NFU1": 4.0,
        "NGF": 4.0,
        "PAIP2B": 4.0,
        "PDE3A": 4.0,
        "PIK3R1": 4.0,
        "PIP4K2C": 4.0,
        "PPARD": 4.0,
        "PPFIA1": 4.0,
        "PTPRC": 4.0,
        "PWWP4": 4.0,
        "RAB28": 4.0,
        "RSRC2": 4.0,
        "RTL1": 4.0,
        "SLC25A13": 4.0,
        "SLC25A21": 4.0,
        "SLC25A47": 4.0,
        "SMAD3": 4.0,
        "SOCS3": 4.0,
        "SOX5": 4.0,
        "SOX6": 4.0,
        "TBC1D1": 4.0,
        "TGFA": 4.0,
        "TNRC18": 4.0,
        "TRAPPC8": 4.0,
        "UVSSA": 4.0,
        "WARS1": 4.0,
        "ZCCHC8": 4.0,
        "ZIC1": 4.0,
        "ZNF638": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "bupivacaine",
        "clonidine",
        "epinephrine",
        "ketorolac",
        "ropivacaine",
        "ropivacaine hydrochloride",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "vertebral_disorder-screening-v1",
    "pathway_keywords": [
        "hormone",
        "mapk",
        "metabolism",
        "mtor",
        "pi3k",
        "signaling",
        "stat",
        "thyroid",
        "xenobiotic",
    ],
    "mechanism_keywords": [
        "hormone",
        "mapk",
        "metabolism",
        "mtor",
        "pi3k",
        "signaling",
        "stat",
        "thyroid",
        "xenobiotic",
    ],
    "reference_drug_ids": [
        "CHEMBL1077896",
        "CHEMBL134",
        "CHEMBL1077896",
        "CHEMBL679",
        "CHEMBL679",
        "CHEMBL1077896",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_vertebral_disorder_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
