"""tongue neoplasm (TONGUE_NEOPLASM) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'tongue neoplasm (TONGUE_NEOPLASM)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of tongue neoplasm
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(tongue neoplasm[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(tongue neoplasm[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(tongue neoplasm[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(tongue neoplasm[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'tongue neoplasm OR tongue'
GWAS_SEARCH_TERMS = ['tongue neoplasm', 'tongue']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AGRN": 4.0,
        "AKT1": 4.0,
        "BDNF": 4.0,
        "BIRC5": 4.0,
        "BMI1": 4.0,
        "CALML6": 4.0,
        "CCL26": 4.0,
        "CCL3": 4.0,
        "CD274": 4.0,
        "CD4": 4.0,
        "CD40LG": 4.0,
        "CD8A": 4.0,
        "CDH1": 4.0,
        "CDKN2A": 4.0,
        "CKAP4": 4.0,
        "CTLA4": 4.0,
        "CXCL14": 4.0,
        "DEK": 4.0,
        "EGF": 4.0,
        "EGFR": 4.0,
        "EGR1": 4.0,
        "FOS": 4.0,
        "GLS": 4.0,
        "GRHL2": 4.0,
        "GSDMB": 4.0,
        "HGF": 4.0,
        "IGFBP3": 4.0,
        "IL13": 4.0,
        "JUN": 4.0,
        "KDM1A": 4.0,
        "LOX": 4.0,
        "LOXL2": 4.0,
        "MMP10": 4.0,
        "MMP13": 4.0,
        "MT-CO2": 4.0,
        "NFKB1": 4.0,
        "NLRP3": 4.0,
        "PARP1": 4.0,
        "PCNA": 4.0,
        "PDCD1": 4.0,
        "PLAUR": 4.0,
        "PRL": 4.0,
        "PTGER4": 4.0,
        "PTGS2": 4.0,
        "RARB": 4.0,
        "RASSF1": 4.0,
        "RPE65": 4.0,
        "RPL17": 4.0,
        "RPL17-C18orf32": 4.0,
        "S100A16": 4.0,
        "S100A7": 4.0,
        "SNCA": 4.0,
        "SPATA2": 4.0,
        "STING1": 4.0,
        "TP53": 4.0,
        "TP63": 4.0,
        "TRPM2": 4.0,
        "UVRAG": 4.0,
        "VEGFC": 4.0,
        "VIM": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
        "gemcitabine hydrochloride",
        "peginterferon alfa-2a",
    ],
    "moderate_risk": [
        "alectinib",
        "amuvatinib",
        "axitinib",
        "bevacizumab",
        "birinapant",
        "blinatumomab",
        "ceritinib",
        "clofarabine",
        "crenolanib",
        "dacomitinib anhydrous",
        "dasatinib",
        "dextromethorphan hydrobromide",
        "eribulin",
        "eribulin mesylate",
        "esomeprazole",
        "famitinib",
        "farletuzumab",
        "fludarabine phosphate",
        "foretinib",
        "golvatinib",
        "ixabepilone",
        "leronlimab",
        "lirilumab",
        "mocetinostat",
        "molibresib",
        "niraparib",
        "nirogacestat",
        "onalespib",
        "pazopanib hydrochloride",
        "pevonedistat",
        "rabeprazole",
        "raltitrexed",
        "regorafenib",
        "rucaparib",
        "ruxolitinib",
        "sorafenib",
        "sunitinib malate",
        "topotecan hydrochloride",
        "tosedostat",
        "vandetanib",
        "vinflunine",
    ],
    "low_risk": [
        "metformin",
        "metformin hydrochloride",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "tongue_neoplasm-screening-v1",
    "pathway_keywords": [
        "(th2)",
        "apoptosis",
        "cell",
        "checkpoint",
        "chemokine",
        "cycle",
        "immune",
        "inflammasome",
        "mapk",
        "pathway",
    ],
    "mechanism_keywords": [
        "(th2)",
        "apoptosis",
        "cell",
        "checkpoint",
        "chemokine",
        "cycle",
        "immune",
        "inflammasome",
        "mapk",
        "pathway",
    ],
    "reference_drug_ids": [
        "CHEMBL1094636",
        "CHEMBL1096882",
        "CHEMBL1096882",
        "CHEMBL1173055",
        "CHEMBL1201320",
        "CHEMBL1201560",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_tongue_neoplasm_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
