"""ovarian epithelial tumor (OVARIAN_EPITHELIAL_TUMOR) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'ovarian epithelial tumor (OVARIAN_EPITHELIAL_TUMOR)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of ovarian epithelial tumor
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(ovarian epithelial tumor[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(ovarian epithelial tumor[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(ovarian epithelial tumor[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(ovarian epithelial tumor[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'ovarian epithelial tumor OR ovarian'
GWAS_SEARCH_TERMS = ['ovarian epithelial tumor', 'ovarian']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACKR3": 4.0,
        "ARHGAP35": 4.0,
        "ARID1A": 4.0,
        "ARID2": 4.0,
        "ATRX": 4.0,
        "BRAF": 4.0,
        "BRCA1": 4.0,
        "BRCA2": 4.0,
        "C19orf33": 4.0,
        "CARD11": 4.0,
        "CDK12": 4.0,
        "CREBBP": 4.0,
        "CSMD3": 4.0,
        "CTNNB1": 4.0,
        "CTNND2": 4.0,
        "ELL": 4.0,
        "ERBB2": 4.0,
        "FAT1": 4.0,
        "FGFR1": 4.0,
        "FOXL2": 4.0,
        "GPC5": 4.0,
        "JAK1": 4.0,
        "KDM5C": 4.0,
        "KMT2A": 4.0,
        "KMT2C": 4.0,
        "KMT2D": 4.0,
        "KRAS": 4.0,
        "LATS1": 4.0,
        "LRP1B": 4.0,
        "MYH9": 4.0,
        "NBEA": 4.0,
        "NF1": 4.0,
        "NF2": 4.0,
        "NOTCH1": 4.0,
        "NRAS": 4.0,
        "NUTM1": 4.0,
        "PALB2": 4.0,
        "PDCD1": 4.0,
        "PIK3CA": 4.0,
        "PIK3R1": 4.0,
        "PPP2R1A": 4.0,
        "PREX2": 4.0,
        "PTEN": 4.0,
        "PTPRB": 4.0,
        "PTPRD": 4.0,
        "PTPRT": 4.0,
        "RB1": 4.0,
        "RNF43": 4.0,
        "ROS1": 4.0,
        "RPL17": 4.0,
        "RPL17-C18orf32": 4.0,
        "SETD1B": 4.0,
        "SMARCA4": 4.0,
        "SNCA": 4.0,
        "SPATA2": 4.0,
        "STAT5B": 4.0,
        "TNC": 4.0,
        "TP53": 4.0,
        "WWTR1": 4.0,
        "ZNF521": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
        "gemcitabine hydrochloride",
        "peginterferon alfa-2a",
    ],
    "moderate_risk": [
        "alectinib",
        "amuvatinib",
        "axitinib",
        "bevacizumab",
        "birinapant",
        "blinatumomab",
        "ceritinib",
        "clofarabine",
        "crenolanib",
        "dacomitinib anhydrous",
        "dasatinib",
        "dextromethorphan hydrobromide",
        "eribulin",
        "eribulin mesylate",
        "esomeprazole",
        "famitinib",
        "farletuzumab",
        "fludarabine phosphate",
        "foretinib",
        "golvatinib",
        "ixabepilone",
        "leronlimab",
        "lirilumab",
        "mocetinostat",
        "molibresib",
        "niraparib",
        "nirogacestat",
        "onalespib",
        "pazopanib hydrochloride",
        "pevonedistat",
        "rabeprazole",
        "raltitrexed",
        "regorafenib",
        "rucaparib",
        "ruxolitinib",
        "sorafenib",
        "sunitinib malate",
        "topotecan hydrochloride",
        "tosedostat",
        "vandetanib",
        "vinflunine",
    ],
    "low_risk": [
        "metformin",
        "metformin hydrochloride",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "ovarian_epithelial_tumor-screening-v1",
    "pathway_keywords": [
        "cascade",
        "cell",
        "checkpoint",
        "chemokine",
        "coagulation",
        "cycle",
        "immune",
        "mapk",
        "mtor",
        "notch",
    ],
    "mechanism_keywords": [
        "cascade",
        "cell",
        "checkpoint",
        "chemokine",
        "coagulation",
        "cycle",
        "immune",
        "mapk",
        "mtor",
        "notch",
    ],
    "reference_drug_ids": [
        "CHEMBL1094636",
        "CHEMBL1096882",
        "CHEMBL1096882",
        "CHEMBL1173055",
        "CHEMBL1201320",
        "CHEMBL1201560",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_ovarian_epithelial_tumor_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
