"""spinocerebellar ataxia type 20 (SPINOCEREBELLAR_ATAXIA_TYPE_20) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'spinocerebellar ataxia type 20 (SPINOCEREBELLAR_ATAXIA_TYPE_20)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Hypermetric saccades",
    "Action tremor",
    "Abnormally high-pitched voice",
    "Limb ataxia",
    "Palatal tremor",
    "Dysphonia",
    "Abnormal pyramidal sign",
    "Autosomal dominant inheritance",
    "Dysarthria",
    "Adult onset",
    "Slowly progressive",
    "Nystagmus",
    "Postural tremor",
    "Gait ataxia",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(spinocerebellar ataxia type 20[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(spinocerebellar ataxia type 20[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(spinocerebellar ataxia type 20[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(spinocerebellar ataxia type 20[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'spinocerebellar ataxia type 20 OR spinocerebellar'
GWAS_SEARCH_TERMS = ['spinocerebellar ataxia type 20', 'spinocerebellar']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACHE": 4.0,
        "ADAM23": 4.0,
        "AGTPBP1": 4.0,
        "ANK3": 4.0,
        "AP3B2": 4.0,
        "ATCAY": 4.0,
        "ATP2B2": 4.0,
        "CACNA1A": 4.0,
        "CACNA1G": 4.0,
        "CACNA2D2": 4.0,
        "CLP1": 4.0,
        "CNTNAP1": 4.0,
        "DAB1": 4.0,
        "DAGLA": 4.0,
        "DST": 4.0,
        "DYNC1H1": 4.0,
        "EFNB3": 4.0,
        "GABRA1": 4.0,
        "GALC": 4.0,
        "GLB1": 4.0,
        "GLRA1": 4.0,
        "GLRB": 4.0,
        "GRID2": 4.0,
        "GRM1": 4.0,
        "HCN2": 4.0,
        "HEXB": 4.0,
        "KCNA1": 4.0,
        "KCNMA1": 4.0,
        "KCNN2": 4.0,
        "KCNQ1": 4.0,
        "KCNV1": 4.0,
        "LRR1": 4.0,
        "MBP": 4.0,
        "MECP2": 4.0,
        "MPZ": 4.0,
        "MYO5A": 4.0,
        "NEFL": 4.0,
        "PLP1": 4.0,
        "PMP22": 4.0,
        "PRNP": 4.0,
        "PSAP": 4.0,
        "QKI": 4.0,
        "RELN": 4.0,
        "RHBDL3": 4.0,
        "RORA": 4.0,
        "RREB1": 4.0,
        "SCN4B": 4.0,
        "SCN8A": 4.0,
        "SMDT1": 4.0,
        "SPTBN2": 4.0,
        "SPTBN4": 4.0,
        "STARD9": 4.0,
        "SULT4A1": 4.0,
        "SYT14": 4.0,
        "SYT2": 4.0,
        "TOR1A": 4.0,
        "TPP1": 4.0,
        "UNC5C": 4.0,
        "ZNF24": 4.0,
        "ZNF423": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "donepezil",
        "encenicline",
        "memantine",
        "rivastigmine",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "spinocerebellar_ataxia_type_20-screening-v1",
    "pathway_keywords": [
        "angiotensin",
        "cardiac",
        "cascade",
        "channel",
        "coagulation",
        "conduction",
        "gaba",
        "glutamate",
        "metabolism",
        "pathway",
    ],
    "mechanism_keywords": [
        "angiotensin",
        "cardiac",
        "cascade",
        "channel",
        "coagulation",
        "conduction",
        "gaba",
        "glutamate",
        "metabolism",
        "pathway",
    ],
    "reference_drug_ids": [
        "CHEMBL807",
        "CHEMBL2151572",
        "CHEMBL636",
        "CHEMBL636",
        "CHEMBL807",
        "CHEMBL502",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_spinocerebellar_ataxia_type_20_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
