"""osteonecrosis (OSTEONECROSIS) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "osteonecrosis (OSTEONECROSIS)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of osteonecrosis
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(osteonecrosis[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(osteonecrosis[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(osteonecrosis[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(osteonecrosis[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "osteonecrosis OR osteonecrosis"
GWAS_SEARCH_TERMS = ["osteonecrosis", "osteonecrosis"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ADORA2A": 4.0,
        "ADORA2B": 4.0,
        "APOA1": 4.0,
        "ASPG": 4.0,
        "BMP2": 4.0,
        "ENO4": 4.0,
        "F2": 4.0,
        "FAM167A": 4.0,
        "FDPS": 4.0,
        "FGF2": 4.0,
        "GPX4": 4.0,
        "HEBP1": 4.0,
        "HIF1A": 4.0,
        "IL2": 4.0,
        "IL6": 4.0,
        "ISYNA1": 4.0,
        "KITLG": 4.0,
        "METTL3": 4.0,
        "MMP9": 4.0,
        "NOS2": 4.0,
        "NOS3": 4.0,
        "PDE10A": 4.0,
        "PDE1A": 4.0,
        "PDE1B": 4.0,
        "PDE1C": 4.0,
        "PDE2A": 4.0,
        "PDE3A": 4.0,
        "PDE3B": 4.0,
        "PDE4A": 4.0,
        "PDE4B": 4.0,
        "PDE4C": 4.0,
        "PDE4D": 4.0,
        "PDE5A": 4.0,
        "PDE6A": 4.0,
        "PDE6B": 4.0,
        "PDE6C": 4.0,
        "PDE6D": 4.0,
        "PDE6G": 4.0,
        "PDE6H": 4.0,
        "PDE7A": 4.0,
        "PDE7B": 4.0,
        "PDE8A": 4.0,
        "PDE8B": 4.0,
        "PDE9A": 4.0,
        "PPARG": 4.0,
        "PTGS1": 4.0,
        "PTGS2": 4.0,
        "SELL": 4.0,
        "SERPINE1": 4.0,
        "SLC35G5": 4.0,
        "SOST": 4.0,
        "TNF": 4.0,
        "TNFRSF11B": 4.0,
        "TNFSF11": 4.0,
        "TRPV4": 4.0,
        "TYMS": 4.0,
        "VDR": 4.0,
        "VEGFA": 4.0,
        "VEGFC": 4.0,
        "WIPF1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "aspirin",
        "ibandronic acid",
        "pentoxifylline",
        "propofol",
        "zoledronic acid",
        "zoledronic acid anhydrous",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "osteonecrosis-screening-v1",
    "pathway_keywords": [
        "adhesion",
        "autophagy",
        "bone",
        "cascade",
        "cell",
        "coagulation",
        "hepcidin",
        "homeostasis",
        "hormone",
        "integrin",
    ],
    "mechanism_keywords": [
        "adhesion",
        "autophagy",
        "bone",
        "cascade",
        "cell",
        "coagulation",
        "hepcidin",
        "homeostasis",
        "hormone",
        "integrin",
    ],
    "reference_drug_ids": [
        "CHEMBL526",
        "CHEMBL4303669",
        "CHEMBL924",
        "CHEMBL628",
        "CHEMBL526",
        "CHEMBL526",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_osteonecrosis_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
