"""Postpartum depression (POSTPARTUM_DEPRESSION) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "Postpartum depression (POSTPARTUM_DEPRESSION)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of Postpartum depression
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(Postpartum depression[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(Postpartum depression[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(Postpartum depression[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(Postpartum depression[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "Postpartum depression OR Postpartum"
GWAS_SEARCH_TERMS = ["Postpartum depression", "Postpartum"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ADIPOQ": 4.0,
        "ARG2": 4.0,
        "BDNF": 4.0,
        "BRD2": 4.0,
        "COMT": 4.0,
        "CRH": 4.0,
        "CRP": 4.0,
        "CSF1R": 4.0,
        "DISC1": 4.0,
        "DRD2": 4.0,
        "ESR1": 4.0,
        "GABRA1": 4.0,
        "GABRA2": 4.0,
        "GABRA3": 4.0,
        "GABRA4": 4.0,
        "GABRA5": 4.0,
        "GABRA6": 4.0,
        "GABRB1": 4.0,
        "GABRB2": 4.0,
        "GABRB3": 4.0,
        "GABRD": 4.0,
        "GABRE": 4.0,
        "GABRG1": 4.0,
        "GABRG2": 4.0,
        "GABRG3": 4.0,
        "GABRP": 4.0,
        "GABRQ": 4.0,
        "GNRHR": 4.0,
        "GRIN1": 4.0,
        "GRIN2A": 4.0,
        "GRIN2B": 4.0,
        "GRIN2C": 4.0,
        "GRIN2D": 4.0,
        "GRIN3A": 4.0,
        "GRIN3B": 4.0,
        "GSTM1": 4.0,
        "HCRT": 4.0,
        "HP1BP3": 4.0,
        "HSD11B1": 4.0,
        "HTR1A": 4.0,
        "HTR2A": 4.0,
        "HTR2C": 4.0,
        "IGF1": 4.0,
        "IL10": 4.0,
        "IL1B": 4.0,
        "IL6": 4.0,
        "LEP": 4.0,
        "NLRP3": 4.0,
        "NR3C1": 4.0,
        "OPRM1": 4.0,
        "OXT": 4.0,
        "OXTR": 4.0,
        "PGR": 4.0,
        "PHLDA1": 4.0,
        "POMC": 4.0,
        "PPARA": 4.0,
        "PRL": 4.0,
        "PTGS2": 4.0,
        "PTPRN": 4.0,
        "RAD51B": 4.0,
        "RDH11": 4.0,
        "SCGB1A1": 4.0,
        "SCN10A": 4.0,
        "SCN11A": 4.0,
        "SCN1A": 4.0,
        "SCN2A": 4.0,
        "SCN3A": 4.0,
        "SCN4A": 4.0,
        "SCN5A": 4.0,
        "SCN7A": 4.0,
        "SCN8A": 4.0,
        "SCN9A": 4.0,
        "SLC6A2": 4.0,
        "SLC6A4": 4.0,
        "TG": 4.0,
        "TNF": 4.0,
        "TPO": 4.0,
        "TRPC5": 4.0,
        "TSPO": 4.0,
        "VTI1B": 4.0,
        "ZFYVE26": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "albendazole",
        "aripiprazole",
        "azithromycin",
        "brexanolone",
        "bupivacaine",
        "celecoxib",
        "choline",
        "citalopram",
        "desvenlafaxine",
        "dinalbuphine sebacate",
        "doconexent",
        "escitalopram",
        "estradiol",
        "fentanyl",
        "ganaxolone",
        "icosapent",
        "ketamine",
        "mebufotenin",
        "meperidine",
        "midazolam",
        "morphine",
        "nitrous oxide",
        "olsalazine sodium",
        "pyrimethamine",
        "quetiapine",
        "remifentanil",
        "ropivacaine",
        "sertraline",
        "sulfadoxine",
        "trazodone",
        "zuranolone",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "postpartum_depression-screening-v1",
    "pathway_keywords": [
        "cardiac",
        "cell",
        "channel",
        "conduction",
        "cycle",
        "dopamine",
        "gaba",
        "glutamate",
        "hormone",
        "inflammasome",
    ],
    "mechanism_keywords": [
        "cardiac",
        "cell",
        "channel",
        "conduction",
        "cycle",
        "dopamine",
        "gaba",
        "glutamate",
        "hormone",
        "inflammasome",
    ],
    "reference_drug_ids": [
        "CHEMBL207538",
        "CHEMBL207538",
        "CHEMBL207538",
        "CHEMBL4105630",
        "CHEMBL4105630",
        "CHEMBL742",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_postpartum_depression_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
