"""monocytic leukemia (MONOCYTIC_LEUKEMIA) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "monocytic leukemia (MONOCYTIC_LEUKEMIA)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of monocytic leukemia
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(monocytic leukemia[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(monocytic leukemia[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(monocytic leukemia[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(monocytic leukemia[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "monocytic leukemia OR monocytic"
GWAS_SEARCH_TERMS = ["monocytic leukemia", "monocytic"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AKT3": 4.0,
        "ASXL1": 4.0,
        "BCL2L1": 4.0,
        "BCL3": 4.0,
        "CALM1": 4.0,
        "CALM2": 4.0,
        "CALM3": 4.0,
        "CAPG": 4.0,
        "CASP3": 4.0,
        "CD14": 4.0,
        "CSF1R": 4.0,
        "CSF2": 4.0,
        "CXCL12": 4.0,
        "CXCL14": 4.0,
        "DNMT3A": 4.0,
        "EGF": 4.0,
        "ERVW-1": 4.0,
        "FCGR1A": 4.0,
        "GLRX": 4.0,
        "ICAM1": 4.0,
        "IFNG": 4.0,
        "IL1A": 4.0,
        "IL1B": 4.0,
        "IL4": 4.0,
        "JAK1": 4.0,
        "JAK2": 4.0,
        "KDM1A": 4.0,
        "KMT2A": 4.0,
        "LDLR": 4.0,
        "LTF": 4.0,
        "LYZ": 4.0,
        "MAPK8": 4.0,
        "MAPKAPK2": 4.0,
        "MPO": 4.0,
        "MUC1": 4.0,
        "MYB": 4.0,
        "MYC": 4.0,
        "NFKB1": 4.0,
        "PICALM": 4.0,
        "PPARG": 4.0,
        "PRDM2": 4.0,
        "PTGS2": 4.0,
        "PTPN11": 4.0,
        "RAF1": 4.0,
        "RUNX1": 4.0,
        "SEMA7A": 4.0,
        "SERPINB2": 4.0,
        "SGMS1": 4.0,
        "SNAP91": 4.0,
        "SRSF2": 4.0,
        "TDO2": 4.0,
        "TET2": 4.0,
        "TGFB1": 4.0,
        "TLR4": 4.0,
        "TNF": 4.0,
        "TNFSF13B": 4.0,
        "TNFSF14": 4.0,
        "TP53": 4.0,
        "VLDLR": 4.0,
        "VSIR": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "ruxolitinib",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "monocytic_leukemia-screening-v1",
    "pathway_keywords": [
        "(th2)",
        "adhesion",
        "apoptosis",
        "cascade",
        "cell",
        "checkpoint",
        "chemokine",
        "coagulation",
        "immune",
        "inflammasome",
    ],
    "mechanism_keywords": [
        "(th2)",
        "adhesion",
        "apoptosis",
        "cascade",
        "cell",
        "checkpoint",
        "chemokine",
        "coagulation",
        "immune",
        "inflammasome",
    ],
    "reference_drug_ids": [
        "CHEMBL1789941",
        "CHEMBL1789941",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_monocytic_leukemia_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
