"""respiratory tract infectious disorder (RESPIRATORY_TRACT_INFECTIOUS_DISORDER) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "respiratory tract infectious disorder (RESPIRATORY_TRACT_INFECTIOUS_DISORDER)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of respiratory tract infectious disorder
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(respiratory tract infectious disorder[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(respiratory tract infectious disorder[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(respiratory tract infectious disorder[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(respiratory tract infectious disorder[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "respiratory tract infectious disorder OR respiratory"
GWAS_SEARCH_TERMS = ["respiratory tract infectious disorder", "respiratory"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AAGAB": 4.0,
        "ACOXL": 4.0,
        "ACVR1": 4.0,
        "ADGRL1": 4.0,
        "ADRA1A": 4.0,
        "ADRA1B": 4.0,
        "ADRA1D": 4.0,
        "APOE": 4.0,
        "BACH2": 4.0,
        "BCL2L11": 4.0,
        "BRDT": 4.0,
        "CDHR3": 4.0,
        "CFTR": 4.0,
        "CLEC16A": 4.0,
        "CXCL9": 4.0,
        "D2HGDH": 4.0,
        "DKK2": 4.0,
        "EMSY": 4.0,
        "ENOX1": 4.0,
        "ENSG00000293584": 4.0,
        "FAAH": 4.0,
        "GALNT1": 4.0,
        "GALNT5": 4.0,
        "GLMN": 4.0,
        "GSDMB": 4.0,
        "HRH1": 4.0,
        "IL13": 4.0,
        "IL18R1": 4.0,
        "IL18RAP": 4.0,
        "IL1R1": 4.0,
        "IL1RL1": 4.0,
        "IL1RL2": 4.0,
        "IL21R": 4.0,
        "IL33": 4.0,
        "IL4R": 4.0,
        "IRF1": 4.0,
        "ITSN2": 4.0,
        "KIF1B": 4.0,
        "KLHL29": 4.0,
        "LIMS4": 4.0,
        "MDN1": 4.0,
        "MTOR": 4.0,
        "NEK6": 4.0,
        "NPEPL1": 4.0,
        "ORMDL3": 4.0,
        "PGD": 4.0,
        "PTGS1": 4.0,
        "PTGS2": 4.0,
        "RANBP6": 4.0,
        "RGS12": 4.0,
        "SH2B3": 4.0,
        "SLC6A2": 4.0,
        "SLC7A10": 4.0,
        "SMAD3": 4.0,
        "TGFBR3": 4.0,
        "TRPV1": 4.0,
        "TSLP": 4.0,
        "WDR36": 4.0,
        "ZNF652": 4.0,
        "ZPBP2": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "acetaminophen",
        "danirixin",
        "pheniramine",
        "pheniramine maleate",
        "phenylephrine",
        "phenylephrine hydrochloride",
        "pseudoephedrine",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "respiratory_tract_infectious_disorder-screening-v1",
    "pathway_keywords": [
        "(th2)",
        "apoptosis",
        "chemokine",
        "hormone",
        "inflammasome",
        "interferon",
        "lipid",
        "metabolism",
        "mtor",
        "pathway",
    ],
    "mechanism_keywords": [
        "(th2)",
        "apoptosis",
        "chemokine",
        "hormone",
        "inflammasome",
        "interferon",
        "lipid",
        "metabolism",
        "mtor",
        "pathway",
    ],
    "reference_drug_ids": [
        "CHEMBL1215",
        "CHEMBL1200339",
        "CHEMBL1215",
        "CHEMBL1215",
        "CHEMBL1590",
        "CHEMBL112",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_respiratory_tract_infectious_disorder_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
