"""orofaciodigital syndrome X (OROFACIODIGITAL_SYNDROME_X) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "orofaciodigital syndrome X (OROFACIODIGITAL_SYNDROME_X)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Coalescence of tarsal bones",
    "Depressed nasal bridge",
    "Retrognathia",
    "Finger aplasia",
    "Telecanthus",
    "Cleft palate",
    "Preaxial hand polydactyly",
    "Fibular aplasia",
    "Autosomal dominant inheritance",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(orofaciodigital syndrome X[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(orofaciodigital syndrome X[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(orofaciodigital syndrome X[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(orofaciodigital syndrome X[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "orofaciodigital syndrome X OR orofaciodigital"
GWAS_SEARCH_TERMS = ["orofaciodigital syndrome X", "orofaciodigital"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ALX4": 4.0,
        "ASPH": 4.0,
        "BMP5": 4.0,
        "BPNT2": 4.0,
        "COL1A1": 4.0,
        "COL2A1": 4.0,
        "DPH1": 4.0,
        "FGFR3": 4.0,
        "FMN1": 4.0,
        "FRAS1": 4.0,
        "GDF5": 4.0,
        "GLI2": 4.0,
        "GLI3": 4.0,
        "GPC6": 4.0,
        "HOXA13": 4.0,
        "HOXD12": 4.0,
        "HOXD13": 4.0,
        "IFT172": 4.0,
        "IFT56": 4.0,
        "IRF6": 4.0,
        "JAG2": 4.0,
        "KCNJ2": 4.0,
        "LNPK": 4.0,
        "PAX9": 4.0,
        "PITX1": 4.0,
        "PRICKLE1": 4.0,
        "QSOX1": 4.0,
        "RFNG": 4.0,
        "ROR2": 4.0,
        "RPL38": 4.0,
        "RSPO2": 4.0,
        "RUNX2": 4.0,
        "RYK": 4.0,
        "SATB2": 4.0,
        "SMOC1": 4.0,
        "TBX2": 4.0,
        "TBX4": 4.0,
        "TMEM107": 4.0,
        "TRPS1": 4.0,
        "TWIST1": 4.0,
        "VPS25": 4.0,
        "ZBTB16": 4.0,
        "ZEB1": 4.0,
        "ZFHX4": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "orofaciodigital_syndrome_x-screening-v1",
    "pathway_keywords": [
        "bone",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "interferon",
        "iron",
        "mapk",
        "notch",
        "pathway",
        "remodeling",
    ],
    "mechanism_keywords": [
        "bone",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "interferon",
        "iron",
        "mapk",
        "notch",
        "pathway",
        "remodeling",
    ],
    "reference_drug_ids": [
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_orofaciodigital_syndrome_x_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
