"""cerebellar pilocytic astrocytoma (CEREBELLAR_PILOCYTIC_ASTROCYTOMA) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "cerebellar pilocytic astrocytoma (CEREBELLAR_PILOCYTIC_ASTROCYTOMA)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of cerebellar pilocytic astrocytoma
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(cerebellar pilocytic astrocytoma[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(cerebellar pilocytic astrocytoma[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(cerebellar pilocytic astrocytoma[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(cerebellar pilocytic astrocytoma[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "cerebellar pilocytic astrocytoma OR cerebellar"
GWAS_SEARCH_TERMS = ["cerebellar pilocytic astrocytoma", "cerebellar"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AMY2A": 4.0,
        "ATRX": 4.0,
        "BCORL1": 4.0,
        "BLOC1S6": 4.0,
        "BRAF": 4.0,
        "CDKN2A": 4.0,
        "CNTN1": 4.0,
        "CNTN3": 4.0,
        "CTNNA2": 4.0,
        "EPB42": 4.0,
        "FAM131B": 4.0,
        "FGFR1": 4.0,
        "GPC5": 4.0,
        "IDH1": 4.0,
        "IKZF1": 4.0,
        "KIAA1549": 4.0,
        "KRAS": 4.0,
        "LHFPL6": 4.0,
        "LRP1B": 4.0,
        "NES": 4.0,
        "NF1": 4.0,
        "NRG1": 4.0,
        "NTRK2": 4.0,
        "PNKP": 4.0,
        "PPFIBP1": 4.0,
        "PRDM16": 4.0,
        "PRH1": 4.0,
        "PRH2": 4.0,
        "PTPN11": 4.0,
        "PTPRD": 4.0,
        "QKI": 4.0,
        "RAF1": 4.0,
        "ROBO2": 4.0,
        "SMAD2": 4.0,
        "SRGAP3": 4.0,
        "TCF12": 4.0,
        "TP53": 4.0,
        "VIM": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "acetaminophen",
        "dexamethasone",
        "midazolam",
        "midazolam hydrochloride",
        "roflumilast",
        "rolipram",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "cerebellar_pilocytic_astrocytoma-screening-v1",
    "pathway_keywords": [
        "cell",
        "cycle",
        "mapk",
        "regulation",
        "repair",
        "signaling",
    ],
    "mechanism_keywords": [
        "cell",
        "cycle",
        "mapk",
        "regulation",
        "repair",
        "signaling",
    ],
    "reference_drug_ids": [
        "CHEMBL112",
        "CHEMBL2108791",
        "CHEMBL63",
        "CHEMBL63",
        "CHEMBL1200420",
        "CHEMBL1200420",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_cerebellar_pilocytic_astrocytoma_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
