"""REM sleep behavior disorder (REM_SLEEP_BEHAVIOR_DISORDER) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "REM sleep behavior disorder (REM_SLEEP_BEHAVIOR_DISORDER)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of REM sleep behavior disorder
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(REM sleep behavior disorder[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(REM sleep behavior disorder[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(REM sleep behavior disorder[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(REM sleep behavior disorder[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "REM sleep behavior disorder OR REM"
GWAS_SEARCH_TERMS = ["REM sleep behavior disorder", "REM"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AOPEP": 4.0,
        "APOE": 4.0,
        "AVP": 4.0,
        "BDNF": 4.0,
        "BST1": 4.0,
        "C1QL1": 4.0,
        "CCK": 4.0,
        "CD4": 4.0,
        "CLOCK": 4.0,
        "CRH": 4.0,
        "DDC": 4.0,
        "DGKQ": 4.0,
        "FOS": 4.0,
        "FYN": 4.0,
        "GABRA1": 4.0,
        "GABRA2": 4.0,
        "GABRA3": 4.0,
        "GABRA5": 4.0,
        "GABRG1": 4.0,
        "GABRG2": 4.0,
        "GABRG3": 4.0,
        "GAK": 4.0,
        "GAS1": 4.0,
        "GBA1": 4.0,
        "GFAP": 4.0,
        "HCRT": 4.0,
        "IGLON5": 4.0,
        "IL1B": 4.0,
        "INPP5F": 4.0,
        "LAMP3": 4.0,
        "LGI1": 4.0,
        "LRRK2": 4.0,
        "MAPT": 4.0,
        "MC1R": 4.0,
        "MMRN1": 4.0,
        "MTNR1A": 4.0,
        "MTNR1B": 4.0,
        "MUC16": 4.0,
        "NEFL": 4.0,
        "NPC1": 4.0,
        "PLXNA3": 4.0,
        "PNMA2": 4.0,
        "PPOX": 4.0,
        "PRKN": 4.0,
        "PSAP": 4.0,
        "SEC23IP": 4.0,
        "SLC18A2": 4.0,
        "SLC50A1": 4.0,
        "SLC6A3": 4.0,
        "SMPD1": 4.0,
        "SNCA": 4.0,
        "SNCB": 4.0,
        "SNCG": 4.0,
        "STX1A": 4.0,
        "SYNM": 4.0,
        "TBX21": 4.0,
        "TF": 4.0,
        "TMEM175": 4.0,
        "TNF": 4.0,
        "WWC2": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "clonazepam",
        "tasimelteon",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "rem_sleep_behavior_disorder-screening-v1",
    "pathway_keywords": [
        "cascade",
        "cell",
        "complement",
        "dopamine",
        "gaba",
        "glutamate",
        "inflammasome",
        "lipid",
        "metabolism",
        "pathway",
    ],
    "mechanism_keywords": [
        "cascade",
        "cell",
        "complement",
        "dopamine",
        "gaba",
        "glutamate",
        "inflammasome",
        "lipid",
        "metabolism",
        "pathway",
    ],
    "reference_drug_ids": [
        "CHEMBL452",
        "CHEMBL452",
        "CHEMBL452",
        "CHEMBL2103822",
        "CHEMBL452",
        "CHEMBL452",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_rem_sleep_behavior_disorder_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
