"""pneumonia (PNEUMONIA) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "pneumonia (PNEUMONIA)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of pneumonia
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(pneumonia[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(pneumonia[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(pneumonia[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(pneumonia[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "pneumonia OR pneumonia"
GWAS_SEARCH_TERMS = ["pneumonia", "pneumonia"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABL1": 4.0,
        "ACE": 4.0,
        "ARPP21": 4.0,
        "ASXL1": 4.0,
        "BCR": 4.0,
        "CDH6": 4.0,
        "CHRNA5": 4.0,
        "CRP": 4.0,
        "CSF2": 4.0,
        "CXCR1": 4.0,
        "CXCR2": 4.0,
        "CYP3A4": 4.0,
        "CYP3A43": 4.0,
        "CYP3A5": 4.0,
        "CYP3A7": 4.0,
        "DPEP1": 4.0,
        "EXD1": 4.0,
        "GLB1": 4.0,
        "HBB": 4.0,
        "HMGCR": 4.0,
        "HNF1A": 4.0,
        "IFIH1": 4.0,
        "IFNAR1": 4.0,
        "IFNAR2": 4.0,
        "IL1B": 4.0,
        "IL1R1": 4.0,
        "IL1R2": 4.0,
        "IL6R": 4.0,
        "JAK1": 4.0,
        "JAK2": 4.0,
        "KIT": 4.0,
        "LY96": 4.0,
        "LZTFL1": 4.0,
        "MMP1": 4.0,
        "MMP13": 4.0,
        "MMP7": 4.0,
        "MMP8": 4.0,
        "MUC5AC": 4.0,
        "NR3C1": 4.0,
        "P2RY12": 4.0,
        "PDE4A": 4.0,
        "PDE4B": 4.0,
        "PDE4C": 4.0,
        "PDE4D": 4.0,
        "PDGFRB": 4.0,
        "PTGS1": 4.0,
        "PTGS2": 4.0,
        "SCHIP1": 4.0,
        "SERPINC1": 4.0,
        "SKI": 4.0,
        "SMAD3": 4.0,
        "SRSF2": 4.0,
        "TET2": 4.0,
        "TLR4": 4.0,
        "TLR7": 4.0,
        "TLR9": 4.0,
        "TNF": 4.0,
        "TNFRSF1A": 4.0,
        "TNFSF8": 4.0,
        "TSLP": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
        "etanercept",
        "interferon beta-1a",
    ],
    "moderate_risk": [
        "apremilast",
        "aspirin",
        "baricitinib",
        "bevacizumab",
        "captopril",
        "cholecalciferol",
        "clopidogrel",
        "cortisone acetate",
        "dexamethasone",
        "dexamethasone sodium phosphate",
        "doxycycline",
        "enalapril",
        "eritoran",
        "hydrocortisone",
        "imatinib",
        "lenzilumab",
        "methylprednisolone",
        "methylprednisolone hemisuccinate",
        "nitric oxide",
        "prednisone",
        "reparixin",
        "ritonavir",
        "ruxolitinib",
        "sarilumab",
        "tofacitinib",
    ],
    "low_risk": [
        "hydroxychloroquine",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "pneumonia-screening-v1",
    "pathway_keywords": [
        "(th2)",
        "cascade",
        "chemokine",
        "coagulation",
        "complement",
        "glucose",
        "inflammasome",
        "insulin",
        "lipid",
        "metabolism",
    ],
    "mechanism_keywords": [
        "(th2)",
        "cascade",
        "chemokine",
        "coagulation",
        "complement",
        "glucose",
        "inflammasome",
        "insulin",
        "lipid",
        "metabolism",
    ],
    "reference_drug_ids": [
        "CHEMBL191413",
        "CHEMBL941",
        "CHEMBL1200699",
        "CHEMBL1200699",
        "CHEMBL4650299",
        "CHEMBL221959",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_pneumonia_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
