"""ring chromosome 4 (RING_CHROMOSOME_4) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "ring chromosome 4 (RING_CHROMOSOME_4)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of ring chromosome 4
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(ring chromosome 4[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(ring chromosome 4[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(ring chromosome 4[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(ring chromosome 4[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "ring chromosome 4 OR ring"
GWAS_SEARCH_TERMS = ["ring chromosome 4", "ring"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "BMP5": 4.0,
        "CHKB": 4.0,
        "COL1A1": 4.0,
        "COL2A1": 4.0,
        "COL9A2": 4.0,
        "EVC2": 4.0,
        "EVX2": 4.0,
        "FBN1": 4.0,
        "FGFR3": 4.0,
        "FLNB": 4.0,
        "FMN1": 4.0,
        "GDF5": 4.0,
        "GLI3": 4.0,
        "GREM1": 4.0,
        "HOXA11": 4.0,
        "HOXA13": 4.0,
        "HOXD11": 4.0,
        "HOXD12": 4.0,
        "HOXD13": 4.0,
        "IFT80": 4.0,
        "LNPK": 4.0,
        "OFD1": 4.0,
        "PBXIP1": 4.0,
        "PHEX": 4.0,
        "PKDCC": 4.0,
        "PRKG2": 4.0,
        "PTHLH": 4.0,
        "RECK": 4.0,
        "ROR2": 4.0,
        "RSPO2": 4.0,
        "SFRP2": 4.0,
        "SLC29A4": 4.0,
        "SNAPC4": 4.0,
        "TIMP1": 4.0,
        "TP63": 4.0,
        "WNT7A": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "ring_chromosome_4-screening-v1",
    "pathway_keywords": [
        "dopamine",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "iron",
        "mapk",
        "remodeling",
        "serotonin",
        "signaling",
    ],
    "mechanism_keywords": [
        "dopamine",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "iron",
        "mapk",
        "remodeling",
        "serotonin",
        "signaling",
    ],
    "reference_drug_ids": [
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_ring_chromosome_4_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
