"""autosomal recessive limb-girdle muscular dystrophy type 2Y (AUTOSOMAL_RECESSIVE_LIMB_GIRDLE_MUSCULAR_DYSTROPHY_TYPE_2Y) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "autosomal recessive limb-girdle muscular dystrophy type 2Y (AUTOSOMAL_RECESSIVE_LIMB_GIRDLE_MUSCULAR_DYSTROPHY_TYPE_2Y)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Premature ventricular contraction",
    "Slowly progressive",
    "Camptodactyly of finger",
    "Early young adult onset",
    "Joint contracture",
    "Ankle flexion contracture",
    "Centrally nucleated skeletal muscle fibers",
    "Spinal rigidity",
    "Muscle weakness",
    "Elevated circulating creatine kinase activity",
    "Interosseus muscle atrophy",
    "Autosomal recessive inheritance",
    "Muscular dystrophy",
    "Decreased forced expiratory flow 25-75%",
    "Increased variability in muscle fiber diameter",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(autosomal recessive limb-girdle muscular dystrophy type 2Y[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(autosomal recessive limb-girdle muscular dystrophy type 2Y[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(autosomal recessive limb-girdle muscular dystrophy type 2Y[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(autosomal recessive limb-girdle muscular dystrophy type 2Y[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "autosomal recessive limb-girdle muscular dystrophy type 2Y OR autosomal"
GWAS_SEARCH_TERMS = ["autosomal recessive limb-girdle muscular dystrophy type 2Y", "autosomal"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACTMAP": 4.0,
        "ANO5": 4.0,
        "APOBEC2": 4.0,
        "APP": 4.0,
        "ASNSD1": 4.0,
        "CAPN3": 4.0,
        "CASQ2": 4.0,
        "CAV3": 4.0,
        "CHKB": 4.0,
        "COL13A1": 4.0,
        "COL6A1": 4.0,
        "COL6A3": 4.0,
        "DES": 4.0,
        "DMD": 4.0,
        "DMPK": 4.0,
        "DNAJB4": 4.0,
        "DNM2": 4.0,
        "DYSF": 4.0,
        "EMD": 4.0,
        "FBN1": 4.0,
        "FBN2": 4.0,
        "FKRP": 4.0,
        "FLNC": 4.0,
        "FOXN1": 4.0,
        "ITGA7": 4.0,
        "KLHL31": 4.0,
        "LAMA2": 4.0,
        "LARGE1": 4.0,
        "LDB3": 4.0,
        "LIMCH1": 4.0,
        "LMOD3": 4.0,
        "MBNL2": 4.0,
        "MBNL3": 4.0,
        "MSTN": 4.0,
        "MTM1": 4.0,
        "MYF5": 4.0,
        "MYH4": 4.0,
        "NEB": 4.0,
        "NFATC3": 4.0,
        "OBSCN": 4.0,
        "PABPN1": 4.0,
        "PLEC": 4.0,
        "RYR1": 4.0,
        "SCN4A": 4.0,
        "SELENON": 4.0,
        "SGCA": 4.0,
        "SGCB": 4.0,
        "SGCD": 4.0,
        "SGCG": 4.0,
        "SRPK3": 4.0,
        "SYNM": 4.0,
        "TCAP": 4.0,
        "TLN2": 4.0,
        "TNNT1": 4.0,
        "TOR1AIP1": 4.0,
        "TRDN": 4.0,
        "TRIM32": 4.0,
        "TRIM72": 4.0,
        "TTN": 4.0,
        "VCP": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "deflazacort",
    ],
    "low_risk": [
        "metformin",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "autosomal_recessive_limb_girdle_muscular_dystrophy_type_2y-screening-v1",
    "pathway_keywords": [
        "adhesion",
        "cell",
        "hormone",
        "integrin",
        "lipid",
        "metabolism",
        "pathway",
        "remodeling",
        "signaling",
        "thyroid",
    ],
    "mechanism_keywords": [
        "adhesion",
        "cell",
        "hormone",
        "integrin",
        "lipid",
        "metabolism",
        "pathway",
        "remodeling",
        "signaling",
        "thyroid",
    ],
    "reference_drug_ids": [
        "CHEMBL1431",
        "CHEMBL1431",
        "CHEMBL1431",
        "CHEMBL1431",
        "CHEMBL1431",
        "CHEMBL1431",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_autosomal_recessive_limb_girdle_muscular_dystrophy_type_2y_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
