"""46,XY sex reversal 4 (46_XY_SEX_REVERSAL_4) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "46,XY sex reversal 4 (46_XY_SEX_REVERSAL_4)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Hypergonadotropic hypogonadism",
    "Trigonocephaly",
    "Upslanted palpebral fissure",
    "Hydronephrosis",
    "Hypoplasia of the uterus",
    "Recurrent otitis media",
    "Anal atresia",
    "Gonadal dysgenesis",
    "Autosomal dominant inheritance",
    "Elevated circulating creatinine concentration",
    "Prominent nose",
    "Increased blood urea nitrogen",
    "High palate",
    "Distal symphalangism",
    "Agonadism",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(46,XY sex reversal 4[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(46,XY sex reversal 4[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(46,XY sex reversal 4[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(46,XY sex reversal 4[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "46,XY sex reversal 4 OR 46,XY"
GWAS_SEARCH_TERMS = ["46,XY sex reversal 4", "46,XY"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACVR2A": 4.0,
        "ADAMTS1": 4.0,
        "ARB2A": 4.0,
        "ARHGDIA": 4.0,
        "CFTR": 4.0,
        "CGB1": 4.0,
        "CGB2": 4.0,
        "CGB3": 4.0,
        "CGB5": 4.0,
        "CGB7": 4.0,
        "CGB8": 4.0,
        "COL4A4": 4.0,
        "DLG1": 4.0,
        "DMRT1": 4.0,
        "EYA1": 4.0,
        "FGF10": 4.0,
        "GNRHR": 4.0,
        "HOXA13": 4.0,
        "KISS1": 4.0,
        "LHB": 4.0,
        "LHCGR": 4.0,
        "LZTS2": 4.0,
        "PAX8": 4.0,
        "PTGS2": 4.0,
        "RET": 4.0,
        "ROBO1": 4.0,
        "SALL4": 4.0,
        "SIX1": 4.0,
        "ZEB1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "46_xy_sex_reversal_4-screening-v1",
    "pathway_keywords": [
        "cascade",
        "coagulation",
        "hormone",
        "remodeling",
        "signaling",
        "thyroid",
    ],
    "mechanism_keywords": [
        "cascade",
        "coagulation",
        "hormone",
        "remodeling",
        "signaling",
        "thyroid",
    ],
    "reference_drug_ids": [
        "CHEMBL1201621",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_46_xy_sex_reversal_4_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
