"""Charcot-Marie-Tooth disease X-linked recessive 2 (CHARCOT_MARIE_TOOTH_DISEASE_X_LINKED_RECESSIVE_2) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "Charcot-Marie-Tooth disease X-linked recessive 2 (CHARCOT_MARIE_TOOTH_DISEASE_X_LINKED_RECESSIVE_2)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Decreased motor nerve conduction velocity",
    "Upper limb muscle weakness",
    "Infantile onset",
    "Distal muscle weakness",
    "X-linked recessive inheritance",
    "Foot dorsiflexor weakness",
    "Steppage gait",
    "Areflexia",
    "Pes cavus",
    "Distal sensory impairment",
    "Intellectual disability",
    "Distal amyotrophy",
    "Peripheral neuropathy",
    "EMG: axonal abnormality",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(Charcot-Marie-Tooth disease X-linked recessive 2[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(Charcot-Marie-Tooth disease X-linked recessive 2[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(Charcot-Marie-Tooth disease X-linked recessive 2[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(Charcot-Marie-Tooth disease X-linked recessive 2[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "Charcot-Marie-Tooth disease X-linked recessive 2 OR Charcot-Marie-Tooth"
GWAS_SEARCH_TERMS = ["Charcot-Marie-Tooth disease X-linked recessive 2", "Charcot-Marie-Tooth"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABCD1": 4.0,
        "AGRN": 4.0,
        "CACNB4": 4.0,
        "CFAP276": 4.0,
        "CHRNE": 4.0,
        "CLCC1": 4.0,
        "CLP1": 4.0,
        "CNTNAP1": 4.0,
        "COX6A1": 4.0,
        "DNAJB4": 4.0,
        "ETV1": 4.0,
        "GARS1": 4.0,
        "GBX1": 4.0,
        "GMPPA": 4.0,
        "IGHMBP2": 4.0,
        "MDGA2": 4.0,
        "MORC2": 4.0,
        "MPZ": 4.0,
        "MTM1": 4.0,
        "NDRG1": 4.0,
        "PLP1": 4.0,
        "SCN4A": 4.0,
        "SCN8A": 4.0,
        "SELENON": 4.0,
        "SHC1": 4.0,
        "ZNF106": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "acetaminophen",
        "dexamethasone",
        "midazolam",
        "midazolam hydrochloride",
        "roflumilast",
        "rolipram",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "charcot_marie_tooth_disease_x_linked_recessive_2-screening-v1",
    "pathway_keywords": [
        "adhesion",
        "cascade",
        "cell",
        "coagulation",
        "integrin",
    ],
    "mechanism_keywords": [
        "adhesion",
        "cascade",
        "cell",
        "coagulation",
        "integrin",
    ],
    "reference_drug_ids": [
        "CHEMBL112",
        "CHEMBL2108791",
        "CHEMBL63",
        "CHEMBL63",
        "CHEMBL1200420",
        "CHEMBL1200420",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_charcot_marie_tooth_disease_x_linked_recessive_2_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
