"""infiltrating bladder urothelial carcinoma (INFILTRATING_BLADDER_UROTHELIAL_CARCINOMA) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'infiltrating bladder urothelial carcinoma (INFILTRATING_BLADDER_UROTHELIAL_CARCINOMA)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of infiltrating bladder urothelial carcinoma
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(infiltrating bladder urothelial carcinoma[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(infiltrating bladder urothelial carcinoma[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(infiltrating bladder urothelial carcinoma[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(infiltrating bladder urothelial carcinoma[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'infiltrating bladder urothelial carcinoma OR infiltrating'
GWAS_SEARCH_TERMS = ['infiltrating bladder urothelial carcinoma', 'infiltrating']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AR": 4.0,
        "BRCA2": 4.0,
        "CD274": 4.0,
        "CDH1": 4.0,
        "CEACAM5": 4.0,
        "CSF3R": 4.0,
        "CTLA4": 4.0,
        "DHFR": 4.0,
        "EGFR": 4.0,
        "ERBB2": 4.0,
        "EZH2": 4.0,
        "FGFR1": 4.0,
        "FGFR2": 4.0,
        "FGFR3": 4.0,
        "FGFR4": 4.0,
        "IGFBP2": 4.0,
        "IGFBP3": 4.0,
        "KDR": 4.0,
        "KRT5": 4.0,
        "LAG3": 4.0,
        "MET": 4.0,
        "MT-CO2": 4.0,
        "MUC1": 4.0,
        "NECTIN4": 4.0,
        "NEU1": 4.0,
        "NEURL1": 4.0,
        "NOTCH1": 4.0,
        "PDCD1": 4.0,
        "POLA1": 4.0,
        "POLA2": 4.0,
        "POLD1": 4.0,
        "POLD2": 4.0,
        "POLD3": 4.0,
        "POLD4": 4.0,
        "POLE": 4.0,
        "POLE2": 4.0,
        "POLE3": 4.0,
        "PRIM1": 4.0,
        "PRIM2": 4.0,
        "PSMD8": 4.0,
        "PTEN": 4.0,
        "PTGS2": 4.0,
        "RPL17": 4.0,
        "RPL17-C18orf32": 4.0,
        "RRM1": 4.0,
        "SNCA": 4.0,
        "SPATA2": 4.0,
        "TACSTD2": 4.0,
        "TOP1": 4.0,
        "TOP2A": 4.0,
        "TUBB": 4.0,
        "TUBB1": 4.0,
        "TUBB2A": 4.0,
        "TUBB2B": 4.0,
        "TUBB3": 4.0,
        "TUBB4A": 4.0,
        "TUBB4B": 4.0,
        "TUBB6": 4.0,
        "TUBB8": 4.0,
        "UPK3A": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
        "gemcitabine",
        "gemcitabine hydrochloride",
        "paclitaxel",
    ],
    "moderate_risk": [
        "apalutamide",
        "cabazitaxel",
        "cabozantinib",
        "cabozantinib s-malate",
        "docetaxel",
        "docetaxel anhydrous",
        "doxorubicin",
        "enfortumab vedotin",
        "erdafitinib",
        "methotrexate",
        "nivolumab",
        "pembrolizumab",
        "tremelimumab",
        "vinblastine",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "infiltrating_bladder_urothelial_carcinoma-screening-v1",
    "pathway_keywords": [
        "angiogenesis",
        "cell",
        "checkpoint",
        "hormone",
        "immune",
        "mapk",
        "mtor",
        "notch",
        "pi3k",
        "receptor",
    ],
    "mechanism_keywords": [
        "angiogenesis",
        "cell",
        "checkpoint",
        "hormone",
        "immune",
        "mapk",
        "mtor",
        "notch",
        "pi3k",
        "receptor",
    ],
    "reference_drug_ids": [
        "CHEMBL1201748",
        "CHEMBL3545252",
        "CHEMBL1201748",
        "CHEMBL1637",
        "CHEMBL1637",
        "CHEMBL3183409",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_infiltrating_bladder_urothelial_carcinoma_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
