"""colorectal cancer, susceptibility to, 3 (COLORECTAL_CANCER_SUSCEPTIBILITY_TO_3) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'colorectal cancer, susceptibility to, 3 (COLORECTAL_CANCER_SUSCEPTIBILITY_TO_3)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Colon cancer",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(colorectal cancer, susceptibility to, 3[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(colorectal cancer, susceptibility to, 3[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(colorectal cancer, susceptibility to, 3[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(colorectal cancer, susceptibility to, 3[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'colorectal cancer, susceptibility to, 3 OR colorectal'
GWAS_SEARCH_TERMS = ['colorectal cancer, susceptibility to, 3', 'colorectal']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AP2S1": 4.0,
        "APC": 4.0,
        "C20orf96": 4.0,
        "CDX2": 4.0,
        "FEM1A": 4.0,
        "FGF10": 4.0,
        "KRT7": 4.0,
        "LYPD8": 4.0,
        "MSH2": 4.0,
        "MUC2": 4.0,
        "NDST4": 4.0,
        "NR5A2": 4.0,
        "OR1E1": 4.0,
        "OR1E2": 4.0,
        "POLE": 4.0,
        "PROX2": 4.0,
        "PTGS1": 4.0,
        "RET": 4.0,
        "SEMA6C": 4.0,
        "SLC22A4": 4.0,
        "SLC49A4": 4.0,
        "SMAD4": 4.0,
        "SMAD7": 4.0,
        "ST6GALNAC1": 4.0,
        "STK11": 4.0,
        "TGFB1": 4.0,
        "THG1L": 4.0,
        "USH1C": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "colorectal_cancer_susceptibility_to_3-screening-v1",
    "pathway_keywords": [
        "cascade",
        "coagulation",
        "dopamine",
        "hormone",
        "repair",
        "serotonin",
        "signaling",
        "thyroid",
    ],
    "mechanism_keywords": [
        "cascade",
        "coagulation",
        "dopamine",
        "hormone",
        "repair",
        "serotonin",
        "signaling",
        "thyroid",
    ],
    "reference_drug_ids": [
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_colorectal_cancer_susceptibility_to_3_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
