"""Waardenburg syndrome type 1 (WAARDENBURG_SYNDROME_TYPE_1) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "Waardenburg syndrome type 1 (WAARDENBURG_SYNDROME_TYPE_1)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Supernumerary ribs",
    "Supernumerary vertebrae",
    "Orofacial cleft",
    "White eyebrow",
    "Mandibular prognathia",
    "Smooth philtrum",
    "White forelock",
    "Thick eyebrow",
    "Telecanthus",
    "Premature graying of hair",
    "Blue irides",
    "Congenital sensorineural hearing impairment",
    "Blepharophimosis",
    "Myelomeningocele",
    "Hypertelorism",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(Waardenburg syndrome type 1[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(Waardenburg syndrome type 1[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(Waardenburg syndrome type 1[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(Waardenburg syndrome type 1[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "Waardenburg syndrome type 1 OR Waardenburg"
GWAS_SEARCH_TERMS = ["Waardenburg syndrome type 1", "Waardenburg"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABO": 4.0,
        "ALX1": 4.0,
        "ATP2B2": 4.0,
        "BLOC1S5": 4.0,
        "BLOC1S5-TXNDC5": 4.0,
        "BMP7": 4.0,
        "CISD2": 4.0,
        "CMA1": 4.0,
        "COL11A1": 4.0,
        "EDA": 4.0,
        "EDN3": 4.0,
        "EDNRB": 4.0,
        "EYA4": 4.0,
        "GATA3": 4.0,
        "GLI3": 4.0,
        "HNF1B": 4.0,
        "JAG1": 4.0,
        "MCAT": 4.0,
        "MCTS1": 4.0,
        "MITF": 4.0,
        "OSTM1": 4.0,
        "PAX2": 4.0,
        "PAX3": 4.0,
        "PAX6": 4.0,
        "POLR2F": 4.0,
        "PXDN": 4.0,
        "RET": 4.0,
        "RPL24": 4.0,
        "RYR1": 4.0,
        "RYR2": 4.0,
        "SLC16A1": 4.0,
        "SLC24A5": 4.0,
        "SOX10": 4.0,
        "TET1": 4.0,
        "TFF2": 4.0,
        "TP53": 4.0,
        "TYR": 4.0,
        "WFS1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "waardenburg_syndrome_type_1-screening-v1",
    "pathway_keywords": [
        "(th2)",
        "cardiac",
        "cascade",
        "channel",
        "coagulation",
        "conduction",
        "glucose",
        "hedgehog",
        "hepcidin",
        "homeostasis",
    ],
    "mechanism_keywords": [
        "(th2)",
        "cardiac",
        "cascade",
        "channel",
        "coagulation",
        "conduction",
        "glucose",
        "hedgehog",
        "hepcidin",
        "homeostasis",
    ],
    "reference_drug_ids": [
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_waardenburg_syndrome_type_1_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
