"""non-melanoma skin carcinoma (NON_MELANOMA_SKIN_CARCINOMA) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "non-melanoma skin carcinoma (NON_MELANOMA_SKIN_CARCINOMA)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of non-melanoma skin carcinoma
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(non-melanoma skin carcinoma[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(non-melanoma skin carcinoma[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(non-melanoma skin carcinoma[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(non-melanoma skin carcinoma[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "non-melanoma skin carcinoma OR non-melanoma"
GWAS_SEARCH_TERMS = ["non-melanoma skin carcinoma", "non-melanoma"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "BACH2": 4.0,
        "BNC2": 4.0,
        "CASP8": 4.0,
        "CDK5RAP1": 4.0,
        "CDKAL1": 4.0,
        "CDKN2B": 4.0,
        "CELF2": 4.0,
        "CLPTM1L": 4.0,
        "CNTNAP3": 4.0,
        "CPVL": 4.0,
        "CTXN2": 4.0,
        "CUX1": 4.0,
        "CYP1B1": 4.0,
        "CYRIA": 4.0,
        "DEF8": 4.0,
        "DHX35": 4.0,
        "FADS2": 4.0,
        "FOXP1": 4.0,
        "IRF4": 4.0,
        "JDP2": 4.0,
        "KANK1": 4.0,
        "KRT5": 4.0,
        "LPP": 4.0,
        "MC1R": 4.0,
        "MYCN": 4.0,
        "OCA2": 4.0,
        "ODC1": 4.0,
        "PRL": 4.0,
        "PTCH1": 4.0,
        "PTGS1": 4.0,
        "PTGS2": 4.0,
        "PTPN14": 4.0,
        "PTPN22": 4.0,
        "RALY": 4.0,
        "RBBP8": 4.0,
        "RCC2": 4.0,
        "RGS22": 4.0,
        "RHOU": 4.0,
        "RNASET2": 4.0,
        "SEC24B": 4.0,
        "SLC24A5": 4.0,
        "SLC45A2": 4.0,
        "SMC2": 4.0,
        "SPATA31A5": 4.0,
        "SPDL1": 4.0,
        "SPG7": 4.0,
        "ST3GAL4": 4.0,
        "TGM3": 4.0,
        "TICAM1": 4.0,
        "TLR7": 4.0,
        "TNFRSF10B": 4.0,
        "TNS3": 4.0,
        "TP63": 4.0,
        "TPCN2": 4.0,
        "TRPV1": 4.0,
        "TYR": 4.0,
        "XPA": 4.0,
        "ZBTB10": 4.0,
        "ZFHX4": 4.0,
        "ZFPM1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
        "peginterferon alfa-2a",
    ],
    "moderate_risk": [
        "acetaminophen",
        "celecoxib",
        "diclofenac",
        "eflornithine",
        "gefitinib",
        "imiquimod",
        "methotrexate",
        "triamcinolone",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "non_melanoma_skin_carcinoma-screening-v1",
    "pathway_keywords": [
        "adhesion",
        "apoptosis",
        "cascade",
        "cell",
        "checkpoint",
        "coagulation",
        "cycle",
        "hedgehog",
        "hormone",
        "immune",
    ],
    "mechanism_keywords": [
        "adhesion",
        "apoptosis",
        "cascade",
        "cell",
        "checkpoint",
        "coagulation",
        "cycle",
        "hedgehog",
        "hormone",
        "immune",
    ],
    "reference_drug_ids": [
        "CHEMBL118",
        "CHEMBL1201560",
        "CHEMBL34259",
        "CHEMBL118",
        "CHEMBL112",
        "CHEMBL139",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_non_melanoma_skin_carcinoma_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
