"""3-methoxytyramine sulfate measurement (3_METHOXYTYRAMINE_SULFATE_MEASUREMENT) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "3-methoxytyramine sulfate measurement (3_METHOXYTYRAMINE_SULFATE_MEASUREMENT)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of 3-methoxytyramine sulfate measurement
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(3-methoxytyramine sulfate measurement[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(3-methoxytyramine sulfate measurement[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(3-methoxytyramine sulfate measurement[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(3-methoxytyramine sulfate measurement[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "3-methoxytyramine sulfate measurement OR 3-methoxytyramine"
GWAS_SEARCH_TERMS = ["3-methoxytyramine sulfate measurement", "3-methoxytyramine"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABCG2": 4.0,
        "ABLIM2": 4.0,
        "ADGRL2": 4.0,
        "AGTR1": 4.0,
        "AQP10": 4.0,
        "ARHGAP25": 4.0,
        "AZI2": 4.0,
        "BPNT2": 4.0,
        "CBLN2": 4.0,
        "CDH26": 4.0,
        "CDH4": 4.0,
        "CNTN4": 4.0,
        "DORIP1": 4.0,
        "DSC3": 4.0,
        "ENPP2": 4.0,
        "ENSG00000289710": 4.0,
        "EXOC4": 4.0,
        "FAM217B": 4.0,
        "FAR2": 4.0,
        "FBXO15": 4.0,
        "FNDC3B": 4.0,
        "GALNT18": 4.0,
        "GCH1": 4.0,
        "GLIS3": 4.0,
        "GRIA2": 4.0,
        "HEYL": 4.0,
        "HIP1": 4.0,
        "IRX5": 4.0,
        "KCP": 4.0,
        "LMO4": 4.0,
        "LRP1B": 4.0,
        "MDFI": 4.0,
        "MSRA": 4.0,
        "NCAM2": 4.0,
        "NELL1": 4.0,
        "NFKBIZ": 4.0,
        "NR3C2": 4.0,
        "NUDT12": 4.0,
        "PDCD6IP": 4.0,
        "PKDCC": 4.0,
        "PMP22": 4.0,
        "PPP1R3D": 4.0,
        "RNF220": 4.0,
        "SDC1": 4.0,
        "SLC6A11": 4.0,
        "TAF4": 4.0,
        "TH": 4.0,
        "TIMM21": 4.0,
        "TMEM229A": 4.0,
        "TMOD1": 4.0,
        "TTPAL": 4.0,
        "VIT": 4.0,
        "ZBTB40": 4.0,
        "ZBTB7C": 4.0,
        "ZCWPW2": 4.0,
        "ZNF608": 4.0,
        "ZNF761": 4.0,
        "ZNRF2": 4.0,
        "ZNRF4": 4.0,
        "ZPLD1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "3_methoxytyramine_sulfate_measurement-screening-v1",
    "pathway_keywords": [
        "angiotensin",
        "cascade",
        "coagulation",
        "dopamine",
        "gaba",
        "glutamate",
        "hedgehog",
        "pathway",
        "renin",
        "serotonin",
    ],
    "mechanism_keywords": [
        "angiotensin",
        "cascade",
        "coagulation",
        "dopamine",
        "gaba",
        "glutamate",
        "hedgehog",
        "pathway",
        "renin",
        "serotonin",
    ],
    "reference_drug_ids": [],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_3_methoxytyramine_sulfate_measurement_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
