"""lymphoid leukemia (LYMPHOID_LEUKEMIA) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "lymphoid leukemia (LYMPHOID_LEUKEMIA)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of lymphoid leukemia
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(lymphoid leukemia[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(lymphoid leukemia[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(lymphoid leukemia[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(lymphoid leukemia[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "lymphoid leukemia OR lymphoid"
GWAS_SEARCH_TERMS = ["lymphoid leukemia", "lymphoid"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABL1": 4.0,
        "ACOXL": 4.0,
        "BCL2": 4.0,
        "BCR": 4.0,
        "BLK": 4.0,
        "C11orf21": 4.0,
        "CD19": 4.0,
        "CD22": 4.0,
        "CD3D": 4.0,
        "CD3E": 4.0,
        "CD3G": 4.0,
        "CHD2": 4.0,
        "CHEK2": 4.0,
        "DHFR": 4.0,
        "DUSP22": 4.0,
        "EPHA2": 4.0,
        "FGR": 4.0,
        "FRK": 4.0,
        "FYN": 4.0,
        "GRAMD1B": 4.0,
        "HCK": 4.0,
        "IGLL5": 4.0,
        "IRF4": 4.0,
        "KIT": 4.0,
        "LCK": 4.0,
        "LYN": 4.0,
        "MYD88": 4.0,
        "NOTCH1": 4.0,
        "NR3C1": 4.0,
        "PDGFRB": 4.0,
        "POLA1": 4.0,
        "POLA2": 4.0,
        "POLD1": 4.0,
        "POLD2": 4.0,
        "POLD3": 4.0,
        "POLD4": 4.0,
        "POLE": 4.0,
        "POLE2": 4.0,
        "POLE3": 4.0,
        "PPAT": 4.0,
        "PRIM1": 4.0,
        "PRIM2": 4.0,
        "RPLP1": 4.0,
        "RRM1": 4.0,
        "SF3B1": 4.0,
        "SP140": 4.0,
        "SRC": 4.0,
        "SRMS": 4.0,
        "TOP2A": 4.0,
        "TP53": 4.0,
        "TUBB": 4.0,
        "TUBB1": 4.0,
        "TUBB2A": 4.0,
        "TUBB2B": 4.0,
        "TUBB3": 4.0,
        "TUBB4A": 4.0,
        "TUBB4B": 4.0,
        "TUBB6": 4.0,
        "TUBB8": 4.0,
        "YES1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
        "alemtuzumab",
    ],
    "moderate_risk": [
        "apg115",
        "blinatumomab",
        "bortezomib",
        "cytarabine",
        "dasatinib",
        "dexamethasone",
        "dinaciclib",
        "doxorubicin",
        "etoposide",
        "fludarabine phosphate",
        "forodesine",
        "forodesine hydrochloride",
        "ibrutinib",
        "mercaptopurine anhydrous",
        "mitoxantrone",
        "mk-2206",
        "mycophenolate mofetil",
        "obatoclax mesylate",
        "sunitinib malate",
        "tozasertib",
        "vincristine",
        "vincristine sulfate",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "lymphoid_leukemia-screening-v1",
    "pathway_keywords": [
        "apoptosis",
        "cascade",
        "cell",
        "coagulation",
        "innate",
        "interferon",
        "mast",
        "notch",
        "pathway",
        "receptor",
    ],
    "mechanism_keywords": [
        "apoptosis",
        "cascade",
        "cell",
        "coagulation",
        "innate",
        "interferon",
        "mast",
        "notch",
        "pathway",
        "receptor",
    ],
    "reference_drug_ids": [
        "CHEMBL1421",
        "CHEMBL1421",
        "CHEMBL1421",
        "CHEMBL1567",
        "CHEMBL1742992",
        "CHEMBL2103840",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_lymphoid_leukemia_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
