"""Poroma (POROMA) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "Poroma (POROMA)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of Poroma
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(Poroma[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(Poroma[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(Poroma[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(Poroma[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "Poroma OR Poroma"
GWAS_SEARCH_TERMS = ["Poroma", "Poroma"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AKT1": 4.0,
        "APC": 4.0,
        "AR": 4.0,
        "BAP1": 4.0,
        "CDKN2A": 4.0,
        "CEACAM3": 4.0,
        "CEACAM7": 4.0,
        "CLDN4": 4.0,
        "CREBBP": 4.0,
        "CYLD": 4.0,
        "DCPS": 4.0,
        "EP300": 4.0,
        "EPCAM": 4.0,
        "ERBB4": 4.0,
        "EWSR1": 4.0,
        "FAP": 4.0,
        "FLT3": 4.0,
        "FUS": 4.0,
        "GATA3": 4.0,
        "GSDMB": 4.0,
        "HRAS": 4.0,
        "IL9": 4.0,
        "JAK2": 4.0,
        "KIT": 4.0,
        "KRT1": 4.0,
        "KRT5": 4.0,
        "LEF1": 4.0,
        "LMO1": 4.0,
        "MAML2": 4.0,
        "MAPK1": 4.0,
        "MUC5AC": 4.0,
        "MYB": 4.0,
        "NECTIN4": 4.0,
        "NF1": 4.0,
        "NF2": 4.0,
        "NFIB": 4.0,
        "NFKB1": 4.0,
        "NOTCH1": 4.0,
        "NUTM1": 4.0,
        "PAK2": 4.0,
        "PALB2": 4.0,
        "PCNA": 4.0,
        "PLAG1": 4.0,
        "POLE": 4.0,
        "PROM1": 4.0,
        "PSG2": 4.0,
        "PTPRG": 4.0,
        "PYGO1": 4.0,
        "RAF1": 4.0,
        "RB1": 4.0,
        "S100A1": 4.0,
        "S100B": 4.0,
        "SETD2": 4.0,
        "SLURP1": 4.0,
        "STK36": 4.0,
        "TAFAZZIN": 4.0,
        "TP53": 4.0,
        "TRPS1": 4.0,
        "WWTR1": 4.0,
        "YAP1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "adapalene",
        "betamethasone dipropionate",
        "betamethasone valerate",
        "cholecalciferol",
        "clobetasol propionate",
        "desonide",
        "desoximetasone",
        "diflorasone diacetate",
        "doxycycline",
        "dupilumab",
        "fluocinolone acetonide",
        "fluocinonide",
        "fluticasone propionate",
        "halcinonide",
        "halobetasol propionate",
        "hydrocortisone",
        "hydrocortisone acetate",
        "hydroxyzine pamoate",
        "levocetirizine dihydrochloride",
        "lidocaine",
        "melatonin",
        "midazolam",
        "mometasone furoate",
        "prednicarbate",
        "prilocaine",
        "sildenafil",
        "tacrolimus anhydrous",
        "tazarotene",
        "tetracaine",
        "triamcinolone",
        "triamcinolone acetonide",
    ],
    "low_risk": [
        "diltiazem",
        "diltiazem hydrochloride",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "poroma-screening-v1",
    "pathway_keywords": [
        "(th2)",
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "mapk",
        "mast",
        "mtor",
        "notch",
        "pathway",
    ],
    "mechanism_keywords": [
        "(th2)",
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "mapk",
        "mast",
        "mtor",
        "notch",
        "pathway",
    ],
    "reference_drug_ids": [
        "CHEMBL1265",
        "CHEMBL79",
        "CHEMBL989",
        "CHEMBL698",
        "CHEMBL79",
        "CHEMBL655",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_poroma_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
