"""autosomal recessive spinocerebellar ataxia 17 (AUTOSOMAL_RECESSIVE_SPINOCEREBELLAR_ATAXIA_17) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = (
    "autosomal recessive spinocerebellar ataxia 17 (AUTOSOMAL_RECESSIVE_SPINOCEREBELLAR_ATAXIA_17)"
)
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Intention tremor",
    "Dystonia",
    "Congenital onset",
    "Childhood onset",
    "Broad-based gait",
    "Delayed speech and language development",
    "Global developmental delay",
    "Thick eyebrow",
    "Synophrys",
    "Easy fatigability",
    "Intellectual disability",
    "Limb ataxia",
    "Autosomal recessive inheritance",
    "Hypotonia",
    "Dysarthria",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(autosomal recessive spinocerebellar ataxia 17[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(autosomal recessive spinocerebellar ataxia 17[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(autosomal recessive spinocerebellar ataxia 17[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(autosomal recessive spinocerebellar ataxia 17[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "autosomal recessive spinocerebellar ataxia 17 OR autosomal"
GWAS_SEARCH_TERMS = ["autosomal recessive spinocerebellar ataxia 17", "autosomal"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AARS1": 4.0,
        "ACP2": 4.0,
        "AGTPBP1": 4.0,
        "ANK3": 4.0,
        "ANKFY1": 4.0,
        "ARCN1": 4.0,
        "ATCAY": 4.0,
        "ATP2B2": 4.0,
        "ATXN7": 4.0,
        "CA8": 4.0,
        "CACNA1A": 4.0,
        "CACNA1G": 4.0,
        "CANX": 4.0,
        "CERS1": 4.0,
        "CHP1": 4.0,
        "CLCN1": 4.0,
        "CLP1": 4.0,
        "CNTNAP1": 4.0,
        "CWF19L1": 4.0,
        "DAB1": 4.0,
        "DCC": 4.0,
        "ELP2": 4.0,
        "EN1": 4.0,
        "FBXO41": 4.0,
        "GALC": 4.0,
        "GDF1": 4.0,
        "GLB1": 4.0,
        "GLRA1": 4.0,
        "GRID2": 4.0,
        "GRM1": 4.0,
        "INPP4A": 4.0,
        "KCNJ6": 4.0,
        "KCNN2": 4.0,
        "KCNV1": 4.0,
        "MYO5A": 4.0,
        "NPC2": 4.0,
        "PMP22": 4.0,
        "PRKCG": 4.0,
        "PRNP": 4.0,
        "PSAP": 4.0,
        "RELN": 4.0,
        "RORA": 4.0,
        "RREB1": 4.0,
        "SCN8A": 4.0,
        "SIL1": 4.0,
        "SPTBN2": 4.0,
        "SPTBN4": 4.0,
        "SRRM3": 4.0,
        "STARD9": 4.0,
        "SULT4A1": 4.0,
        "SYT2": 4.0,
        "TBP": 4.0,
        "TMEM176B": 4.0,
        "TPP1": 4.0,
        "TUBB4A": 4.0,
        "UNC5C": 4.0,
        "WDR81": 4.0,
        "WNT1": 4.0,
        "ZIC1": 4.0,
        "ZNF423": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "befiradol",
        "deutetrabenazine",
        "famotidine",
        "levetiracetam",
        "propranolol",
        "propranolol hydrochloride",
        "sarizotan",
        "sarizotan hydrochloride",
        "tetrabenazine",
        "valbenazine",
        "valbenazine tosylate",
    ],
    "low_risk": [
        "levetiracetam",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "autosomal_recessive_spinocerebellar_ataxia_17-screening-v1",
    "pathway_keywords": [
        "angiotensin",
        "bone",
        "cardiac",
        "channel",
        "conduction",
        "gaba",
        "glutamate",
        "inflammasome",
        "metabolism",
        "pathway",
    ],
    "mechanism_keywords": [
        "angiotensin",
        "bone",
        "cardiac",
        "channel",
        "conduction",
        "gaba",
        "glutamate",
        "inflammasome",
        "metabolism",
        "pathway",
    ],
    "reference_drug_ids": [
        "CHEMBL220808",
        "CHEMBL1286",
        "CHEMBL2146110",
        "CHEMBL1671",
        "CHEMBL220808",
        "CHEMBL27",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_autosomal_recessive_spinocerebellar_ataxia_17_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
