"""familial lipoprotein lipase deficiency (FAMILIAL_LIPOPROTEIN_LIPASE_DEFICIENCY) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'familial lipoprotein lipase deficiency (FAMILIAL_LIPOPROTEIN_LIPASE_DEFICIENCY)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Jaundice",
    "Splenomegaly",
    "Hyperlipidemia",
    "Hepatosplenomegaly",
    "Episodic abdominal pain",
    "Lactescent serum",
    "Increased circulating chylomicron concentration",
    "Nausea",
    "Lipemia retinalis",
    "Autosomal recessive inheritance",
    "Young adult onset",
    "Vomiting",
    "Acute pancreatitis",
    "Precocious atherosclerosis",
    "Hypercholesterolemia",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(familial lipoprotein lipase deficiency[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(familial lipoprotein lipase deficiency[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(familial lipoprotein lipase deficiency[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(familial lipoprotein lipase deficiency[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'familial lipoprotein lipase deficiency OR familial'
GWAS_SEARCH_TERMS = ['familial lipoprotein lipase deficiency', 'familial']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABCB11": 4.0,
        "ABCB4": 4.0,
        "ABCC2": 4.0,
        "ABCG5": 4.0,
        "ACOT12": 4.0,
        "ANGPTL3": 4.0,
        "APC": 4.0,
        "APOA1": 4.0,
        "APOA5": 4.0,
        "APOB": 4.0,
        "APOC1": 4.0,
        "APOC3": 4.0,
        "APOE": 4.0,
        "BHMT": 4.0,
        "C11orf86": 4.0,
        "CDCA7L": 4.0,
        "COL4A5": 4.0,
        "CYP27A1": 4.0,
        "CYP8B1": 4.0,
        "ECHDC1": 4.0,
        "FBXL5": 4.0,
        "FHIP2B": 4.0,
        "GPIHBP1": 4.0,
        "ILRUN": 4.0,
        "IMPDH1": 4.0,
        "IMPDH2": 4.0,
        "LDLR": 4.0,
        "LEP": 4.0,
        "LIPG": 4.0,
        "LMF1": 4.0,
        "LPL": 4.0,
        "LRP6": 4.0,
        "LYN": 4.0,
        "MTTP": 4.0,
        "NCOA6": 4.0,
        "NPC1L1": 4.0,
        "NR1D1": 4.0,
        "NR1H3": 4.0,
        "NR1H4": 4.0,
        "NR3C1": 4.0,
        "NSMCE1": 4.0,
        "OCA2": 4.0,
        "ORM1": 4.0,
        "ORM2": 4.0,
        "PLVAP": 4.0,
        "PLXNC1": 4.0,
        "PON3": 4.0,
        "PPIA": 4.0,
        "SAR1B": 4.0,
        "SCARB1": 4.0,
        "SCP2": 4.0,
        "SLC10A2": 4.0,
        "SLC27A5": 4.0,
        "SOAT1": 4.0,
        "SOAT2": 4.0,
        "STARD10": 4.0,
        "TM6SF2": 4.0,
        "TXNIP": 4.0,
        "WDFY2": 4.0,
        "WDR27": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "cyclosporine",
        "methylprednisolone",
        "mycophenolate mofetil",
        "prednisolone",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "familial_lipoprotein_lipase_deficiency-screening-v1",
    "pathway_keywords": [
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "lipid",
        "mast",
        "metabolism",
        "receptor",
        "regulation",
        "remodeling",
    ],
    "mechanism_keywords": [
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "lipid",
        "mast",
        "metabolism",
        "receptor",
        "regulation",
        "remodeling",
    ],
    "reference_drug_ids": [
        "CHEMBL1456",
        "CHEMBL1456",
        "CHEMBL3544989",
        "CHEMBL1456",
        "CHEMBL131",
        "CHEMBL1456",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_familial_lipoprotein_lipase_deficiency_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
