"""intellectual disability, X-linked syndromic, Turner type (INTELLECTUAL_DISABILITY_X_LINKED_SYNDROMIC_TURNER_TYPE) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "intellectual disability, X-linked syndromic, Turner type (INTELLECTUAL_DISABILITY_X_LINKED_SYNDROMIC_TURNER_TYPE)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Long philtrum",
    "HP_0002370",
    "Micropenis",
    "Low posterior hairline",
    "Hypospadias",
    "High palate",
    "Oligodontia",
    "Short philtrum",
    "Blepharophimosis",
    "Absent speech",
    "Delayed ability to walk",
    "Short foot",
    "X-linked inheritance",
    "Short nose",
    "Nystagmus",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(intellectual disability, X-linked syndromic, Turner type[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(intellectual disability, X-linked syndromic, Turner type[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(intellectual disability, X-linked syndromic, Turner type[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(intellectual disability, X-linked syndromic, Turner type[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "intellectual disability, X-linked syndromic, Turner type OR intellectual"
GWAS_SEARCH_TERMS = ["intellectual disability, X-linked syndromic, Turner type", "intellectual"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AR": 4.0,
        "ARB2A": 4.0,
        "BCL2L2": 4.0,
        "BCL2L2-PABPN1": 4.0,
        "CHUK": 4.0,
        "CNOT7": 4.0,
        "DHH": 4.0,
        "EFCAB5": 4.0,
        "EGR4": 4.0,
        "FMR1": 4.0,
        "FSHR": 4.0,
        "FSTL3": 4.0,
        "GKAP1": 4.0,
        "HUWE1": 4.0,
        "IL21": 4.0,
        "KATNA1": 4.0,
        "KDM6A": 4.0,
        "LAMTOR1": 4.0,
        "LMNA": 4.0,
        "MAP7": 4.0,
        "MFSD2A": 4.0,
        "NF1": 4.0,
        "NR0B1": 4.0,
        "PATZ1": 4.0,
        "PAX6": 4.0,
        "PLPP6": 4.0,
        "PRL": 4.0,
        "PTDSS2": 4.0,
        "SAFB2": 4.0,
        "SIX3": 4.0,
        "SIX5": 4.0,
        "SMAD2": 4.0,
        "SULT1E1": 4.0,
        "TCTN1": 4.0,
        "USP9X": 4.0,
        "ZIC2": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "amantadine",
        "amantadine hydrochloride",
        "aripiprazole",
        "brexpiprazole",
        "cannabidiol",
        "chlorpromazine",
        "dexmedetomidine",
        "galantamine",
        "galantamine hydrobromide",
        "gts-21",
        "haloperidol",
        "ketamine",
        "lamotrigine",
        "mifepristone",
        "naltrexone",
        "olanzapine",
        "osoresnontrine",
        "paliperidone",
        "quetiapine",
        "risperidone",
        "rituximab",
        "trifluoperazine hydrochloride",
        "valproic acid",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "intellectual_disability_x_linked_syndromic_turner_type-screening-v1",
    "pathway_keywords": [
        "apoptosis",
        "hedgehog",
        "metabolism",
        "mtor",
        "pathway",
        "pi3k",
        "signaling",
        "th17",
        "xenobiotic",
    ],
    "mechanism_keywords": [
        "apoptosis",
        "hedgehog",
        "metabolism",
        "mtor",
        "pathway",
        "pi3k",
        "signaling",
        "th17",
        "xenobiotic",
    ],
    "reference_drug_ids": [
        "CHEMBL134713",
        "CHEMBL1569",
        "CHEMBL741",
        "CHEMBL1569",
        "CHEMBL741",
        "CHEMBL660",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_intellectual_disability_x_linked_syndromic_turner_type_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
