"""functional brain measurement (FUNCTIONAL_BRAIN_MEASUREMENT) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "functional brain measurement (FUNCTIONAL_BRAIN_MEASUREMENT)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of functional brain measurement
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(functional brain measurement[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(functional brain measurement[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(functional brain measurement[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(functional brain measurement[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "functional brain measurement OR functional"
GWAS_SEARCH_TERMS = ["functional brain measurement", "functional"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACO1": 4.0,
        "ANGPTL5": 4.0,
        "ANO1": 4.0,
        "APOC1": 4.0,
        "APOE": 4.0,
        "ARB2A": 4.0,
        "ATP2A2": 4.0,
        "ATP8B1": 4.0,
        "B9D1": 4.0,
        "BLID": 4.0,
        "CELSR1": 4.0,
        "DACT1": 4.0,
        "DGKB": 4.0,
        "DPP4": 4.0,
        "EPHA3": 4.0,
        "FANCL": 4.0,
        "FBXL5": 4.0,
        "FBXO11": 4.0,
        "FES": 4.0,
        "FHL5": 4.0,
        "FOXF2": 4.0,
        "FOXP2": 4.0,
        "FURIN": 4.0,
        "HPS1": 4.0,
        "HSPG2": 4.0,
        "IFITM2": 4.0,
        "IL17RD": 4.0,
        "INPP5A": 4.0,
        "IRAG1": 4.0,
        "MAPK7": 4.0,
        "MSRB3": 4.0,
        "NOC3L": 4.0,
        "NPM1": 4.0,
        "NRG2": 4.0,
        "NTF3": 4.0,
        "NTRK2": 4.0,
        "PAX8": 4.0,
        "PKDCC": 4.0,
        "PLCE1": 4.0,
        "PLEKHG3": 4.0,
        "PROS1": 4.0,
        "PYROXD2": 4.0,
        "RIGI": 4.0,
        "RRAS": 4.0,
        "SLC11A2": 4.0,
        "SLC39A12": 4.0,
        "SMIM21": 4.0,
        "STAB1": 4.0,
        "TBC1D22A": 4.0,
        "TBC1D5": 4.0,
        "TF": 4.0,
        "THBS1": 4.0,
        "THOC1": 4.0,
        "TRAM1L1": 4.0,
        "UFL1": 4.0,
        "VCAN": 4.0,
        "VRK2": 4.0,
        "WNT16": 4.0,
        "ZIC4": 4.0,
        "ZNG1B": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "functional_brain_measurement-screening-v1",
    "pathway_keywords": [
        "autophagy",
        "bone",
        "cascade",
        "coagulation",
        "dopamine",
        "glucose",
        "inflammasome",
        "insulin",
        "interferon",
        "lipid",
    ],
    "mechanism_keywords": [
        "autophagy",
        "bone",
        "cascade",
        "coagulation",
        "dopamine",
        "glucose",
        "inflammasome",
        "insulin",
        "interferon",
        "lipid",
    ],
    "reference_drug_ids": [],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_functional_brain_measurement_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
