"""lipodystrophy-intellectual disability-deafness syndrome (LIPODYSTROPHY_INTELLECTUAL_DISABILITY_DEAFNESS_SYNDROME) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "lipodystrophy-intellectual disability-deafness syndrome (LIPODYSTROPHY_INTELLECTUAL_DISABILITY_DEAFNESS_SYNDROME)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Cubitus valgus",
    "Slender long bones with narrow diaphyses",
    "Progeroid facial appearance",
    "Sparse facial hair",
    "Intrauterine growth retardation",
    "Sparse axillary hair",
    "Abnormality of carpal bone ossification",
    "Abnormality of the skin",
    "Short femoral neck",
    "Genu valgum",
    "Hypoplasia of the maxilla",
    "Generalized lipodystrophy",
    "Congenital generalized lipodystrophy",
    "Deeply set eye",
    "Short stature",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(lipodystrophy-intellectual disability-deafness syndrome[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(lipodystrophy-intellectual disability-deafness syndrome[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(lipodystrophy-intellectual disability-deafness syndrome[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(lipodystrophy-intellectual disability-deafness syndrome[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = (
    "lipodystrophy-intellectual disability-deafness syndrome OR lipodystrophy-intellectual"
)
GWAS_SEARCH_TERMS = [
    "lipodystrophy-intellectual disability-deafness syndrome",
    "lipodystrophy-intellectual",
]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AP1S2": 4.0,
        "ASAP1": 4.0,
        "BGN": 4.0,
        "BMP5": 4.0,
        "CANT1": 4.0,
        "CHSY1": 4.0,
        "CNOT3": 4.0,
        "COL12A1": 4.0,
        "COL2A1": 4.0,
        "CRTAP": 4.0,
        "CXXC5": 4.0,
        "CYP27B1": 4.0,
        "EBF2": 4.0,
        "ENPP1": 4.0,
        "EVC2": 4.0,
        "FAM20C": 4.0,
        "FGF18": 4.0,
        "FGF23": 4.0,
        "FGF9": 4.0,
        "FGFR3": 4.0,
        "FLNB": 4.0,
        "GHRHR": 4.0,
        "GLI2": 4.0,
        "HOXD13": 4.0,
        "IBSP": 4.0,
        "IFITM5": 4.0,
        "IHH": 4.0,
        "INPP4B": 4.0,
        "IRS1": 4.0,
        "KLF10": 4.0,
        "LMNA": 4.0,
        "LRP5": 4.0,
        "LRRK1": 4.0,
        "NOTCH2": 4.0,
        "NPR2": 4.0,
        "OSTM1": 4.0,
        "P2RX7": 4.0,
        "PHEX": 4.0,
        "PHOSPHO1": 4.0,
        "PLS3": 4.0,
        "POSTN": 4.0,
        "PPIB": 4.0,
        "ROR2": 4.0,
        "RUNX3": 4.0,
        "SCUBE2": 4.0,
        "SH3PXD2B": 4.0,
        "SIK3": 4.0,
        "SLC10A7": 4.0,
        "SLC30A5": 4.0,
        "SLC39A13": 4.0,
        "SLC39A14": 4.0,
        "SMPD3": 4.0,
        "SOST": 4.0,
        "SP6": 4.0,
        "TCIRG1": 4.0,
        "TENT5A": 4.0,
        "TNFRSF11A": 4.0,
        "TNFRSF11B": 4.0,
        "ZEB1": 4.0,
        "ZMPSTE24": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "lipodystrophy_intellectual_disability_deafness_syndrome-screening-v1",
    "pathway_keywords": [
        "autophagy",
        "bone",
        "cascade",
        "coagulation",
        "glucose",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "insulin",
        "iron",
    ],
    "mechanism_keywords": [
        "autophagy",
        "bone",
        "cascade",
        "coagulation",
        "glucose",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "insulin",
        "iron",
    ],
    "reference_drug_ids": [
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_lipodystrophy_intellectual_disability_deafness_syndrome_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
