"""neoplasm of cerebral hemisphere (NEOPLASM_OF_CEREBRAL_HEMISPHERE) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'neoplasm of cerebral hemisphere (NEOPLASM_OF_CEREBRAL_HEMISPHERE)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of neoplasm of cerebral hemisphere
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(neoplasm of cerebral hemisphere[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(neoplasm of cerebral hemisphere[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(neoplasm of cerebral hemisphere[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(neoplasm of cerebral hemisphere[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'neoplasm of cerebral hemisphere OR neoplasm'
GWAS_SEARCH_TERMS = ['neoplasm of cerebral hemisphere', 'neoplasm']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ADCY1": 4.0,
        "AKT1": 4.0,
        "ALB": 4.0,
        "AQP4": 4.0,
        "CA2": 4.0,
        "CACNA2D1": 4.0,
        "CAT": 4.0,
        "CD34": 4.0,
        "CGB5": 4.0,
        "CXCL12": 4.0,
        "CXCL13": 4.0,
        "CXCR4": 4.0,
        "EGF": 4.0,
        "EGFR": 4.0,
        "ENO2": 4.0,
        "EPHB2": 4.0,
        "EPO": 4.0,
        "ERBB2": 4.0,
        "FGFR1": 4.0,
        "FGFR3": 4.0,
        "GFAP": 4.0,
        "GH1": 4.0,
        "GLIPR1": 4.0,
        "GLUL": 4.0,
        "HADHA": 4.0,
        "IDH1": 4.0,
        "IDH2": 4.0,
        "IGF2": 4.0,
        "IL2": 4.0,
        "LGALS1": 4.0,
        "LRP12": 4.0,
        "LRRC32": 4.0,
        "MGP": 4.0,
        "MN1": 4.0,
        "MSH2": 4.0,
        "NF1": 4.0,
        "NOS1": 4.0,
        "NPY": 4.0,
        "PDCD4": 4.0,
        "PDGFRA": 4.0,
        "PECAM1": 4.0,
        "PGP": 4.0,
        "PGR": 4.0,
        "PIAS1": 4.0,
        "PIK3CA": 4.0,
        "PIK3CB": 4.0,
        "PIK3CD": 4.0,
        "PIK3CG": 4.0,
        "PRH2": 4.0,
        "SEMA3E": 4.0,
        "SMARCB1": 4.0,
        "SOX10": 4.0,
        "SOX2": 4.0,
        "SOX9": 4.0,
        "TMEM132A": 4.0,
        "TMEM37": 4.0,
        "VEGFA": 4.0,
        "VIM": 4.0,
        "YAP1": 4.0,
        "YY1AP1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
        "gabapentin",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "neoplasm_of_cerebral_hemisphere-screening-v1",
    "pathway_keywords": [
        "cardiac",
        "cascade",
        "cell",
        "channel",
        "chemokine",
        "coagulation",
        "conduction",
        "gaba",
        "glutamate",
        "hedgehog",
    ],
    "mechanism_keywords": [
        "cardiac",
        "cascade",
        "cell",
        "channel",
        "chemokine",
        "coagulation",
        "conduction",
        "gaba",
        "glutamate",
        "hedgehog",
    ],
    "reference_drug_ids": [
        "CHEMBL940",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_neoplasm_of_cerebral_hemisphere_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
