"""brachydactyly type E (BRACHYDACTYLY_TYPE_E) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'brachydactyly type E (BRACHYDACTYLY_TYPE_E)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of brachydactyly type E
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(brachydactyly type E[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(brachydactyly type E[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(brachydactyly type E[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(brachydactyly type E[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'brachydactyly type E OR brachydactyly'
GWAS_SEARCH_TERMS = ['brachydactyly type E', 'brachydactyly']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABCC9": 4.0,
        "ACVR1": 4.0,
        "ADAMTS12": 4.0,
        "ADAMTS17": 4.0,
        "BMPR1B": 4.0,
        "BRD2": 4.0,
        "COL2A1": 4.0,
        "CXXC5": 4.0,
        "EVX2": 4.0,
        "FBN1": 4.0,
        "FGR": 4.0,
        "FLNB": 4.0,
        "FMN1": 4.0,
        "FURIN": 4.0,
        "GAS1": 4.0,
        "GDF5": 4.0,
        "GHRH": 4.0,
        "GLI3": 4.0,
        "GPC1": 4.0,
        "HDAC4": 4.0,
        "HOXA13": 4.0,
        "HOXD11": 4.0,
        "HOXD12": 4.0,
        "HOXD13": 4.0,
        "IHH": 4.0,
        "LMBR1": 4.0,
        "LNPK": 4.0,
        "LRP4": 4.0,
        "MMP9": 4.0,
        "PDE3A": 4.0,
        "PLOD1": 4.0,
        "PORCN": 4.0,
        "PRKAR1A": 4.0,
        "PTH": 4.0,
        "PTH1R": 4.0,
        "PTHLH": 4.0,
        "ROR2": 4.0,
        "RUNX2": 4.0,
        "SFRP2": 4.0,
        "SHH": 4.0,
        "SLC10A7": 4.0,
        "SPRY4": 4.0,
        "TBX4": 4.0,
        "TMEM53": 4.0,
        "TRPS1": 4.0,
        "ZBTB16": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "bupivacaine",
        "clonidine",
        "epinephrine",
        "ketorolac",
        "ropivacaine",
        "ropivacaine hydrochloride",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "brachydactyly_type_e-screening-v1",
    "pathway_keywords": [
        "bone",
        "dopamine",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "iron",
        "metabolism",
        "remodeling",
        "serotonin",
        "signaling",
    ],
    "mechanism_keywords": [
        "bone",
        "dopamine",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "iron",
        "metabolism",
        "remodeling",
        "serotonin",
        "signaling",
    ],
    "reference_drug_ids": [
        "CHEMBL1077896",
        "CHEMBL134",
        "CHEMBL1077896",
        "CHEMBL679",
        "CHEMBL679",
        "CHEMBL1077896",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_brachydactyly_type_e_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
