"""autosomal erythropoietic protoporphyria (AUTOSOMAL_ERYTHROPOIETIC_PROTOPORPHYRIA) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'autosomal erythropoietic protoporphyria (AUTOSOMAL_ERYTHROPOIETIC_PROTOPORPHYRIA)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of autosomal erythropoietic protoporphyria
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(autosomal erythropoietic protoporphyria[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(autosomal erythropoietic protoporphyria[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(autosomal erythropoietic protoporphyria[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(autosomal erythropoietic protoporphyria[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'autosomal erythropoietic protoporphyria OR autosomal'
GWAS_SEARCH_TERMS = ['autosomal erythropoietic protoporphyria', 'autosomal']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABCB4": 4.0,
        "ABCC2": 4.0,
        "ABCG2": 4.0,
        "AHSP": 4.0,
        "ALOX12B": 4.0,
        "ANK1": 4.0,
        "APOC1": 4.0,
        "BLVRA": 4.0,
        "CCBE1": 4.0,
        "CDK5RAP3": 4.0,
        "CLEC10A": 4.0,
        "CP": 4.0,
        "CPOX": 4.0,
        "CYP27A1": 4.0,
        "CYP8B1": 4.0,
        "ELOVL1": 4.0,
        "EPB41": 4.0,
        "EPB42": 4.0,
        "EXOC6": 4.0,
        "FECH": 4.0,
        "FOXP3": 4.0,
        "GPBAR1": 4.0,
        "HEPH": 4.0,
        "HK1": 4.0,
        "IKZF1": 4.0,
        "ITGB2": 4.0,
        "JARID2": 4.0,
        "JUN": 4.0,
        "LDLR": 4.0,
        "LIG1": 4.0,
        "LRP6": 4.0,
        "MYB": 4.0,
        "NCOR1": 4.0,
        "NR1H4": 4.0,
        "ORM1": 4.0,
        "ORM2": 4.0,
        "PCTP": 4.0,
        "PKD1": 4.0,
        "PKHD1": 4.0,
        "PKLR": 4.0,
        "PRKAB1": 4.0,
        "PRKAG1": 4.0,
        "RELB": 4.0,
        "SCARB1": 4.0,
        "SCD": 4.0,
        "SCP2": 4.0,
        "SLC10A2": 4.0,
        "SLC20A1": 4.0,
        "SOAT2": 4.0,
        "SOCS1": 4.0,
        "SOCS3": 4.0,
        "SOX17": 4.0,
        "SPTA1": 4.0,
        "STARD10": 4.0,
        "TM6SF2": 4.0,
        "TMCC2": 4.0,
        "TMOD3": 4.0,
        "TMPRSS6": 4.0,
        "TPI1": 4.0,
        "TTC7A": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "autosomal_erythropoietic_protoporphyria-screening-v1",
    "pathway_keywords": [
        "adhesion",
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "hormone",
        "integrin",
        "lipid",
        "metabolism",
        "pathway",
    ],
    "mechanism_keywords": [
        "adhesion",
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "hormone",
        "integrin",
        "lipid",
        "metabolism",
        "pathway",
    ],
    "reference_drug_ids": [
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_autosomal_erythropoietic_protoporphyria_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
