"""mitochondrial dna depletion syndrome 16B (neuroophthalmic type) (MITOCHONDRIAL_DNA_DEPLETION_SYNDROME_16B_NEUROOPHTHALMIC_TYPE) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'mitochondrial dna depletion syndrome 16B (neuroophthalmic type) (MITOCHONDRIAL_DNA_DEPLETION_SYNDROME_16B_NEUROOPHTHALMIC_TYPE)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Depression",
    "Cerebellar atrophy",
    "Optic atrophy",
    "Visual loss",
    "Premature ovarian insufficiency",
    "Peripheral axonal neuropathy",
    "Cerebral cortical atrophy",
    "Amenorrhea",
    "Ataxia",
    "Open angle glaucoma",
    "Gait disturbance",
    "Autosomal recessive inheritance",
    "Anxiety",
    "Headache",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(mitochondrial dna depletion syndrome 16B (neuroophthalmic type)[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(mitochondrial dna depletion syndrome 16B (neuroophthalmic type)[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(mitochondrial dna depletion syndrome 16B (neuroophthalmic type)[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(mitochondrial dna depletion syndrome 16B (neuroophthalmic type)[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'mitochondrial dna depletion syndrome 16B (neuroophthalmic type) OR mitochondrial'
GWAS_SEARCH_TERMS = ['mitochondrial dna depletion syndrome 16B (neuroophthalmic type)', 'mitochondrial']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AGTPBP1": 4.0,
        "ANK3": 4.0,
        "ATXN7": 4.0,
        "BORCS7": 4.0,
        "BORCS7-ASMT": 4.0,
        "CACNA1A": 4.0,
        "CACNA1G": 4.0,
        "CERS1": 4.0,
        "CHP1": 4.0,
        "CLN8": 4.0,
        "DOCK3": 4.0,
        "EDARADD": 4.0,
        "GDF1": 4.0,
        "GRID2": 4.0,
        "KCNJ6": 4.0,
        "KDM3B": 4.0,
        "MILR1": 4.0,
        "MYH10": 4.0,
        "PDE6B": 4.0,
        "PLA2G6": 4.0,
        "PMP22": 4.0,
        "POLG2": 4.0,
        "PSAP": 4.0,
        "RAB18": 4.0,
        "RORA": 4.0,
        "SPTBN4": 4.0,
        "STUB1": 4.0,
        "SUN1": 4.0,
        "TMEM176B": 4.0,
        "TPP1": 4.0,
        "TRIM2": 4.0,
        "TUBB4A": 4.0,
        "UBE4B": 4.0,
        "UNC5C": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "melatonin",
        "rosiglitazone",
        "rosuvastatin",
    ],
    "low_risk": [
        "metformin",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "mitochondrial_dna_depletion_syndrome_16b_neuroophthalmic_type-screening-v1",
    "pathway_keywords": [
        "angiotensin",
        "cardiac",
        "channel",
        "conduction",
        "pathway",
        "renin",
        "system",
        "th17",
    ],
    "mechanism_keywords": [
        "angiotensin",
        "cardiac",
        "channel",
        "conduction",
        "pathway",
        "renin",
        "system",
        "th17",
    ],
    "reference_drug_ids": [
        "CHEMBL1431",
        "CHEMBL45",
        "CHEMBL1431",
        "CHEMBL1431",
        "CHEMBL1431",
        "CHEMBL1431",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_mitochondrial_dna_depletion_syndrome_16b_neuroophthalmic_type_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
