"""hyperuricemic nephropathy, familial juvenile type 4 (HYPERURICEMIC_NEPHROPATHY_FAMILIAL_JUVENILE_TYPE_4) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "hyperuricemic nephropathy, familial juvenile type 4 (HYPERURICEMIC_NEPHROPATHY_FAMILIAL_JUVENILE_TYPE_4)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Abnormal circulating renin concentration",
    "Impaired renal concentrating ability",
    "Autosomal dominant inheritance",
    "Hyperechogenic kidneys",
    "Proteinuria",
    "Progressive",
    "Chronic constipation",
    "Recurrent infections",
    "Infantile onset",
    "Retrognathia",
    "Elevated circulating parathyroid hormone level",
    "Decreased urinary uromodulin level",
    "Renal sodium wasting",
    "Anemia",
    "Hematuria",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(hyperuricemic nephropathy, familial juvenile type 4[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(hyperuricemic nephropathy, familial juvenile type 4[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(hyperuricemic nephropathy, familial juvenile type 4[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(hyperuricemic nephropathy, familial juvenile type 4[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "hyperuricemic nephropathy, familial juvenile type 4 OR hyperuricemic"
GWAS_SEARCH_TERMS = ["hyperuricemic nephropathy, familial juvenile type 4", "hyperuricemic"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABCG2": 4.0,
        "ABCG5": 4.0,
        "ABCG8": 4.0,
        "ACE": 4.0,
        "AGT": 4.0,
        "AGTR1": 4.0,
        "ANK1": 4.0,
        "APRT": 4.0,
        "AQP11": 4.0,
        "AQP2": 4.0,
        "ARHGDIA": 4.0,
        "BCL2": 4.0,
        "BSND": 4.0,
        "C1GALT1": 4.0,
        "CD151": 4.0,
        "CD2AP": 4.0,
        "CLCN5": 4.0,
        "CLCNKA": 4.0,
        "CLCNKB": 4.0,
        "CLDN7": 4.0,
        "COL4A1": 4.0,
        "COL4A3": 4.0,
        "COL4A4": 4.0,
        "COL4A5": 4.0,
        "CYBB": 4.0,
        "CYS1": 4.0,
        "GLIS2": 4.0,
        "GNE": 4.0,
        "HMOX1": 4.0,
        "HNF1A": 4.0,
        "HTR3A": 4.0,
        "KCNJ1": 4.0,
        "KCTD1": 4.0,
        "LEPR": 4.0,
        "LGMN": 4.0,
        "LIN7C": 4.0,
        "MAGI2": 4.0,
        "MOCOS": 4.0,
        "MYO1E": 4.0,
        "NPHP3": 4.0,
        "NPHP3-ACAD11": 4.0,
        "NPHS2": 4.0,
        "NR3C2": 4.0,
        "PIK3C2A": 4.0,
        "PKD1": 4.0,
        "PTGS2": 4.0,
        "REN": 4.0,
        "RRM2B": 4.0,
        "RUVBL1": 4.0,
        "SCTR": 4.0,
        "SEC61A1": 4.0,
        "SLC12A1": 4.0,
        "SLC2A9": 4.0,
        "SLC4A1": 4.0,
        "SLC4A4": 4.0,
        "SLC4A5": 4.0,
        "TFAP2B": 4.0,
        "UMOD": 4.0,
        "WWTR1": 4.0,
        "XDH": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "bumetanide",
        "buparlisib",
        "carvedilol",
        "chiglitazar",
        "cipepofol",
        "cytarabine",
        "cytisinicline",
        "dabrafenib",
        "daclizumab",
        "empagliflozin",
        "encenicline",
        "esketamine",
        "felzartamab",
        "filgotinib",
        "fimasartan",
        "fruquintinib",
        "furosemide",
        "lemborexant",
        "mobocertinib",
        "peficitinib",
        "plerixafor",
        "pradigastat",
        "ribociclib",
        "rituximab",
        "roxadustat",
        "seltorexant",
        "setrusumab",
        "sirolimus",
        "sorafenib",
        "tacrolimus anhydrous",
        "tavapadon",
        "theophylline",
        "varespladib methyl",
        "voxelotor",
    ],
    "low_risk": [
        "amlodipine",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "hyperuricemic_nephropathy_familial_juvenile_type_4-screening-v1",
    "pathway_keywords": [
        "angiotensin",
        "apoptosis",
        "cascade",
        "complement",
        "dopamine",
        "glucose",
        "hedgehog",
        "hormone",
        "insulin",
        "metabolism",
    ],
    "mechanism_keywords": [
        "angiotensin",
        "apoptosis",
        "cascade",
        "complement",
        "dopamine",
        "glucose",
        "hedgehog",
        "hormone",
        "insulin",
        "metabolism",
    ],
    "reference_drug_ids": [
        "CHEMBL2017974",
        "CHEMBL269732",
        "CHEMBL35",
        "CHEMBL3545367",
        "CHEMBL4297744",
        "CHEMBL4297744",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_hyperuricemic_nephropathy_familial_juvenile_type_4_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
