"""precocious puberty, central, 2 (PRECOCIOUS_PUBERTY_CENTRAL_2) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'precocious puberty, central, 2 (PRECOCIOUS_PUBERTY_CENTRAL_2)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Premature thelarche",
    "Accelerated skeletal maturation",
    "Premature pubarche",
    "Autosomal dominant inheritance with maternal imprinting",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(precocious puberty, central, 2[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(precocious puberty, central, 2[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(precocious puberty, central, 2[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(precocious puberty, central, 2[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'precocious puberty, central, 2 OR precocious'
GWAS_SEARCH_TERMS = ['precocious puberty, central, 2', 'precocious']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AFP": 4.0,
        "ALK": 4.0,
        "AMH": 4.0,
        "AMHR2": 4.0,
        "AR": 4.0,
        "BRDT": 4.0,
        "C14orf93": 4.0,
        "CDKN2D": 4.0,
        "CHST8": 4.0,
        "CYP7B1": 4.0,
        "DHH": 4.0,
        "DRD2": 4.0,
        "ESR1": 4.0,
        "ESR2": 4.0,
        "FAAP100": 4.0,
        "FHL5": 4.0,
        "FSHR": 4.0,
        "GADD45G": 4.0,
        "GDF9": 4.0,
        "GNRH1": 4.0,
        "GNRHR": 4.0,
        "IGSF1": 4.0,
        "INSM1": 4.0,
        "KISS1": 4.0,
        "KIT": 4.0,
        "LHCGR": 4.0,
        "MED1": 4.0,
        "MKRN3": 4.0,
        "MRC1": 4.0,
        "NPFFR1": 4.0,
        "NR0B2": 4.0,
        "NR5A1": 4.0,
        "NSMF": 4.0,
        "PCYT1B": 4.0,
        "PIK3CB": 4.0,
        "PLK4": 4.0,
        "POLR3H": 4.0,
        "PRL": 4.0,
        "PROP1": 4.0,
        "PSEN1": 4.0,
        "PTDSS2": 4.0,
        "RSPO1": 4.0,
        "SIX5": 4.0,
        "SLC14A1": 4.0,
        "SRY": 4.0,
        "SST": 4.0,
        "SYTL4": 4.0,
        "TAF4B": 4.0,
        "TGFBR3L": 4.0,
        "THRB": 4.0,
        "TPST2": 4.0,
        "TRHR": 4.0,
        "TSHR": 4.0,
        "UBE2D2": 4.0,
        "UBE2D3": 4.0,
        "USP26": 4.0,
        "UTP14A": 4.0,
        "UTP14C": 4.0,
        "WT1": 4.0,
        "ZGLP1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "precocious_puberty_central_2-screening-v1",
    "pathway_keywords": [
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "dopamine",
        "gaba",
        "glucose",
        "glutamate",
        "hedgehog",
        "hormone",
    ],
    "mechanism_keywords": [
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "dopamine",
        "gaba",
        "glucose",
        "glutamate",
        "hedgehog",
        "hormone",
    ],
    "reference_drug_ids": [
        "CHEMBL1200554",
        "CHEMBL1200775",
        "CHEMBL1201199",
        "CHEMBL1200775",
        "CHEMBL1201334",
        "CHEMBL1201199",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_precocious_puberty_central_2_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
