"""Zechi-Ceide syndrome (ZECHI_CEIDE_SYNDROME) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'Zechi-Ceide syndrome (ZECHI_CEIDE_SYNDROME)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of Zechi-Ceide syndrome
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(Zechi-Ceide syndrome[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(Zechi-Ceide syndrome[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(Zechi-Ceide syndrome[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(Zechi-Ceide syndrome[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'Zechi-Ceide syndrome OR Zechi-Ceide'
GWAS_SEARCH_TERMS = ['Zechi-Ceide syndrome', 'Zechi-Ceide']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ALX1": 4.0,
        "ASPH": 4.0,
        "BMP7": 4.0,
        "C3orf38": 4.0,
        "CPLANE1": 4.0,
        "CYP51A1": 4.0,
        "EYA1": 4.0,
        "FGFR1": 4.0,
        "GAS1": 4.0,
        "GATA3": 4.0,
        "GDF5": 4.0,
        "GLI3": 4.0,
        "GPC6": 4.0,
        "HOXD12": 4.0,
        "LRP6": 4.0,
        "OSR2": 4.0,
        "PITX1": 4.0,
        "PRICKLE1": 4.0,
        "ROR2": 4.0,
        "RSPO2": 4.0,
        "SATB2": 4.0,
        "SFN": 4.0,
        "TBX10": 4.0,
        "TMEM107": 4.0,
        "WIZ": 4.0,
        "WNT5A": 4.0,
        "ZEB1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "zechi_ceide_syndrome-screening-v1",
    "pathway_keywords": [
        "(th2)",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "iron",
        "mapk",
        "metabolism",
        "pathway",
        "signaling",
        "xenobiotic",
    ],
    "mechanism_keywords": [
        "(th2)",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "iron",
        "mapk",
        "metabolism",
        "pathway",
        "signaling",
        "xenobiotic",
    ],
    "reference_drug_ids": [
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_zechi_ceide_syndrome_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
