"""spinocerebellar ataxia type 10 (SPINOCEREBELLAR_ATAXIA_TYPE_10) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'spinocerebellar ataxia type 10 (SPINOCEREBELLAR_ATAXIA_TYPE_10)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Dysarthria",
    "Urinary incontinence",
    "Typified by incomplete penetrance",
    "Depression",
    "Limb fasciculations",
    "Abnormal pyramidal tract morphology",
    "Seizure",
    "Autosomal dominant inheritance",
    "Abnormal pyramidal sign",
    "Impaired smooth pursuit",
    "Dysdiadochokinesis",
    "Polyneuropathy",
    "Urinary urgency",
    "Dysmetria",
    "Genetic anticipation",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(spinocerebellar ataxia type 10[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(spinocerebellar ataxia type 10[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(spinocerebellar ataxia type 10[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(spinocerebellar ataxia type 10[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'spinocerebellar ataxia type 10 OR spinocerebellar'
GWAS_SEARCH_TERMS = ['spinocerebellar ataxia type 10', 'spinocerebellar']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ANK3": 4.0,
        "ANKFY1": 4.0,
        "ASPA": 4.0,
        "ATCAY": 4.0,
        "ATP1A3": 4.0,
        "ATP2B1": 4.0,
        "ATP2B2": 4.0,
        "ATXN10": 4.0,
        "CA8": 4.0,
        "CACNA1A": 4.0,
        "CACNA1G": 4.0,
        "CACNA2D2": 4.0,
        "CACNB4": 4.0,
        "CANX": 4.0,
        "CCR10": 4.0,
        "CDH23": 4.0,
        "CERS1": 4.0,
        "CLP1": 4.0,
        "CNTNAP1": 4.0,
        "COQ8A": 4.0,
        "CSTB": 4.0,
        "DCC": 4.0,
        "DNM1": 4.0,
        "EN1": 4.0,
        "GABRG2": 4.0,
        "GDF1": 4.0,
        "GLRA1": 4.0,
        "GRID2": 4.0,
        "HCN2": 4.0,
        "HDAC4": 4.0,
        "HPRT1": 4.0,
        "HTT": 4.0,
        "KCNA1": 4.0,
        "KCNJ6": 4.0,
        "KCNMA1": 4.0,
        "LMX1A": 4.0,
        "MBP": 4.0,
        "MECP2": 4.0,
        "MORC2": 4.0,
        "NEUROD2": 4.0,
        "NPC1": 4.0,
        "PMP22": 4.0,
        "PSAP": 4.0,
        "QKI": 4.0,
        "RELN": 4.0,
        "RORA": 4.0,
        "SCN1A": 4.0,
        "SCN8A": 4.0,
        "SLC2A1": 4.0,
        "SPTBN2": 4.0,
        "SPTBN4": 4.0,
        "SULT4A1": 4.0,
        "SUN1": 4.0,
        "TMEM176B": 4.0,
        "TPP1": 4.0,
        "TRIM2": 4.0,
        "TUBB4A": 4.0,
        "UBE3A": 4.0,
        "UNC5C": 4.0,
        "WWOX": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "capecitabine",
        "dasatinib",
        "dexmedetomidine",
        "galantamine",
        "galantamine hydrobromide",
        "lapatinib",
        "pentoxifylline",
        "roflumilast",
        "sacituzumab govitecan",
        "trastuzumab",
        "vorinostat",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "spinocerebellar_ataxia_type_10-screening-v1",
    "pathway_keywords": [
        "cardiac",
        "cascade",
        "channel",
        "chemokine",
        "complement",
        "conduction",
        "glucose",
        "insulin",
        "interferon",
        "metabolism",
    ],
    "mechanism_keywords": [
        "cardiac",
        "cascade",
        "channel",
        "chemokine",
        "complement",
        "conduction",
        "glucose",
        "insulin",
        "interferon",
        "metabolism",
    ],
    "reference_drug_ids": [
        "CHEMBL628",
        "CHEMBL628",
        "CHEMBL1421",
        "CHEMBL628",
        "CHEMBL1421",
        "CHEMBL628",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_spinocerebellar_ataxia_type_10_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
