"""elephantiasis (ELEPHANTIASIS) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "elephantiasis (ELEPHANTIASIS)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of elephantiasis
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(elephantiasis[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(elephantiasis[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(elephantiasis[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(elephantiasis[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "elephantiasis OR elephantiasis"
GWAS_SEARCH_TERMS = ["elephantiasis", "elephantiasis"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABO": 4.0,
        "ACHE": 4.0,
        "CD27": 4.0,
        "CD274": 4.0,
        "CD4": 4.0,
        "CD40LG": 4.0,
        "CD8A": 4.0,
        "EDN1": 4.0,
        "ELN": 4.0,
        "FGFR3": 4.0,
        "IFNG": 4.0,
        "IL10": 4.0,
        "IL10RA": 4.0,
        "IL10RB": 4.0,
        "IL2": 4.0,
        "IL26": 4.0,
        "IL4": 4.0,
        "IL6": 4.0,
        "LBP": 4.0,
        "PDCD1": 4.0,
        "PDCD1LG2": 4.0,
        "PDPN": 4.0,
        "RNASE3": 4.0,
        "RPL17": 4.0,
        "RPL17-C18orf32": 4.0,
        "SELL": 4.0,
        "SERPINA3": 4.0,
        "SNCA": 4.0,
        "SPATA2": 4.0,
        "TF": 4.0,
        "TNFRSF1B": 4.0,
        "TNFRSF25": 4.0,
        "VEGFA": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "acebilustat",
        "bevacizumab",
        "pazopanib",
        "propranolol",
        "tacrolimus anhydrous",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "elephantiasis-screening-v1",
    "pathway_keywords": [
        "(th2)",
        "adhesion",
        "cascade",
        "cell",
        "checkpoint",
        "coagulation",
        "immune",
        "inflammasome",
        "integrin",
        "mapk",
    ],
    "mechanism_keywords": [
        "(th2)",
        "adhesion",
        "cascade",
        "cell",
        "checkpoint",
        "coagulation",
        "immune",
        "inflammasome",
        "integrin",
        "mapk",
    ],
    "reference_drug_ids": [
        "CHEMBL269732",
        "CHEMBL27",
        "CHEMBL477772",
        "CHEMBL477772",
        "CHEMBL269732",
        "CHEMBL477772",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_elephantiasis_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
