"""Lessel-Kubisch syndrome (LESSEL_KUBISCH_SYNDROME) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "Lessel-Kubisch syndrome (LESSEL_KUBISCH_SYNDROME)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Renal insufficiency",
    "Premature graying of hair",
    "Hypertension",
    "Narrow mouth",
    "Hypogonadism",
    "Autosomal recessive inheritance",
    "Narrow nasal bridge",
    "Renal hypoplasia",
    "Sparse pubic hair",
    "Short stature",
    "Abnormally high-pitched voice",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(Lessel-Kubisch syndrome[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(Lessel-Kubisch syndrome[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(Lessel-Kubisch syndrome[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(Lessel-Kubisch syndrome[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "Lessel-Kubisch syndrome OR Lessel-Kubisch"
GWAS_SEARCH_TERMS = ["Lessel-Kubisch syndrome", "Lessel-Kubisch"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACE": 4.0,
        "AGT": 4.0,
        "APRT": 4.0,
        "AQP2": 4.0,
        "BCL2": 4.0,
        "BMP4": 4.0,
        "CD151": 4.0,
        "CYP4A11": 4.0,
        "CYP4A22": 4.0,
        "CYP4F11": 4.0,
        "CYP4F12": 4.0,
        "DRD5": 4.0,
        "EDA": 4.0,
        "GATA5": 4.0,
        "GDNF": 4.0,
        "GLIS2": 4.0,
        "KISS1R": 4.0,
        "KITLG": 4.0,
        "LIFR": 4.0,
        "LIN7C": 4.0,
        "MAP3K15": 4.0,
        "MDM2": 4.0,
        "MITF": 4.0,
        "MYO1E": 4.0,
        "NAA10": 4.0,
        "PAX2": 4.0,
        "PDE1A": 4.0,
        "PRKG1": 4.0,
        "PTGS2": 4.0,
        "REN": 4.0,
        "RET": 4.0,
        "SLC6A18": 4.0,
        "TAL1": 4.0,
        "TFCP2L1": 4.0,
        "TNS1": 4.0,
        "UMOD": 4.0,
        "WT1": 4.0,
        "WWTR1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "lessel_kubisch_syndrome-screening-v1",
    "pathway_keywords": [
        "angiotensin",
        "apoptosis",
        "cell",
        "dopamine",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "hormone",
        "iron",
        "mast",
    ],
    "mechanism_keywords": [
        "angiotensin",
        "apoptosis",
        "cell",
        "dopamine",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "hormone",
        "iron",
        "mast",
    ],
    "reference_drug_ids": [
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_lessel_kubisch_syndrome_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
