"""myopathy due to calsequestrin and SERCA1 protein overload (MYOPATHY_DUE_TO_CALSEQUESTRIN_AND_SERCA1_PROTEIN_OVERLOAD) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'myopathy due to calsequestrin and SERCA1 protein overload (MYOPATHY_DUE_TO_CALSEQUESTRIN_AND_SERCA1_PROTEIN_OVERLOAD)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Muscle fiber calsequestrin 1-containing inclusion bodies",
    "Easy fatigability",
    "Proximal muscle weakness",
    "Autosomal dominant inheritance",
    "Muscle weakness",
    "Muscle spasm",
    "Myalgia",
    "Elevated circulating creatine kinase activity",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(myopathy due to calsequestrin and SERCA1 protein overload[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(myopathy due to calsequestrin and SERCA1 protein overload[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(myopathy due to calsequestrin and SERCA1 protein overload[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(myopathy due to calsequestrin and SERCA1 protein overload[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'myopathy due to calsequestrin and SERCA1 protein overload OR myopathy'
GWAS_SEARCH_TERMS = ['myopathy due to calsequestrin and SERCA1 protein overload', 'myopathy']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACTMAP": 4.0,
        "ANK1": 4.0,
        "ANO5": 4.0,
        "APOBEC2": 4.0,
        "APP": 4.0,
        "ASNSD1": 4.0,
        "CALCR": 4.0,
        "CAMKMT": 4.0,
        "CAPN3": 4.0,
        "CASQ1": 4.0,
        "CAV3": 4.0,
        "COL13A1": 4.0,
        "COL4A1": 4.0,
        "COL6A1": 4.0,
        "COL6A3": 4.0,
        "DES": 4.0,
        "DMD": 4.0,
        "DMPK": 4.0,
        "DNAJB4": 4.0,
        "DNM2": 4.0,
        "DYSF": 4.0,
        "FFAR2": 4.0,
        "FKRP": 4.0,
        "FLNC": 4.0,
        "IDUA": 4.0,
        "ITGA7": 4.0,
        "KLHL31": 4.0,
        "LAMA2": 4.0,
        "LARGE1": 4.0,
        "LDB3": 4.0,
        "LIMCH1": 4.0,
        "LMOD3": 4.0,
        "LUM": 4.0,
        "MCFD2": 4.0,
        "MDN1": 4.0,
        "MSTN": 4.0,
        "MYBPC2": 4.0,
        "MYF5": 4.0,
        "MYH4": 4.0,
        "MYPN": 4.0,
        "NEB": 4.0,
        "NFATC3": 4.0,
        "NOC4L": 4.0,
        "OBSCN": 4.0,
        "OCIAD2": 4.0,
        "PHKB": 4.0,
        "PLEC": 4.0,
        "PRL": 4.0,
        "RYR1": 4.0,
        "SCN4A": 4.0,
        "SCO2": 4.0,
        "SELENON": 4.0,
        "SGCA": 4.0,
        "SGCG": 4.0,
        "SRPK3": 4.0,
        "TCAP": 4.0,
        "TNNT1": 4.0,
        "TRIM24": 4.0,
        "TRIM32": 4.0,
        "USP18": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "acetaminophen",
        "dexamethasone",
        "midazolam",
        "midazolam hydrochloride",
        "roflumilast",
        "rolipram",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "myopathy_due_to_calsequestrin_and_serca1_protein_overload-screening-v1",
    "pathway_keywords": [
        "adhesion",
        "cell",
        "hormone",
        "integrin",
        "lipid",
        "metabolism",
        "pathway",
        "remodeling",
        "signaling",
        "thyroid",
    ],
    "mechanism_keywords": [
        "adhesion",
        "cell",
        "hormone",
        "integrin",
        "lipid",
        "metabolism",
        "pathway",
        "remodeling",
        "signaling",
        "thyroid",
    ],
    "reference_drug_ids": [
        "CHEMBL112",
        "CHEMBL2108791",
        "CHEMBL63",
        "CHEMBL63",
        "CHEMBL1200420",
        "CHEMBL1200420",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_myopathy_due_to_calsequestrin_and_serca1_protein_overload_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
