"""Patent ductus arteriosus (PATENT_DUCTUS_ARTERIOSUS) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "Patent ductus arteriosus (PATENT_DUCTUS_ARTERIOSUS)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of Patent ductus arteriosus
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(Patent ductus arteriosus[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(Patent ductus arteriosus[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(Patent ductus arteriosus[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(Patent ductus arteriosus[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "Patent ductus arteriosus OR Patent"
GWAS_SEARCH_TERMS = ["Patent ductus arteriosus", "Patent"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACAN": 4.0,
        "ACKR3": 4.0,
        "ADAM17": 4.0,
        "ADAM19": 4.0,
        "ADAMTS19": 4.0,
        "ADAMTS6": 4.0,
        "ADAMTSL2": 4.0,
        "ARID4A": 4.0,
        "ARSB": 4.0,
        "B3GAT3": 4.0,
        "BMP5": 4.0,
        "BMPR1B": 4.0,
        "BMPR2": 4.0,
        "CHSY1": 4.0,
        "CHSY3": 4.0,
        "CITED2": 4.0,
        "COL11A1": 4.0,
        "COL1A1": 4.0,
        "COL2A1": 4.0,
        "CPLANE2": 4.0,
        "CXCR4": 4.0,
        "DDX19A": 4.0,
        "DDX46": 4.0,
        "DHX16": 4.0,
        "EVX2": 4.0,
        "FBN1": 4.0,
        "FMN1": 4.0,
        "GATA4": 4.0,
        "GDF5": 4.0,
        "GJA1": 4.0,
        "GLI3": 4.0,
        "HBEGF": 4.0,
        "HECTD1": 4.0,
        "HEY2": 4.0,
        "HOXA11": 4.0,
        "HOXA13": 4.0,
        "HOXD11": 4.0,
        "HOXD12": 4.0,
        "HOXD13": 4.0,
        "IHH": 4.0,
        "KIF12": 4.0,
        "LMBR1": 4.0,
        "LNPK": 4.0,
        "LRRK1": 4.0,
        "LTBP1": 4.0,
        "MATR3": 4.0,
        "MTREX": 4.0,
        "NKX2-5": 4.0,
        "PITX1": 4.0,
        "PLXND1": 4.0,
        "PMM2": 4.0,
        "PROM1": 4.0,
        "ROR2": 4.0,
        "RSPO2": 4.0,
        "SALL1": 4.0,
        "SALL4": 4.0,
        "SEMA3C": 4.0,
        "SFRP2": 4.0,
        "SKIC2": 4.0,
        "SMARCA4": 4.0,
        "TAB1": 4.0,
        "TBX1": 4.0,
        "TBX4": 4.0,
        "TFAP2B": 4.0,
        "THSD4": 4.0,
        "XYLT1": 4.0,
        "ZBTB16": 4.0,
        "ZFPM2": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "patent_ductus_arteriosus-screening-v1",
    "pathway_keywords": [
        "chemokine",
        "dopamine",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "iron",
        "remodeling",
        "repair",
        "serotonin",
        "signaling",
    ],
    "mechanism_keywords": [
        "chemokine",
        "dopamine",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "iron",
        "remodeling",
        "repair",
        "serotonin",
        "signaling",
    ],
    "reference_drug_ids": [
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_patent_ductus_arteriosus_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
