"""GM2 gangliosidosis (GM2_GANGLIOSIDOSIS) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "GM2 gangliosidosis (GM2_GANGLIOSIDOSIS)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of GM2 gangliosidosis
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(GM2 gangliosidosis[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(GM2 gangliosidosis[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(GM2 gangliosidosis[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(GM2 gangliosidosis[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "GM2 gangliosidosis OR GM2"
GWAS_SEARCH_TERMS = ["GM2 gangliosidosis", "GM2"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "BBS9": 4.0,
        "CCR2": 4.0,
        "CHIT1": 4.0,
        "CSF2": 4.0,
        "DCC": 4.0,
        "DPP4": 4.0,
        "EIF2AK3": 4.0,
        "ETFA": 4.0,
        "F9": 4.0,
        "FAP": 4.0,
        "FYN": 4.0,
        "GAD1": 4.0,
        "GALC": 4.0,
        "GBA1": 4.0,
        "GFAP": 4.0,
        "GLA": 4.0,
        "GLB1": 4.0,
        "GM2A": 4.0,
        "HEXA": 4.0,
        "HEXB": 4.0,
        "HEXD": 4.0,
        "HHEX": 4.0,
        "HPX": 4.0,
        "IGBP1": 4.0,
        "INS": 4.0,
        "KIF1A": 4.0,
        "LAMC2": 4.0,
        "MAPT": 4.0,
        "MBP": 4.0,
        "MS4A1": 4.0,
        "MTOR": 4.0,
        "NEFL": 4.0,
        "NEU1": 4.0,
        "NEU3": 4.0,
        "NEU4": 4.0,
        "NPC1": 4.0,
        "NPC2": 4.0,
        "OGA": 4.0,
        "PANK1": 4.0,
        "PIK3CA": 4.0,
        "PIK3CB": 4.0,
        "PIK3CD": 4.0,
        "PPT1": 4.0,
        "PROS1": 4.0,
        "PSAP": 4.0,
        "PTEN": 4.0,
        "RIPK3": 4.0,
        "RNASET2": 4.0,
        "SCP2": 4.0,
        "SMN1": 4.0,
        "SMPD1": 4.0,
        "SNCB": 4.0,
        "SPANXB1": 4.0,
        "SPG11": 4.0,
        "SULF1": 4.0,
        "SULF2": 4.0,
        "SYN1": 4.0,
        "TFEB": 4.0,
        "TMEFF1": 4.0,
        "UGCG": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "miglustat",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "gm2_gangliosidosis-screening-v1",
    "pathway_keywords": [
        "apoptosis",
        "cascade",
        "cell",
        "chemokine",
        "coagulation",
        "complement",
        "gaba",
        "glucose",
        "glutamate",
        "insulin",
    ],
    "mechanism_keywords": [
        "apoptosis",
        "cascade",
        "cell",
        "chemokine",
        "coagulation",
        "complement",
        "gaba",
        "glucose",
        "glutamate",
        "insulin",
    ],
    "reference_drug_ids": [
        "CHEMBL1029",
        "CHEMBL3039538",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_gm2_gangliosidosis_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
