"""subcorneal pustular dermatosis (SUBCORNEAL_PUSTULAR_DERMATOSIS) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "subcorneal pustular dermatosis (SUBCORNEAL_PUSTULAR_DERMATOSIS)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of subcorneal pustular dermatosis
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(subcorneal pustular dermatosis[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(subcorneal pustular dermatosis[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(subcorneal pustular dermatosis[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(subcorneal pustular dermatosis[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "subcorneal pustular dermatosis OR subcorneal"
GWAS_SEARCH_TERMS = ["subcorneal pustular dermatosis", "subcorneal"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ASH1L": 4.0,
        "BCL2L11": 4.0,
        "BTLA": 4.0,
        "BTN2A1": 4.0,
        "BTN2A2": 4.0,
        "C1QTNF3": 4.0,
        "C1QTNF3-AMACR": 4.0,
        "C1QTNF6": 4.0,
        "C9orf72": 4.0,
        "CARD11": 4.0,
        "CCNT1": 4.0,
        "CD19": 4.0,
        "CD276": 4.0,
        "CD28": 4.0,
        "CD38": 4.0,
        "CLEC4A": 4.0,
        "CLEC4C": 4.0,
        "CYSLTR2": 4.0,
        "DUSP22": 4.0,
        "FAS": 4.0,
        "FASLG": 4.0,
        "FCER1G": 4.0,
        "FCGR2A": 4.0,
        "FCGR2B": 4.0,
        "FCGR2C": 4.0,
        "FOXP3": 4.0,
        "GATA1": 4.0,
        "ICOS": 4.0,
        "IFIH1": 4.0,
        "IFNG": 4.0,
        "IFNGR1": 4.0,
        "IKZF3": 4.0,
        "IL12RB2": 4.0,
        "IL13": 4.0,
        "IL17A": 4.0,
        "IL17F": 4.0,
        "IL21R": 4.0,
        "IL4": 4.0,
        "IL6ST": 4.0,
        "LTA": 4.0,
        "LTC4S": 4.0,
        "LYN": 4.0,
        "MAP4K3": 4.0,
        "NFATC1": 4.0,
        "POLB": 4.0,
        "PPARG": 4.0,
        "PSTPIP2": 4.0,
        "RNF128": 4.0,
        "RO60": 4.0,
        "STAT6": 4.0,
        "TANK": 4.0,
        "TBC1D10C": 4.0,
        "TIMD4": 4.0,
        "TLR7": 4.0,
        "TNF": 4.0,
        "TNFSF10": 4.0,
        "TNFSF13": 4.0,
        "TREX1": 4.0,
        "TRIM21": 4.0,
        "TYK2": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "adapalene",
        "betamethasone dipropionate",
        "betamethasone valerate",
        "cholecalciferol",
        "clobetasol propionate",
        "desonide",
        "desoximetasone",
        "diflorasone diacetate",
        "doxycycline",
        "dupilumab",
        "fluocinolone acetonide",
        "fluocinonide",
        "fluticasone propionate",
        "halcinonide",
        "halobetasol propionate",
        "hydrocortisone",
        "hydrocortisone acetate",
        "hydroxyzine pamoate",
        "levocetirizine dihydrochloride",
        "lidocaine",
        "melatonin",
        "midazolam",
        "mometasone furoate",
        "prednicarbate",
        "prilocaine",
        "sildenafil",
        "tacrolimus anhydrous",
        "tazarotene",
        "tetracaine",
        "triamcinolone",
        "triamcinolone acetonide",
    ],
    "low_risk": [
        "diltiazem",
        "diltiazem hydrochloride",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "subcorneal_pustular_dermatosis-screening-v1",
    "pathway_keywords": [
        "(th2)",
        "apoptosis",
        "cascade",
        "cell",
        "coagulation",
        "complement",
        "inflammasome",
        "lipid",
        "mast",
        "metabolism",
    ],
    "mechanism_keywords": [
        "(th2)",
        "apoptosis",
        "cascade",
        "cell",
        "coagulation",
        "complement",
        "inflammasome",
        "lipid",
        "mast",
        "metabolism",
    ],
    "reference_drug_ids": [
        "CHEMBL1265",
        "CHEMBL79",
        "CHEMBL989",
        "CHEMBL698",
        "CHEMBL79",
        "CHEMBL655",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_subcorneal_pustular_dermatosis_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
