"""dystocia (DYSTOCIA) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "dystocia (DYSTOCIA)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of dystocia
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(dystocia[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(dystocia[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(dystocia[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(dystocia[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "dystocia OR dystocia"
GWAS_SEARCH_TERMS = ["dystocia", "dystocia"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABCC6": 4.0,
        "ADRB1": 4.0,
        "ADRB2": 4.0,
        "ATP11C": 4.0,
        "BGN": 4.0,
        "CEP192": 4.0,
        "CGA": 4.0,
        "CGB5": 4.0,
        "CHKA": 4.0,
        "CHKB": 4.0,
        "CMPK1": 4.0,
        "CXCL8": 4.0,
        "CYP24A1": 4.0,
        "DCN": 4.0,
        "EDN1": 4.0,
        "ERAP2": 4.0,
        "EXOSC10": 4.0,
        "FASLG": 4.0,
        "GGH": 4.0,
        "GGPS1": 4.0,
        "GH1": 4.0,
        "GNRH1": 4.0,
        "HP": 4.0,
        "IBSP": 4.0,
        "IL1A": 4.0,
        "IL1B": 4.0,
        "IL6": 4.0,
        "INS": 4.0,
        "JUP": 4.0,
        "LEPR": 4.0,
        "LILRA3": 4.0,
        "MARCKSL1": 4.0,
        "MBNL2": 4.0,
        "MEPE": 4.0,
        "MMP2": 4.0,
        "MMP9": 4.0,
        "MSTN": 4.0,
        "OXT": 4.0,
        "OXTR": 4.0,
        "PAG1": 4.0,
        "PGA4": 4.0,
        "PGR": 4.0,
        "POMC": 4.0,
        "PRDX1": 4.0,
        "PRKAA1": 4.0,
        "PRL": 4.0,
        "SAA1": 4.0,
        "SAA2": 4.0,
        "SETD3": 4.0,
        "SLC10A4": 4.0,
        "SLC44A5": 4.0,
        "SLCO2A1": 4.0,
        "SOD1": 4.0,
        "SPP1": 4.0,
        "TGM2": 4.0,
        "TNF": 4.0,
        "TNNI3": 4.0,
        "TP53": 4.0,
        "VIP": 4.0,
        "YTHDF2": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "propranolol",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "dystocia-screening-v1",
    "pathway_keywords": [
        "cascade",
        "cell",
        "chemokine",
        "coagulation",
        "cycle",
        "dopamine",
        "glucose",
        "inflammasome",
        "insulin",
        "metabolism",
    ],
    "mechanism_keywords": [
        "cascade",
        "cell",
        "chemokine",
        "coagulation",
        "cycle",
        "dopamine",
        "glucose",
        "inflammasome",
        "insulin",
        "metabolism",
    ],
    "reference_drug_ids": [
        "CHEMBL395429",
        "CHEMBL27",
        "CHEMBL27",
        "CHEMBL27",
        "CHEMBL27",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_dystocia_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
