"""epidermolytic palmoplantar keratoderma, 1 (EPIDERMOLYTIC_PALMOPLANTAR_KERATODERMA_1) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'epidermolytic palmoplantar keratoderma, 1 (EPIDERMOLYTIC_PALMOPLANTAR_KERATODERMA_1)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Localized epidermolytic hyperkeratosis",
    "Palmoplantar hyperkeratosis",
    "Palmar hyperkeratosis",
    "Increased circulating IgE concentration",
    "Autosomal dominant inheritance",
    "Plantar hyperkeratosis",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(epidermolytic palmoplantar keratoderma, 1[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(epidermolytic palmoplantar keratoderma, 1[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(epidermolytic palmoplantar keratoderma, 1[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(epidermolytic palmoplantar keratoderma, 1[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'epidermolytic palmoplantar keratoderma, 1 OR epidermolytic'
GWAS_SEARCH_TERMS = ['epidermolytic palmoplantar keratoderma, 1', 'epidermolytic']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABCA12": 4.0,
        "AICDA": 4.0,
        "C8orf44-SGK3": 4.0,
        "CARD11": 4.0,
        "CCHCR1": 4.0,
        "CD28": 4.0,
        "CD40": 4.0,
        "CES2": 4.0,
        "DSG4": 4.0,
        "EDA": 4.0,
        "EGFR": 4.0,
        "FAM83G": 4.0,
        "FCER1G": 4.0,
        "FCER2": 4.0,
        "FCGR2A": 4.0,
        "FCGR2B": 4.0,
        "FCGR2C": 4.0,
        "FLG": 4.0,
        "FYN": 4.0,
        "GATA3": 4.0,
        "GPX8": 4.0,
        "GSDMA": 4.0,
        "HOXC13": 4.0,
        "HOXC4": 4.0,
        "ICOS": 4.0,
        "IFIT2": 4.0,
        "IKBKG": 4.0,
        "IL21R": 4.0,
        "IL4": 4.0,
        "ITGB2": 4.0,
        "KLK11": 4.0,
        "KRT1": 4.0,
        "KRT10": 4.0,
        "KRT2": 4.0,
        "KRT25": 4.0,
        "KRT27": 4.0,
        "KRT71": 4.0,
        "KRT75": 4.0,
        "KRT76": 4.0,
        "KRT9": 4.0,
        "LIPH": 4.0,
        "LRIG1": 4.0,
        "MPZL3": 4.0,
        "NSDHL": 4.0,
        "PADI3": 4.0,
        "PIGR": 4.0,
        "PRSS8": 4.0,
        "PSTPIP2": 4.0,
        "SGK3": 4.0,
        "SH2D1A": 4.0,
        "SLC27A4": 4.0,
        "SPINK5": 4.0,
        "ST14": 4.0,
        "STAT6": 4.0,
        "TGFA": 4.0,
        "TGM3": 4.0,
        "TMEM79": 4.0,
        "TNFRSF21": 4.0,
        "TRPV3": 4.0,
        "ZDHHC21": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "diclofenac",
        "fluorouracil",
        "imiquimod",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "epidermolytic_palmoplantar_keratoderma_1-screening-v1",
    "pathway_keywords": [
        "(th2)",
        "adhesion",
        "cascade",
        "cell",
        "coagulation",
        "complement",
        "hedgehog",
        "inflammasome",
        "integrin",
        "mapk",
    ],
    "mechanism_keywords": [
        "(th2)",
        "adhesion",
        "cascade",
        "cell",
        "coagulation",
        "complement",
        "hedgehog",
        "inflammasome",
        "integrin",
        "mapk",
    ],
    "reference_drug_ids": [
        "CHEMBL139",
        "CHEMBL1282",
        "CHEMBL185",
        "CHEMBL139",
        "CHEMBL1282",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_epidermolytic_palmoplantar_keratoderma_1_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
