"""pleurisy (PLEURISY) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "pleurisy (PLEURISY)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of pleurisy
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(pleurisy[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(pleurisy[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(pleurisy[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(pleurisy[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "pleurisy OR pleurisy"
GWAS_SEARCH_TERMS = ["pleurisy", "pleurisy"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABCC5": 4.0,
        "ADA": 4.0,
        "AFM": 4.0,
        "AGO2": 4.0,
        "ALOX5": 4.0,
        "ATP5MK": 4.0,
        "BDKRB2": 4.0,
        "CALCA": 4.0,
        "CCL2": 4.0,
        "CCN6": 4.0,
        "CD40LG": 4.0,
        "CD8A": 4.0,
        "CDKN2A": 4.0,
        "COX5A": 4.0,
        "COX8A": 4.0,
        "CPOX": 4.0,
        "CRP": 4.0,
        "CXCL8": 4.0,
        "GSDMB": 4.0,
        "GTF2A1L": 4.0,
        "HPD": 4.0,
        "HRH4": 4.0,
        "HSPA1A": 4.0,
        "HSPA1B": 4.0,
        "IL1B": 4.0,
        "IL6": 4.0,
        "ISYNA1": 4.0,
        "KLK4": 4.0,
        "KNG1": 4.0,
        "LYZ": 4.0,
        "MPO": 4.0,
        "MSLN": 4.0,
        "MT-CO2": 4.0,
        "NLRP3": 4.0,
        "NOS1": 4.0,
        "NOS2": 4.0,
        "PCLAF": 4.0,
        "PEPD": 4.0,
        "PLG": 4.0,
        "PPARD": 4.0,
        "PRL": 4.0,
        "PTGS2": 4.0,
        "SOD1": 4.0,
        "STON1-GTF2A1L": 4.0,
        "TAC1": 4.0,
        "TGFB1": 4.0,
        "TNF": 4.0,
        "TNFRSF18": 4.0,
        "UROD": 4.0,
        "VEGFA": 4.0,
        "VSX1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "alectinib",
        "aspirin",
        "budesonide",
        "ciclesonide",
        "doxapram",
        "dupilumab",
        "gsk-1995057",
        "ivacaftor",
        "linagliptin",
        "methylprednisolone",
        "montelukast",
        "naphazoline",
        "naphazoline hydrochloride",
        "nitric oxide",
        "pheniramine",
        "pheniramine maleate",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "pleurisy-screening-v1",
    "pathway_keywords": [
        "cascade",
        "cell",
        "chemokine",
        "coagulation",
        "cycle",
        "hormone",
        "inflammasome",
        "pathway",
        "receptor",
        "regulation",
    ],
    "mechanism_keywords": [
        "cascade",
        "cell",
        "chemokine",
        "coagulation",
        "cycle",
        "hormone",
        "inflammasome",
        "pathway",
        "receptor",
        "regulation",
    ],
    "reference_drug_ids": [
        "CHEMBL1706",
        "CHEMBL1754",
        "CHEMBL650",
        "CHEMBL787",
        "CHEMBL1738797",
        "CHEMBL237500",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_pleurisy_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
