"""brachyolmia-amelogenesis imperfecta syndrome (BRACHYOLMIA_AMELOGENESIS_IMPERFECTA_SYNDROME) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'brachyolmia-amelogenesis imperfecta syndrome (BRACHYOLMIA_AMELOGENESIS_IMPERFECTA_SYNDROME)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Narrow vertebral interpedicular distance",
    "Autosomal recessive inheritance",
    "Widely spaced teeth",
    "Oligodontia",
    "Platyspondyly",
    "Mandibular prognathia",
    "Mitral valve prolapse",
    "Hypertrichosis",
    "Herniation of intervertebral nuclei",
    "Short stature",
    "Microdontia",
    "Hypoplasia of the maxilla",
    "Intervertebral space narrowing",
    "Scoliosis",
    "Amelogenesis imperfecta",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(brachyolmia-amelogenesis imperfecta syndrome[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(brachyolmia-amelogenesis imperfecta syndrome[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(brachyolmia-amelogenesis imperfecta syndrome[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(brachyolmia-amelogenesis imperfecta syndrome[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'brachyolmia-amelogenesis imperfecta syndrome OR brachyolmia-amelogenesis'
GWAS_SEARCH_TERMS = ['brachyolmia-amelogenesis imperfecta syndrome', 'brachyolmia-amelogenesis']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AFF3": 4.0,
        "ALPL": 4.0,
        "AMBN": 4.0,
        "AMELX": 4.0,
        "AMELY": 4.0,
        "AMTN": 4.0,
        "ANTXR1": 4.0,
        "ASXL1": 4.0,
        "ATPAF2": 4.0,
        "BCL11B": 4.0,
        "C3orf38": 4.0,
        "DMP1": 4.0,
        "EDA": 4.0,
        "EDAR": 4.0,
        "ENAM": 4.0,
        "FAM20A": 4.0,
        "FGF9": 4.0,
        "FGFR3": 4.0,
        "GREM2": 4.0,
        "ITGA11": 4.0,
        "LASP1": 4.0,
        "LOXL3": 4.0,
        "LRP6": 4.0,
        "LTBP1": 4.0,
        "LTBP3": 4.0,
        "MEX3B": 4.0,
        "MMP20": 4.0,
        "MMP9": 4.0,
        "NECTIN1": 4.0,
        "NFIC": 4.0,
        "ODAPH": 4.0,
        "OS9": 4.0,
        "PAX1": 4.0,
        "PAX9": 4.0,
        "POSTN": 4.0,
        "ROPN1L": 4.0,
        "RPL38": 4.0,
        "RPS6KA3": 4.0,
        "SETD5": 4.0,
        "SH3PXD2B": 4.0,
        "SLC25A21": 4.0,
        "SP6": 4.0,
        "SPRY2": 4.0,
        "SSUH2": 4.0,
        "TGFB1": 4.0,
        "TMEM273": 4.0,
        "TNN": 4.0,
        "WDR72": 4.0,
        "WNT10A": 4.0,
        "ZIC3": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "brachyolmia_amelogenesis_imperfecta_syndrome-screening-v1",
    "pathway_keywords": [
        "adhesion",
        "bone",
        "cascade",
        "cell",
        "coagulation",
        "hormone",
        "integrin",
        "lipid",
        "mapk",
        "metabolism",
    ],
    "mechanism_keywords": [
        "adhesion",
        "bone",
        "cascade",
        "cell",
        "coagulation",
        "hormone",
        "integrin",
        "lipid",
        "mapk",
        "metabolism",
    ],
    "reference_drug_ids": [
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_brachyolmia_amelogenesis_imperfecta_syndrome_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
