"""carbohydrate measurement (CARBOHYDRATE_MEASUREMENT) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'carbohydrate measurement (CARBOHYDRATE_MEASUREMENT)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of carbohydrate measurement
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(carbohydrate measurement[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(carbohydrate measurement[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(carbohydrate measurement[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(carbohydrate measurement[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'carbohydrate measurement OR carbohydrate'
GWAS_SEARCH_TERMS = ['carbohydrate measurement', 'carbohydrate']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "B3GNTL1": 4.0,
        "BCAT2": 4.0,
        "BST1": 4.0,
        "CD38": 4.0,
        "CITED2": 4.0,
        "FAM200B": 4.0,
        "FIGNL1": 4.0,
        "FN3K": 4.0,
        "FN3KRP": 4.0,
        "FUT2": 4.0,
        "FUT3": 4.0,
        "FUT6": 4.0,
        "GGA1": 4.0,
        "HK1": 4.0,
        "HSD17B14": 4.0,
        "IKZF1": 4.0,
        "LGALS1": 4.0,
        "MACO1": 4.0,
        "MAMSTR": 4.0,
        "PLEKHA4": 4.0,
        "RASIP1": 4.0,
        "RHCE": 4.0,
        "RHD": 4.0,
        "RSRP1": 4.0,
        "TBCD": 4.0,
        "TMC1": 4.0,
        "TMEM50A": 4.0,
        "TXLNB": 4.0,
        "VMAC": 4.0,
        "ZFAND5": 4.0,
        "ZNF750": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "carbohydrate_measurement-screening-v1",
    "pathway_keywords": [
        "cascade",
        "cell",
        "coagulation",
        "mapk",
        "receptor",
        "signaling",
    ],
    "mechanism_keywords": [
        "cascade",
        "cell",
        "coagulation",
        "mapk",
        "receptor",
        "signaling",
    ],
    "reference_drug_ids": [
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_carbohydrate_measurement_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
