"""myofibrillar myopathy 2 (MYOFIBRILLAR_MYOPATHY_2) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'myofibrillar myopathy 2 (MYOFIBRILLAR_MYOPATHY_2)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of myofibrillar myopathy 2
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(myofibrillar myopathy 2[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(myofibrillar myopathy 2[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(myofibrillar myopathy 2[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(myofibrillar myopathy 2[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'myofibrillar myopathy 2 OR myofibrillar'
GWAS_SEARCH_TERMS = ['myofibrillar myopathy 2', 'myofibrillar']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACTA1": 4.0,
        "ACTMAP": 4.0,
        "ANK1": 4.0,
        "ASNSD1": 4.0,
        "BIN1": 4.0,
        "C10orf71": 4.0,
        "CAPN3": 4.0,
        "CAV3": 4.0,
        "CFL2": 4.0,
        "CHD4": 4.0,
        "CHKB": 4.0,
        "COL13A1": 4.0,
        "COL6A1": 4.0,
        "COL6A3": 4.0,
        "CRYAB": 4.0,
        "CSRP3": 4.0,
        "DES": 4.0,
        "DMD": 4.0,
        "DMPK": 4.0,
        "DNAJB4": 4.0,
        "DNM2": 4.0,
        "DYSF": 4.0,
        "FBN2": 4.0,
        "FKRP": 4.0,
        "FLNC": 4.0,
        "GAA": 4.0,
        "GARS1": 4.0,
        "GMPPA": 4.0,
        "ITGA7": 4.0,
        "KLHL31": 4.0,
        "KLHL40": 4.0,
        "LAMA2": 4.0,
        "LARGE1": 4.0,
        "LDB3": 4.0,
        "LIMCH1": 4.0,
        "LMNA": 4.0,
        "LMOD2": 4.0,
        "LMOD3": 4.0,
        "MTM1": 4.0,
        "MYBPC2": 4.0,
        "MYBPC3": 4.0,
        "MYH4": 4.0,
        "MYOZ2": 4.0,
        "NEB": 4.0,
        "NFATC3": 4.0,
        "PLPP7": 4.0,
        "RYR1": 4.0,
        "SCN4A": 4.0,
        "SCN8A": 4.0,
        "SGCA": 4.0,
        "SGCB": 4.0,
        "SGCD": 4.0,
        "SGCG": 4.0,
        "SLC6A6": 4.0,
        "STIM1": 4.0,
        "SYNM": 4.0,
        "TNNT1": 4.0,
        "TTN": 4.0,
        "VCP": 4.0,
        "XIRP1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "methylprednisolone",
        "rituximab",
        "vatiquinone",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "myofibrillar_myopathy_2-screening-v1",
    "pathway_keywords": [
        "adhesion",
        "cascade",
        "cell",
        "coagulation",
        "hormone",
        "integrin",
        "pathway",
        "remodeling",
        "signaling",
        "thyroid",
    ],
    "mechanism_keywords": [
        "adhesion",
        "cascade",
        "cell",
        "coagulation",
        "hormone",
        "integrin",
        "pathway",
        "remodeling",
        "signaling",
        "thyroid",
    ],
    "reference_drug_ids": [
        "CHEMBL1201576",
        "CHEMBL1201567",
        "CHEMBL650",
        "CHEMBL1812161",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_myofibrillar_myopathy_2_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
