"""T-lymphoblastic lymphoma (T_LYMPHOBLASTIC_LYMPHOMA) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "T-lymphoblastic lymphoma (T_LYMPHOBLASTIC_LYMPHOMA)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of T-lymphoblastic lymphoma
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(T-lymphoblastic lymphoma[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(T-lymphoblastic lymphoma[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(T-lymphoblastic lymphoma[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(T-lymphoblastic lymphoma[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "T-lymphoblastic lymphoma OR T-lymphoblastic"
GWAS_SEARCH_TERMS = ["T-lymphoblastic lymphoma", "T-lymphoblastic"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABL1": 4.0,
        "ALK": 4.0,
        "BCL2": 4.0,
        "BCR": 4.0,
        "CD38": 4.0,
        "CD7": 4.0,
        "CTNNB1": 4.0,
        "DHFR": 4.0,
        "ERG": 4.0,
        "FAAH": 4.0,
        "FBXW7": 4.0,
        "FGFR1": 4.0,
        "HRH1": 4.0,
        "HRH2": 4.0,
        "IMPDH1": 4.0,
        "IMPDH2": 4.0,
        "JAK2": 4.0,
        "KIT": 4.0,
        "MME": 4.0,
        "MS4A1": 4.0,
        "NOTCH1": 4.0,
        "NPM1": 4.0,
        "NR3C1": 4.0,
        "NRAS": 4.0,
        "NUP214": 4.0,
        "PCM1": 4.0,
        "PDGFRB": 4.0,
        "POLA1": 4.0,
        "POLA2": 4.0,
        "POLD1": 4.0,
        "POLD2": 4.0,
        "POLD3": 4.0,
        "POLD4": 4.0,
        "POLE": 4.0,
        "POLE2": 4.0,
        "POLE3": 4.0,
        "PPAT": 4.0,
        "PRIM1": 4.0,
        "PRIM2": 4.0,
        "PSMB5": 4.0,
        "PTGS1": 4.0,
        "PTGS2": 4.0,
        "SET": 4.0,
        "STIL": 4.0,
        "TAL1": 4.0,
        "TET2": 4.0,
        "THAP12": 4.0,
        "TOP2A": 4.0,
        "TOP2B": 4.0,
        "TRPV1": 4.0,
        "TUBB": 4.0,
        "TUBB1": 4.0,
        "TUBB2A": 4.0,
        "TUBB2B": 4.0,
        "TUBB3": 4.0,
        "TUBB4A": 4.0,
        "TUBB4B": 4.0,
        "TUBB6": 4.0,
        "TUBB8": 4.0,
        "WT1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "acetaminophen",
        "bortezomib",
        "cytarabine",
        "daunorubicin",
        "dexamethasone",
        "doxorubicin",
        "doxorubicin hydrochloride",
        "etoposide",
        "imatinib",
        "imatinib mesylate",
        "isatuximab",
        "mercaptopurine",
        "mercaptopurine anhydrous",
        "methotrexate",
        "rituximab",
        "thioguanine",
        "vincristine",
        "vincristine sulfate",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "t_lymphoblastic_lymphoma-screening-v1",
    "pathway_keywords": [
        "apoptosis",
        "cell",
        "dopamine",
        "hormone",
        "mapk",
        "mast",
        "notch",
        "receptor",
        "serotonin",
        "signaling",
    ],
    "mechanism_keywords": [
        "apoptosis",
        "cell",
        "dopamine",
        "hormone",
        "mapk",
        "mast",
        "notch",
        "receptor",
        "serotonin",
        "signaling",
    ],
    "reference_drug_ids": [
        "CHEMBL501867",
        "CHEMBL501867",
        "CHEMBL90555",
        "CHEMBL501867",
        "CHEMBL803",
        "CHEMBL90555",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_t_lymphoblastic_lymphoma_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
