"""bile duct carcinoma (BILE_DUCT_CARCINOMA) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'bile duct carcinoma (BILE_DUCT_CARCINOMA)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of bile duct carcinoma
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(bile duct carcinoma[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(bile duct carcinoma[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(bile duct carcinoma[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(bile duct carcinoma[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'bile duct carcinoma OR bile'
GWAS_SEARCH_TERMS = ['bile duct carcinoma', 'bile']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACVR1": 4.0,
        "ARHGAP26": 4.0,
        "ATP1A1": 4.0,
        "ATP2B3": 4.0,
        "BAP1": 4.0,
        "BARD1": 4.0,
        "BAX": 4.0,
        "BCL2": 4.0,
        "BCL3": 4.0,
        "BMPR1A": 4.0,
        "BTK": 4.0,
        "CCND2": 4.0,
        "CCND3": 4.0,
        "DDR2": 4.0,
        "DICER1": 4.0,
        "EIF3E": 4.0,
        "ELK4": 4.0,
        "EPAS1": 4.0,
        "EPS15": 4.0,
        "ERCC4": 4.0,
        "ESR1": 4.0,
        "ETV1": 4.0,
        "EZH2": 4.0,
        "FANCC": 4.0,
        "FBXW7": 4.0,
        "FGFR1": 4.0,
        "FGFR2": 4.0,
        "FLT4": 4.0,
        "FOXO3": 4.0,
        "GNAS": 4.0,
        "HLF": 4.0,
        "HNF1A": 4.0,
        "KMT2A": 4.0,
        "LEF1": 4.0,
        "LMO2": 4.0,
        "LRIG3": 4.0,
        "MAML2": 4.0,
        "MAP2K1": 4.0,
        "MITF": 4.0,
        "NDRG1": 4.0,
        "NFE2L2": 4.0,
        "NTRK3": 4.0,
        "PDGFRB": 4.0,
        "PIK3CB": 4.0,
        "POLE": 4.0,
        "POLQ": 4.0,
        "RAF1": 4.0,
        "SALL4": 4.0,
        "SDHC": 4.0,
        "SETD2": 4.0,
        "SMAD2": 4.0,
        "SMAD4": 4.0,
        "SND1": 4.0,
        "STAG2": 4.0,
        "STAT3": 4.0,
        "SYK": 4.0,
        "TCF7L2": 4.0,
        "TERT": 4.0,
        "TGFBR2": 4.0,
        "WWTR1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
        "gemcitabine",
    ],
    "moderate_risk": [
        "capecitabine",
        "cetuximab",
        "crizotinib",
        "erlotinib",
        "erlotinib hydrochloride",
        "everolimus",
        "fluorouracil",
        "gefitinib",
        "irinotecan",
        "ixabepilone",
        "lapatinib",
        "mk-2206",
        "regorafenib",
        "selumetinib",
        "sorafenib",
        "trastuzumab",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "bile_duct_carcinoma-screening-v1",
    "pathway_keywords": [
        "apoptosis",
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "glucose",
        "hepcidin",
        "homeostasis",
        "insulin",
        "iron",
    ],
    "mechanism_keywords": [
        "apoptosis",
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "glucose",
        "hepcidin",
        "homeostasis",
        "insulin",
        "iron",
    ],
    "reference_drug_ids": [
        "CHEMBL1614701",
        "CHEMBL1946170",
        "CHEMBL1946170",
        "CHEMBL1946170",
        "CHEMBL554",
        "CHEMBL888",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_bile_duct_carcinoma_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
