"""phospholipids in large LDL measurement (PHOSPHOLIPIDS_IN_LARGE_LDL_MEASUREMENT) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "phospholipids in large LDL measurement (PHOSPHOLIPIDS_IN_LARGE_LDL_MEASUREMENT)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of phospholipids in large LDL measurement
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(phospholipids in large LDL measurement[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(phospholipids in large LDL measurement[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(phospholipids in large LDL measurement[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(phospholipids in large LDL measurement[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "phospholipids in large LDL measurement OR phospholipids"
GWAS_SEARCH_TERMS = ["phospholipids in large LDL measurement", "phospholipids"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABCA1": 4.0,
        "ABCA5": 4.0,
        "ABCA6": 4.0,
        "ABCG8": 4.0,
        "ABO": 4.0,
        "ANGPTL3": 4.0,
        "ANKDD1B": 4.0,
        "APOA1": 4.0,
        "APOA5": 4.0,
        "APOB": 4.0,
        "APOE": 4.0,
        "APOH": 4.0,
        "ASGR1": 4.0,
        "ATRAID": 4.0,
        "ATXN2": 4.0,
        "CELSR2": 4.0,
        "CETP": 4.0,
        "DNAH11": 4.0,
        "EPGN": 4.0,
        "FADS2": 4.0,
        "FAM117B": 4.0,
        "GCKR": 4.0,
        "HGFAC": 4.0,
        "HK1": 4.0,
        "HMGCR": 4.0,
        "HNF1A": 4.0,
        "HP": 4.0,
        "ITGA1": 4.0,
        "LDLR": 4.0,
        "LIPC": 4.0,
        "LIPG": 4.0,
        "MAFB": 4.0,
        "MAMSTR": 4.0,
        "MAU2": 4.0,
        "MISFA": 4.0,
        "MTARC1": 4.0,
        "MYLIP": 4.0,
        "PCSK9": 4.0,
        "PELO": 4.0,
        "PKN3": 4.0,
        "PLTP": 4.0,
        "SERPINA1": 4.0,
        "SH2B3": 4.0,
        "SLC22A1": 4.0,
        "SORT1": 4.0,
        "SPTY2D1": 4.0,
        "ST3GAL4": 4.0,
        "SUGP1": 4.0,
        "TIMD4": 4.0,
        "TM6SF2": 4.0,
        "TMPRSS11E": 4.0,
        "TNFSF13": 4.0,
        "TOP1": 4.0,
        "TRIB1": 4.0,
        "TRIM5": 4.0,
        "TRPS1": 4.0,
        "USP24": 4.0,
        "ZHX3": 4.0,
        "ZNF285": 4.0,
        "ZPR1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "phospholipids_in_large_ldl_measurement-screening-v1",
    "pathway_keywords": [
        "adhesion",
        "cascade",
        "cell",
        "coagulation",
        "glucose",
        "hormone",
        "insulin",
        "integrin",
        "lipid",
        "metabolism",
    ],
    "mechanism_keywords": [
        "adhesion",
        "cascade",
        "cell",
        "coagulation",
        "glucose",
        "hormone",
        "insulin",
        "integrin",
        "lipid",
        "metabolism",
    ],
    "reference_drug_ids": [],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_phospholipids_in_large_ldl_measurement_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
