"""Keloid (KELOID) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "Keloid (KELOID)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of Keloid
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(Keloid[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(Keloid[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(Keloid[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(Keloid[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "Keloid OR Keloid"
GWAS_SEARCH_TERMS = ["Keloid", "Keloid"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACTA1": 4.0,
        "ADIPOQ": 4.0,
        "AKT1": 4.0,
        "ASAH1": 4.0,
        "BMX": 4.0,
        "BRAF": 4.0,
        "BTK": 4.0,
        "CACNA1G": 4.0,
        "CCN2": 4.0,
        "CMA1": 4.0,
        "CREB3L1": 4.0,
        "CREB3L2": 4.0,
        "DUSP10": 4.0,
        "FAP": 4.0,
        "FOXL2": 4.0,
        "FTO": 4.0,
        "FUS": 4.0,
        "FUT1": 4.0,
        "GABPA": 4.0,
        "GLI1": 4.0,
        "HFE": 4.0,
        "HIF1A": 4.0,
        "HMGB1": 4.0,
        "HOXA11": 4.0,
        "HSPA1A": 4.0,
        "HSPA4": 4.0,
        "HSPA9": 4.0,
        "HTRA1": 4.0,
        "IGF1R": 4.0,
        "IL4R": 4.0,
        "IL6": 4.0,
        "JAK3": 4.0,
        "KDR": 4.0,
        "KIT": 4.0,
        "LOC389151": 4.0,
        "MRPS22": 4.0,
        "MTOR": 4.0,
        "NAV1": 4.0,
        "NEDD4": 4.0,
        "NFE2L2": 4.0,
        "NOTCH1": 4.0,
        "NR": 4.0,
        "NR3C1": 4.0,
        "PDGFRB": 4.0,
        "PHLDA3": 4.0,
        "POSTN": 4.0,
        "PRR23A": 4.0,
        "PRR23C": 4.0,
        "PRTG": 4.0,
        "PTBP1": 4.0,
        "PTBP2": 4.0,
        "PTEN": 4.0,
        "RUNX2": 4.0,
        "SLC2A1": 4.0,
        "SMN1": 4.0,
        "SPOCD1": 4.0,
        "TGFB1": 4.0,
        "TLR7": 4.0,
        "TNF": 4.0,
        "TP53": 4.0,
        "VEGFA": 4.0,
        "WNT5A": 4.0,
        "ZNF217": 4.0,
        "intergenic": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "bevacizumab",
        "dupilumab",
        "imiquimod",
        "losartan",
        "qax-576",
        "ritlecitinib",
        "sorafenib",
        "triamcinolone",
        "triamcinolone acetonide",
    ],
    "low_risk": [
        "insulin human",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "keloid-screening-v1",
    "pathway_keywords": [
        "(th2)",
        "bone",
        "cardiac",
        "cascade",
        "cell",
        "channel",
        "coagulation",
        "conduction",
        "glucose",
        "hedgehog",
    ],
    "mechanism_keywords": [
        "(th2)",
        "bone",
        "cardiac",
        "cascade",
        "cell",
        "channel",
        "coagulation",
        "conduction",
        "glucose",
        "hedgehog",
    ],
    "reference_drug_ids": [
        "CHEMBL1451",
        "CHEMBL191",
        "CHEMBL4085457",
        "CHEMBL1504",
        "CHEMBL1201631",
        "CHEMBL1336",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_keloid_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
