"""ectodermal dysplasia 10A, hypohidrotic/hair/nail type, autosomal dominant (ECTODERMAL_DYSPLASIA_10A_HYPOHIDROTIC_HAIR_NAIL_TYPE_AUTOSOMAL_DOMINANT) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "ectodermal dysplasia 10A, hypohidrotic/hair/nail type, autosomal dominant (ECTODERMAL_DYSPLASIA_10A_HYPOHIDROTIC_HAIR_NAIL_TYPE_AUTOSOMAL_DOMINANT)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Sparse eyelashes",
    "Ectodermal dysplasia",
    "Sparse hair",
    "Sparse eyebrow",
    "Hypohidrosis",
    "Fine hair",
    "Ridged nail",
    "Dry skin",
    "Slow-growing hair",
    "Heat intolerance",
    "Hypodontia",
    "Anodontia",
    "Microdontia",
    "Autosomal dominant inheritance",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(ectodermal dysplasia 10A, hypohidrotic/hair/nail type, autosomal dominant[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(ectodermal dysplasia 10A, hypohidrotic/hair/nail type, autosomal dominant[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(ectodermal dysplasia 10A, hypohidrotic/hair/nail type, autosomal dominant[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(ectodermal dysplasia 10A, hypohidrotic/hair/nail type, autosomal dominant[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = (
    "ectodermal dysplasia 10A, hypohidrotic/hair/nail type, autosomal dominant OR ectodermal"
)
GWAS_SEARCH_TERMS = [
    "ectodermal dysplasia 10A, hypohidrotic/hair/nail type, autosomal dominant",
    "ectodermal",
]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ASS1": 4.0,
        "AWAT2": 4.0,
        "C8orf44-SGK3": 4.0,
        "CCHCR1": 4.0,
        "CD109": 4.0,
        "CERS4": 4.0,
        "CIDEA": 4.0,
        "CTSL": 4.0,
        "CTSV": 4.0,
        "CUX1": 4.0,
        "DSG3": 4.0,
        "DSG4": 4.0,
        "EDA": 4.0,
        "EDAR": 4.0,
        "EDARADD": 4.0,
        "EGFR": 4.0,
        "FA2H": 4.0,
        "FAM83H": 4.0,
        "FOXE1": 4.0,
        "FOXN1": 4.0,
        "FOXP3": 4.0,
        "FOXQ1": 4.0,
        "GATA3": 4.0,
        "GSDMA": 4.0,
        "HEPHL1": 4.0,
        "HOXC13": 4.0,
        "HR": 4.0,
        "KRT17": 4.0,
        "KRT25": 4.0,
        "KRT27": 4.0,
        "KRT71": 4.0,
        "KRT75": 4.0,
        "KRT76": 4.0,
        "KSR1": 4.0,
        "LIPH": 4.0,
        "MPZL3": 4.0,
        "OTC": 4.0,
        "PADI3": 4.0,
        "PKP3": 4.0,
        "PRSS8": 4.0,
        "SCD": 4.0,
        "SGK3": 4.0,
        "SOX18": 4.0,
        "TAL1": 4.0,
        "TGFA": 4.0,
        "TGM3": 4.0,
        "TMEM79": 4.0,
        "TRPV3": 4.0,
        "TWIST2": 4.0,
        "ZDHHC21": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "adapalene",
        "betamethasone dipropionate",
        "betamethasone valerate",
        "cholecalciferol",
        "clobetasol propionate",
        "desonide",
        "desoximetasone",
        "diflorasone diacetate",
        "doxycycline",
        "dupilumab",
        "fluocinolone acetonide",
        "fluocinonide",
        "fluticasone propionate",
        "halcinonide",
        "halobetasol propionate",
        "hydrocortisone",
        "hydrocortisone acetate",
        "hydroxyzine pamoate",
        "levocetirizine dihydrochloride",
        "lidocaine",
        "melatonin",
        "midazolam",
        "mometasone furoate",
        "prednicarbate",
        "prilocaine",
        "sildenafil",
        "tacrolimus anhydrous",
        "tazarotene",
        "tetracaine",
        "triamcinolone",
        "triamcinolone acetonide",
    ],
    "low_risk": [
        "diltiazem",
        "diltiazem hydrochloride",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "ectodermal_dysplasia_10a_hypohidrotic_hair_nail_type_autosomal_dominant-screening-v1",
    "pathway_keywords": [
        "(th2)",
        "cascade",
        "complement",
        "hedgehog",
        "hormone",
        "mapk",
        "pathway",
        "signaling",
        "thyroid",
    ],
    "mechanism_keywords": [
        "(th2)",
        "cascade",
        "complement",
        "hedgehog",
        "hormone",
        "mapk",
        "pathway",
        "signaling",
        "thyroid",
    ],
    "reference_drug_ids": [
        "CHEMBL1265",
        "CHEMBL79",
        "CHEMBL989",
        "CHEMBL698",
        "CHEMBL79",
        "CHEMBL655",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_ectodermal_dysplasia_10a_hypohidrotic_hair_nail_type_autosomal_dominant_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
