"""pervasive developmental disorder (PERVASIVE_DEVELOPMENTAL_DISORDER) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'pervasive developmental disorder (PERVASIVE_DEVELOPMENTAL_DISORDER)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of pervasive developmental disorder
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(pervasive developmental disorder[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(pervasive developmental disorder[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(pervasive developmental disorder[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(pervasive developmental disorder[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'pervasive developmental disorder OR pervasive'
GWAS_SEARCH_TERMS = ['pervasive developmental disorder', 'pervasive']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABCB1": 4.0,
        "ADCY4": 4.0,
        "AFF2": 4.0,
        "AGTR2": 4.0,
        "AR": 4.0,
        "ARSA": 4.0,
        "ARSL": 4.0,
        "CCK": 4.0,
        "CD40LG": 4.0,
        "CHRNA3": 4.0,
        "CHRNB4": 4.0,
        "COL9A1": 4.0,
        "CXCL8": 4.0,
        "CYP2D6": 4.0,
        "DIO2": 4.0,
        "DMBX1": 4.0,
        "DRD2": 4.0,
        "ENPP2": 4.0,
        "FANCA": 4.0,
        "FAS": 4.0,
        "FBXW7": 4.0,
        "FCGR3A": 4.0,
        "FCGR3B": 4.0,
        "FMR1": 4.0,
        "FXN": 4.0,
        "GABRB3": 4.0,
        "GRIK2": 4.0,
        "HELZ": 4.0,
        "HTR1A": 4.0,
        "HTR2A": 4.0,
        "IL1B": 4.0,
        "IL6": 4.0,
        "MAST3": 4.0,
        "MECP2": 4.0,
        "MUTYH": 4.0,
        "NLGN2": 4.0,
        "NLGN3": 4.0,
        "NRXN1": 4.0,
        "OPRD1": 4.0,
        "OPRK1": 4.0,
        "OPRM1": 4.0,
        "OTC": 4.0,
        "OXTR": 4.0,
        "PON1": 4.0,
        "PRDM15": 4.0,
        "PRL": 4.0,
        "PUS7": 4.0,
        "RBFOX1": 4.0,
        "SCT": 4.0,
        "SLC2A3": 4.0,
        "SLC38A8": 4.0,
        "SLC6A4": 4.0,
        "SMG1": 4.0,
        "SPTBN1": 4.0,
        "SULF1": 4.0,
        "SULF2": 4.0,
        "TBC1D9": 4.0,
        "TMEM185A": 4.0,
        "ZNF135": 4.0,
        "ZNF77": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "aripiprazole",
        "mecamylamine",
        "naltrexone",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "pervasive_developmental_disorder-screening-v1",
    "pathway_keywords": [
        "angiotensin",
        "autophagy",
        "cascade",
        "chemokine",
        "coagulation",
        "gaba",
        "glucose",
        "glutamate",
        "inflammasome",
        "insulin",
    ],
    "mechanism_keywords": [
        "angiotensin",
        "autophagy",
        "cascade",
        "chemokine",
        "coagulation",
        "gaba",
        "glucose",
        "glutamate",
        "inflammasome",
        "insulin",
    ],
    "reference_drug_ids": [
        "CHEMBL1112",
        "CHEMBL1112",
        "CHEMBL1112",
        "CHEMBL1112",
        "CHEMBL1112",
        "CHEMBL19019",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_pervasive_developmental_disorder_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
