"""breast fibrocystic disease (BREAST_FIBROCYSTIC_DISEASE) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "breast fibrocystic disease (BREAST_FIBROCYSTIC_DISEASE)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of breast fibrocystic disease
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(breast fibrocystic disease[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(breast fibrocystic disease[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(breast fibrocystic disease[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(breast fibrocystic disease[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "breast fibrocystic disease OR breast"
GWAS_SEARCH_TERMS = ["breast fibrocystic disease", "breast"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AP1B1": 4.0,
        "AR": 4.0,
        "AREG": 4.0,
        "ASCC2": 4.0,
        "BTC": 4.0,
        "C22orf31": 4.0,
        "CABP7": 4.0,
        "CASTOR1": 4.0,
        "CCDC117": 4.0,
        "CCDC157": 4.0,
        "CHEK2": 4.0,
        "CPT1A": 4.0,
        "DUSP18": 4.0,
        "EMID1": 4.0,
        "EREG": 4.0,
        "EWSR1": 4.0,
        "GAL3ST1": 4.0,
        "GAS2L1": 4.0,
        "HMGB1": 4.0,
        "HORMAD2": 4.0,
        "HSCB": 4.0,
        "IGF1": 4.0,
        "KLK7": 4.0,
        "KREMEN1": 4.0,
        "LIF": 4.0,
        "MORC2": 4.0,
        "MTFP1": 4.0,
        "MTMR3": 4.0,
        "NEFH": 4.0,
        "NF2": 4.0,
        "NIPSNAP1": 4.0,
        "OSBP2": 4.0,
        "OSM": 4.0,
        "PES1": 4.0,
        "PGR": 4.0,
        "PITPNB": 4.0,
        "RASL10A": 4.0,
        "RFPL1": 4.0,
        "RHBDD3": 4.0,
        "RNF215": 4.0,
        "RTKN2": 4.0,
        "SEC14L2": 4.0,
        "SEC14L3": 4.0,
        "SEC14L4": 4.0,
        "SEC14L6": 4.0,
        "SELENOM": 4.0,
        "SF3A1": 4.0,
        "SLC35E4": 4.0,
        "SMTN": 4.0,
        "TBC1D10A": 4.0,
        "TCN2": 4.0,
        "THOC5": 4.0,
        "TP53": 4.0,
        "TTC28": 4.0,
        "TUG1": 4.0,
        "UQCR10": 4.0,
        "XBP1": 4.0,
        "ZMAT5": 4.0,
        "ZNF365": 4.0,
        "ZNRF3": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "danazol",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "breast_fibrocystic_disease-screening-v1",
    "pathway_keywords": [
        "adhesion",
        "autophagy",
        "cascade",
        "cell",
        "coagulation",
        "complement",
        "dopamine",
        "integrin",
        "mapk",
        "repair",
    ],
    "mechanism_keywords": [
        "adhesion",
        "autophagy",
        "cascade",
        "cell",
        "coagulation",
        "complement",
        "dopamine",
        "integrin",
        "mapk",
        "repair",
    ],
    "reference_drug_ids": [
        "CHEMBL1479",
        "CHEMBL1479",
        "CHEMBL1479",
        "CHEMBL1479",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_breast_fibrocystic_disease_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
