"""Matthew-Wood syndrome (MATTHEW_WOOD_SYNDROME) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "Matthew-Wood syndrome (MATTHEW_WOOD_SYNDROME)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Pulmonic stenosis",
    "Short stature",
    "Generalized hypotonia",
    "Intestinal malrotation",
    "Retrognathia",
    "Intrauterine growth retardation",
    "Atrial septal defect",
    "Single ventricle",
    "Microphthalmia",
    "Multilobulated spleen",
    "Horseshoe kidney",
    "Neonatal death",
    "Hypoplastic left atrium",
    "Congenital diaphragmatic hernia",
    "Tetralogy of Fallot",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(Matthew-Wood syndrome[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(Matthew-Wood syndrome[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(Matthew-Wood syndrome[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(Matthew-Wood syndrome[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "Matthew-Wood syndrome OR Matthew-Wood"
GWAS_SEARCH_TERMS = ["Matthew-Wood syndrome", "Matthew-Wood"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACVR2B": 4.0,
        "CC2D2A": 4.0,
        "CFC1": 4.0,
        "CFC1B": 4.0,
        "CITED2": 4.0,
        "CNTRL": 4.0,
        "DLG1": 4.0,
        "DNAH11": 4.0,
        "FOXH1": 4.0,
        "FREM1": 4.0,
        "FUZ": 4.0,
        "GATA4": 4.0,
        "HEY2": 4.0,
        "HHIP": 4.0,
        "KLHL6": 4.0,
        "LAMA5": 4.0,
        "LAMC1": 4.0,
        "LHCGR": 4.0,
        "LRP2": 4.0,
        "MEGF8": 4.0,
        "NDST1": 4.0,
        "PBX1": 4.0,
        "PCSK5": 4.0,
        "PDK2": 4.0,
        "PDX1": 4.0,
        "PIGV": 4.0,
        "PITX2": 4.0,
        "PRAMEF1": 4.0,
        "PRAMEF10": 4.0,
        "PRAMEF11": 4.0,
        "PRAMEF12": 4.0,
        "PRAMEF13": 4.0,
        "PRAMEF14": 4.0,
        "PRAMEF15": 4.0,
        "PRAMEF17": 4.0,
        "PRAMEF18": 4.0,
        "PRAMEF19": 4.0,
        "PRAMEF2": 4.0,
        "PRAMEF20": 4.0,
        "PRAMEF25": 4.0,
        "PRAMEF26": 4.0,
        "PRAMEF27": 4.0,
        "PRAMEF33": 4.0,
        "PRAMEF4": 4.0,
        "PRAMEF5": 4.0,
        "PRAMEF6": 4.0,
        "PRAMEF7": 4.0,
        "PRAMEF8": 4.0,
        "PRAMEF9": 4.0,
        "RARB": 4.0,
        "RERE": 4.0,
        "RET": 4.0,
        "RND2": 4.0,
        "STRA6": 4.0,
        "TBC1D32": 4.0,
        "TCF21": 4.0,
        "TMEM248": 4.0,
        "VAMP4": 4.0,
        "WNT7B": 4.0,
        "ZFPM2": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "matthew_wood_syndrome-screening-v1",
    "pathway_keywords": [
        "cascade",
        "coagulation",
        "glucose",
        "insulin",
        "metabolism",
        "secretion",
        "signaling",
    ],
    "mechanism_keywords": [
        "cascade",
        "coagulation",
        "glucose",
        "insulin",
        "metabolism",
        "secretion",
        "signaling",
    ],
    "reference_drug_ids": [
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_matthew_wood_syndrome_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
