"""hyper-IgM syndrome type 2 (HYPER_IGM_SYNDROME_TYPE_2) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'hyper-IgM syndrome type 2 (HYPER_IGM_SYNDROME_TYPE_2)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Increased circulating IgM concentration",
    "Recurrent infection of the gastrointestinal tract",
    "Impaired Ig class switch recombination",
    "Complete or near-complete absence of specific antibody response to tetanus vaccine",
    "Immunodeficiency",
    "Lymphadenopathy",
    "Recurrent bacterial infections",
    "Autosomal recessive inheritance",
    "Decreased circulating IgA concentration",
    "Recurrent respiratory infections",
    "Recurrent upper and lower respiratory tract infections",
    "Childhood onset",
    "Decreased circulating IgG concentration",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(hyper-IgM syndrome type 2[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(hyper-IgM syndrome type 2[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(hyper-IgM syndrome type 2[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(hyper-IgM syndrome type 2[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'hyper-IgM syndrome type 2 OR hyper-IgM'
GWAS_SEARCH_TERMS = ['hyper-IgM syndrome type 2', 'hyper-IgM']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AICDA": 4.0,
        "APOBEC3B": 4.0,
        "APOBEC3C": 4.0,
        "APOBEC3D": 4.0,
        "APOBEC3F": 4.0,
        "APOBEC3G": 4.0,
        "APOBEC3H": 4.0,
        "BTK": 4.0,
        "CARD11": 4.0,
        "CD19": 4.0,
        "CD209": 4.0,
        "CD28": 4.0,
        "CD40": 4.0,
        "CD40LG": 4.0,
        "CLEC4M": 4.0,
        "CR2": 4.0,
        "DAPP1": 4.0,
        "DOCK2": 4.0,
        "FAS": 4.0,
        "ICOS": 4.0,
        "ICOSLG": 4.0,
        "IFNG": 4.0,
        "IFNGR1": 4.0,
        "IL13": 4.0,
        "IL21R": 4.0,
        "IL25": 4.0,
        "IL4": 4.0,
        "IL4R": 4.0,
        "IRF4": 4.0,
        "JAK3": 4.0,
        "JCHAIN": 4.0,
        "LTA": 4.0,
        "LTB": 4.0,
        "LYN": 4.0,
        "MALT1": 4.0,
        "MAP3K14": 4.0,
        "MYD88": 4.0,
        "NFKB1": 4.0,
        "NFKB2": 4.0,
        "PDCD1LG2": 4.0,
        "PIGR": 4.0,
        "PIK3CD": 4.0,
        "POU2AF1": 4.0,
        "PRF1": 4.0,
        "PRKCB": 4.0,
        "PTPN22": 4.0,
        "RAG2": 4.0,
        "REL": 4.0,
        "RORC": 4.0,
        "SH2D1A": 4.0,
        "SPPL2A": 4.0,
        "STAT1": 4.0,
        "STAT4": 4.0,
        "STAT6": 4.0,
        "TICAM1": 4.0,
        "TLR2": 4.0,
        "TLR4": 4.0,
        "TNF": 4.0,
        "TNFRSF13B": 4.0,
        "ZNF318": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "hyper_igm_syndrome_type_2-screening-v1",
    "pathway_keywords": [
        "(th2)",
        "adhesion",
        "cascade",
        "cell",
        "checkpoint",
        "complement",
        "immune",
        "inflammasome",
        "integrin",
        "lipid",
    ],
    "mechanism_keywords": [
        "(th2)",
        "adhesion",
        "cascade",
        "cell",
        "checkpoint",
        "complement",
        "immune",
        "inflammasome",
        "integrin",
        "lipid",
    ],
    "reference_drug_ids": [
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_hyper_igm_syndrome_type_2_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
