"""genetic generalized epilepsy (GENETIC_GENERALIZED_EPILEPSY) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'genetic generalized epilepsy (GENETIC_GENERALIZED_EPILEPSY)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of genetic generalized epilepsy
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(genetic generalized epilepsy[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(genetic generalized epilepsy[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(genetic generalized epilepsy[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(genetic generalized epilepsy[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'genetic generalized epilepsy OR genetic'
GWAS_SEARCH_TERMS = ['genetic generalized epilepsy', 'genetic']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "APOE": 4.0,
        "BCL11A": 4.0,
        "BDNF": 4.0,
        "BRD7": 4.0,
        "CACNA1H": 4.0,
        "CHRNA7": 4.0,
        "CRISP2": 4.0,
        "DYNC1H1": 4.0,
        "EFHC1": 4.0,
        "ERBB4": 4.0,
        "GABRA1": 4.0,
        "GABRA2": 4.0,
        "GABRB2": 4.0,
        "GABRG2": 4.0,
        "GRIK1": 4.0,
        "GRM3": 4.0,
        "GRM5": 4.0,
        "HCN1": 4.0,
        "HCN4": 4.0,
        "HIP1": 4.0,
        "KCNA2": 4.0,
        "KCNAB1": 4.0,
        "KCNC2": 4.0,
        "KCNN2": 4.0,
        "KCNQ5": 4.0,
        "NIPA1": 4.0,
        "NPY": 4.0,
        "PNPO": 4.0,
        "PRSS55": 4.0,
        "RBFOX1": 4.0,
        "RELN": 4.0,
        "RYR2": 4.0,
        "SCN1A": 4.0,
        "SCN2A": 4.0,
        "SCN3A": 4.0,
        "SCN8A": 4.0,
        "SLC2A1": 4.0,
        "SPZ1": 4.0,
        "STAT4": 4.0,
        "STX1B": 4.0,
        "THBS1": 4.0,
        "TREM2": 4.0,
        "TTC21B": 4.0,
        "TXNRD1": 4.0,
        "USP25": 4.0,
        "VRK2": 4.0,
        "YWHAG": 4.0,
        "ZCWPW1": 4.0,
        "ZEB2": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "capecitabine",
        "dasatinib",
        "dexmedetomidine",
        "galantamine",
        "galantamine hydrobromide",
        "lapatinib",
        "pentoxifylline",
        "roflumilast",
        "sacituzumab govitecan",
        "trastuzumab",
        "vorinostat",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "genetic_generalized_epilepsy-screening-v1",
    "pathway_keywords": [
        "cardiac",
        "channel",
        "conduction",
        "dopamine",
        "gaba",
        "glucose",
        "glutamate",
        "insulin",
        "lipid",
        "metabolism",
    ],
    "mechanism_keywords": [
        "cardiac",
        "channel",
        "conduction",
        "dopamine",
        "gaba",
        "glucose",
        "glutamate",
        "insulin",
        "lipid",
        "metabolism",
    ],
    "reference_drug_ids": [
        "CHEMBL628",
        "CHEMBL628",
        "CHEMBL1421",
        "CHEMBL628",
        "CHEMBL1421",
        "CHEMBL628",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_genetic_generalized_epilepsy_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
