"""beta-hydroxyisovalerate measurement (BETA_HYDROXYISOVALERATE_MEASUREMENT) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'beta-hydroxyisovalerate measurement (BETA_HYDROXYISOVALERATE_MEASUREMENT)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of beta-hydroxyisovalerate measurement
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(beta-hydroxyisovalerate measurement[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(beta-hydroxyisovalerate measurement[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(beta-hydroxyisovalerate measurement[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(beta-hydroxyisovalerate measurement[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'beta-hydroxyisovalerate measurement OR beta-hydroxyisovalerate'
GWAS_SEARCH_TERMS = ['beta-hydroxyisovalerate measurement', 'beta-hydroxyisovalerate']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACOT7": 4.0,
        "ACSM1": 4.0,
        "ACSM2B": 4.0,
        "AUH": 4.0,
        "CCR4": 4.0,
        "CFAP251": 4.0,
        "CTLA4": 4.0,
        "DCUN1D1": 4.0,
        "DIRAS2": 4.0,
        "GLB1": 4.0,
        "GPR153": 4.0,
        "HPD": 4.0,
        "ICOS": 4.0,
        "LAMP3": 4.0,
        "MCCC1": 4.0,
        "MRPL9": 4.0,
        "NFIL3": 4.0,
        "NOL9": 4.0,
        "PLEKHG5": 4.0,
        "PSMD9": 4.0,
        "S100A10": 4.0,
        "SLC22A1": 4.0,
        "SLC22A2": 4.0,
        "SYK": 4.0,
        "THEM4": 4.0,
        "TRIML1": 4.0,
        "VSTM4": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "beta_hydroxyisovalerate_measurement-screening-v1",
    "pathway_keywords": [
        "cell",
        "checkpoint",
        "chemokine",
        "dopamine",
        "immune",
        "mapk",
        "receptor",
        "serotonin",
        "signaling",
    ],
    "mechanism_keywords": [
        "cell",
        "checkpoint",
        "chemokine",
        "dopamine",
        "immune",
        "mapk",
        "receptor",
        "serotonin",
        "signaling",
    ],
    "reference_drug_ids": [
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_beta_hydroxyisovalerate_measurement_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
