"""anthrax infection (ANTHRAX_INFECTION) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "anthrax infection (ANTHRAX_INFECTION)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of anthrax infection
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(anthrax infection[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(anthrax infection[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(anthrax infection[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(anthrax infection[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "anthrax infection OR anthrax"
GWAS_SEARCH_TERMS = ["anthrax infection", "anthrax"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ADA": 4.0,
        "AKT1": 4.0,
        "AMY2A": 4.0,
        "ANTXR1": 4.0,
        "ANTXR2": 4.0,
        "APCS": 4.0,
        "ATR": 4.0,
        "BLOC1S6": 4.0,
        "CALM1": 4.0,
        "CASP1": 4.0,
        "CASP8": 4.0,
        "CAT": 4.0,
        "CD4": 4.0,
        "CHKA": 4.0,
        "CHKB": 4.0,
        "CMPK1": 4.0,
        "CXCL10": 4.0,
        "CXCL11": 4.0,
        "CXCL9": 4.0,
        "EPB42": 4.0,
        "FURIN": 4.0,
        "HSPG2": 4.0,
        "HTN3": 4.0,
        "HTRA1": 4.0,
        "IFNA1": 4.0,
        "IFNG": 4.0,
        "IL1B": 4.0,
        "INHA": 4.0,
        "ITGAX": 4.0,
        "JUN": 4.0,
        "KIF1C": 4.0,
        "LRP6": 4.0,
        "LTA": 4.0,
        "MAP2K1": 4.0,
        "MAP2K2": 4.0,
        "MAP2K3": 4.0,
        "MAP2K4": 4.0,
        "MAP2K6": 4.0,
        "MAP2K7": 4.0,
        "MMP1": 4.0,
        "MMP13": 4.0,
        "MMP7": 4.0,
        "MMP8": 4.0,
        "NLRP3": 4.0,
        "NOS2": 4.0,
        "NR5A1": 4.0,
        "PDCD6IP": 4.0,
        "PON1": 4.0,
        "PRDX1": 4.0,
        "PRH1": 4.0,
        "PRH2": 4.0,
        "PTPRC": 4.0,
        "RPA1": 4.0,
        "SH2D1A": 4.0,
        "SMR3B": 4.0,
        "SOD1": 4.0,
        "SPINT2": 4.0,
        "TLR7": 4.0,
        "TLR9": 4.0,
        "TNF": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "doxycycline",
        "doxycycline anhydrous",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "anthrax_infection-screening-v1",
    "pathway_keywords": [
        "adhesion",
        "apoptosis",
        "cell",
        "chemokine",
        "dopamine",
        "inflammasome",
        "integrin",
        "mapk",
        "mtor",
        "pathway",
    ],
    "mechanism_keywords": [
        "adhesion",
        "apoptosis",
        "cell",
        "chemokine",
        "dopamine",
        "inflammasome",
        "integrin",
        "mapk",
        "mtor",
        "pathway",
    ],
    "reference_drug_ids": [
        "CHEMBL1200699",
        "CHEMBL1200699",
        "CHEMBL1433",
        "CHEMBL1433",
        "CHEMBL1433",
        "CHEMBL1200699",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_anthrax_infection_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
