"""acrorenal syndrome (ACRORENAL_SYNDROME) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "acrorenal syndrome (ACRORENAL_SYNDROME)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Abnormal renal morphology",
    "Autosomal dominant inheritance",
    "Finger aplasia",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(acrorenal syndrome[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(acrorenal syndrome[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(acrorenal syndrome[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(acrorenal syndrome[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "acrorenal syndrome OR acrorenal"
GWAS_SEARCH_TERMS = ["acrorenal syndrome", "acrorenal"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "BPNT2": 4.0,
        "CILK1": 4.0,
        "COL1A1": 4.0,
        "COL2A1": 4.0,
        "CYP51A1": 4.0,
        "DPH1": 4.0,
        "DZIP1L": 4.0,
        "EVX2": 4.0,
        "FBN1": 4.0,
        "FGF9": 4.0,
        "FGFR3": 4.0,
        "FMN1": 4.0,
        "GDF5": 4.0,
        "GLI2": 4.0,
        "GLI3": 4.0,
        "GREM1": 4.0,
        "HOXA11": 4.0,
        "HOXA13": 4.0,
        "HOXD11": 4.0,
        "HOXD12": 4.0,
        "HOXD13": 4.0,
        "IFITM5": 4.0,
        "IFT172": 4.0,
        "IFT80": 4.0,
        "IRF6": 4.0,
        "JAG2": 4.0,
        "LNPK": 4.0,
        "PAPPA2": 4.0,
        "PAX9": 4.0,
        "PBXIP1": 4.0,
        "PHEX": 4.0,
        "PITX1": 4.0,
        "PKDCC": 4.0,
        "PTHLH": 4.0,
        "RECK": 4.0,
        "RFNG": 4.0,
        "ROR2": 4.0,
        "RPL38": 4.0,
        "RSPO2": 4.0,
        "RUNX2": 4.0,
        "SATB2": 4.0,
        "SC5D": 4.0,
        "SCLT1": 4.0,
        "SFRP2": 4.0,
        "SLC29A4": 4.0,
        "SLC30A4": 4.0,
        "SMOC1": 4.0,
        "SOX9": 4.0,
        "TBX2": 4.0,
        "TBX4": 4.0,
        "TMEM216": 4.0,
        "TP63": 4.0,
        "TWIST1": 4.0,
        "VPS33A": 4.0,
        "WDPCP": 4.0,
        "ZBTB16": 4.0,
        "ZNF366": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "acrorenal_syndrome-screening-v1",
    "pathway_keywords": [
        "autophagy",
        "bone",
        "cascade",
        "coagulation",
        "dopamine",
        "hedgehog",
        "interferon",
        "mapk",
        "notch",
        "pathway",
    ],
    "mechanism_keywords": [
        "autophagy",
        "bone",
        "cascade",
        "coagulation",
        "dopamine",
        "hedgehog",
        "interferon",
        "mapk",
        "notch",
        "pathway",
    ],
    "reference_drug_ids": [],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_acrorenal_syndrome_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
