"""ventricular septal defect 2 (VENTRICULAR_SEPTAL_DEFECT_2) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'ventricular septal defect 2 (VENTRICULAR_SEPTAL_DEFECT_2)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of ventricular septal defect 2
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(ventricular septal defect 2[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(ventricular septal defect 2[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(ventricular septal defect 2[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(ventricular septal defect 2[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'ventricular septal defect 2 OR ventricular'
GWAS_SEARCH_TERMS = ['ventricular septal defect 2', 'ventricular']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ARID1B": 4.0,
        "BAZ1B": 4.0,
        "BMPR2": 4.0,
        "CCN1": 4.0,
        "CITED2": 4.0,
        "CYP26B1": 4.0,
        "ECE1": 4.0,
        "EVL": 4.0,
        "FBLN1": 4.0,
        "FGF19": 4.0,
        "FOXC2": 4.0,
        "FOXJ1": 4.0,
        "GJA5": 4.0,
        "GLYR1": 4.0,
        "HECTD1": 4.0,
        "HEY2": 4.0,
        "IMPDH1": 4.0,
        "JMJD6": 4.0,
        "KCTD15": 4.0,
        "KDM1A": 4.0,
        "KLF3": 4.0,
        "MMP21": 4.0,
        "NKX2-5": 4.0,
        "NR1D2": 4.0,
        "PCNT": 4.0,
        "PLXND1": 4.0,
        "POGZ": 4.0,
        "PRDM8": 4.0,
        "PSEN1": 4.0,
        "PTPN11": 4.0,
        "RFX3": 4.0,
        "ROBO1": 4.0,
        "SALL4": 4.0,
        "SHROOM3": 4.0,
        "SMAD6": 4.0,
        "SMARCA4": 4.0,
        "SOX4": 4.0,
        "TBX1": 4.0,
        "TLL1": 4.0,
        "YWHAE": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "bosentan",
        "dexmedetomidine",
        "levosimendan",
        "liothyronine",
        "liothyronine sodium",
        "macitentan",
        "milrinone",
        "nitric oxide",
        "norepinephrine",
        "phenoxybenzamine",
        "sevoflurane",
        "theophylline",
        "topiramate",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "ventricular_septal_defect_2-screening-v1",
    "pathway_keywords": [
        "hepcidin",
        "homeostasis",
        "iron",
        "metabolism",
        "remodeling",
        "signaling",
        "xenobiotic",
    ],
    "mechanism_keywords": [
        "hepcidin",
        "homeostasis",
        "iron",
        "metabolism",
        "remodeling",
        "signaling",
        "xenobiotic",
    ],
    "reference_drug_ids": [
        "CHEMBL1200694",
        "CHEMBL190",
        "CHEMBL220492",
        "CHEMBL1437",
        "CHEMBL220492",
        "CHEMBL220492",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_ventricular_septal_defect_2_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
