"""long QT syndrome 12 (LONG_QT_SYNDROME_12) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'long QT syndrome 12 (LONG_QT_SYNDROME_12)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Prolonged QTc interval",
    "Torsade de pointes",
    "Ventricular fibrillation",
    "Autosomal dominant inheritance",
    "Syncope",
    "Early young adult onset",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(long QT syndrome 12[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(long QT syndrome 12[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(long QT syndrome 12[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(long QT syndrome 12[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'long QT syndrome 12 OR long'
GWAS_SEARCH_TERMS = ['long QT syndrome 12', 'long']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACE": 4.0,
        "AFF2": 4.0,
        "AKAP10": 4.0,
        "AP1S3": 4.0,
        "ARL5A": 4.0,
        "ARRB1": 4.0,
        "CACNA1G": 4.0,
        "CALCA": 4.0,
        "CALCB": 4.0,
        "CALM2": 4.0,
        "CASQ2": 4.0,
        "CHMP2B": 4.0,
        "CMYA5": 4.0,
        "CXADR": 4.0,
        "DSG2": 4.0,
        "FCGR2A": 4.0,
        "FCGR2B": 4.0,
        "FCGR2C": 4.0,
        "FKBP1B": 4.0,
        "GJA1": 4.0,
        "GJA5": 4.0,
        "GJD3": 4.0,
        "GOLGA4": 4.0,
        "HCN1": 4.0,
        "HCN4": 4.0,
        "HNRNPA1": 4.0,
        "HNRNPA1L2": 4.0,
        "HNRNPM": 4.0,
        "IQGAP3": 4.0,
        "IRX3": 4.0,
        "KCNA7": 4.0,
        "KCNE4": 4.0,
        "KCNE5": 4.0,
        "KCNIP2": 4.0,
        "KCNJ3": 4.0,
        "KCNJ5": 4.0,
        "KCNQ1": 4.0,
        "KLHL29": 4.0,
        "LAMTOR3": 4.0,
        "MECP2": 4.0,
        "NDUFA7": 4.0,
        "NKX2-5": 4.0,
        "NOS1AP": 4.0,
        "NOS3": 4.0,
        "NUP155": 4.0,
        "PHACTR4": 4.0,
        "PIERCE2": 4.0,
        "PSORS1C2": 4.0,
        "RBM20": 4.0,
        "RGS6": 4.0,
        "RYR2": 4.0,
        "SCN1A": 4.0,
        "SCN3B": 4.0,
        "SCN5A": 4.0,
        "SLC22A15": 4.0,
        "SNTA1": 4.0,
        "SYNRG": 4.0,
        "TBX3": 4.0,
        "TNFRSF17": 4.0,
        "USP35": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "acadesine",
        "atorvastatin",
        "carvedilol",
        "dipyridamole",
        "dobutamine",
        "ephedrine",
        "fasudil",
        "gemfibrozil",
        "irbesartan",
        "labetalol",
        "losmapimod",
        "lovastatin",
        "mavacamten",
        "metoprolol",
        "midazolam",
        "nadolol",
        "nebivolol",
        "norepinephrine",
        "pentoxifylline",
        "perhexiline",
        "perindopril",
        "phentolamine",
        "phenylephrine",
        "phenylephrine hydrochloride",
        "polythiazide",
        "ranolazine",
        "spirapril",
        "tasosartan",
        "tolazoline",
        "trichlormethiazide",
        "valsartan",
    ],
    "low_risk": [
        "amlodipine",
        "bepridil",
        "cilnidipine",
        "felodipine",
        "isradipine",
        "lercanidipine",
        "levamlodipine",
        "manidipine 6300",
        "metformin",
        "mibefradil",
        "nilvadipine",
        "nitrendipine",
        "suloctidil",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "long_qt_syndrome_12-screening-v1",
    "pathway_keywords": [
        "angiotensin",
        "cardiac",
        "cascade",
        "cell",
        "channel",
        "coagulation",
        "conduction",
        "cycle",
        "mtor",
        "pi3k",
    ],
    "mechanism_keywords": [
        "angiotensin",
        "cardiac",
        "cascade",
        "cell",
        "channel",
        "coagulation",
        "conduction",
        "cycle",
        "mtor",
        "pi3k",
    ],
    "reference_drug_ids": [
        "CHEMBL1054",
        "CHEMBL1200339",
        "CHEMBL1480",
        "CHEMBL1480",
        "CHEMBL1648",
        "CHEMBL2108358",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_long_qt_syndrome_12_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
