"""Neurodevelopmental disorder (AUTOSOMAL_DOMINANT_MICROCEPHALY) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'Neurodevelopmental disorder (AUTOSOMAL_DOMINANT_MICROCEPHALY)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of Neurodevelopmental disorder
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(Neurodevelopmental disorder[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(Neurodevelopmental disorder[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(Neurodevelopmental disorder[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(Neurodevelopmental disorder[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'Neurodevelopmental disorder OR Neurodevelopmental'
GWAS_SEARCH_TERMS = ['Neurodevelopmental disorder', 'Neurodevelopmental']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACSM3": 4.0,
        "ANK2": 4.0,
        "ANKRD11": 4.0,
        "ATP2B1": 4.0,
        "BAP1": 4.0,
        "BAZ2B": 4.0,
        "BRSK2": 4.0,
        "CAMK2D": 4.0,
        "CASK": 4.0,
        "CC2D2A": 4.0,
        "CDC42": 4.0,
        "CHD8": 4.0,
        "DDX3X": 4.0,
        "DHX30": 4.0,
        "DHX34": 4.0,
        "DNAH14": 4.0,
        "DNMT3A": 4.0,
        "DOCK4": 4.0,
        "EIF4A2": 4.0,
        "FOXP4": 4.0,
        "GIGYF1": 4.0,
        "ITSN1": 4.0,
        "JARID2": 4.0,
        "KCNA3": 4.0,
        "KDM5B": 4.0,
        "KMT2E": 4.0,
        "MAST4": 4.0,
        "MED13L": 4.0,
        "NAA15": 4.0,
        "NARS1": 4.0,
        "NSD1": 4.0,
        "PAK1": 4.0,
        "PAX5": 4.0,
        "PIP5K1C": 4.0,
        "POGZ": 4.0,
        "PPP1R3F": 4.0,
        "PSMC3": 4.0,
        "RAB5C": 4.0,
        "SATB1": 4.0,
        "SCN8A": 4.0,
        "SETD1B": 4.0,
        "SETD5": 4.0,
        "SHANK1": 4.0,
        "SPTBN1": 4.0,
        "SRCAP": 4.0,
        "SRRM2": 4.0,
        "TAF8": 4.0,
        "TAOK1": 4.0,
        "TBR1": 4.0,
        "THUMPD1": 4.0,
        "TRA2B": 4.0,
        "TRIP12": 4.0,
        "U2AF2": 4.0,
        "WDFY3": 4.0,
        "WNK3": 4.0,
        "ZEB2": 4.0,
        "ZFHX3": 4.0,
        "ZFHX4": 4.0,
        "ZMYM2": 4.0,
        "ZNF292": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "risperidone",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "autosomal_dominant_microcephaly-screening-v1",
    "pathway_keywords": [
        "cardiac",
        "cascade",
        "channel",
        "coagulation",
        "conduction",
        "dopamine",
        "serotonin",
        "signaling",
    ],
    "mechanism_keywords": [
        "cardiac",
        "cascade",
        "channel",
        "coagulation",
        "conduction",
        "dopamine",
        "serotonin",
        "signaling",
    ],
    "reference_drug_ids": [
        "CHEMBL85",
        "CHEMBL395429",
        "CHEMBL85",
        "CHEMBL85",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_autosomal_dominant_microcephaly_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
