"""vulvar neoplasm (VULVAR_NEOPLASM) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'vulvar neoplasm (VULVAR_NEOPLASM)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of vulvar neoplasm
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(vulvar neoplasm[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(vulvar neoplasm[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(vulvar neoplasm[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(vulvar neoplasm[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'vulvar neoplasm OR vulvar'
GWAS_SEARCH_TERMS = ['vulvar neoplasm', 'vulvar']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ATP7A": 4.0,
        "BRAF": 4.0,
        "CD274": 4.0,
        "CD34": 4.0,
        "CD44": 4.0,
        "CDKN2A": 4.0,
        "CHGA": 4.0,
        "CTNNB1": 4.0,
        "CTNND1": 4.0,
        "CXCL12": 4.0,
        "CXCR4": 4.0,
        "CYRIB": 4.0,
        "DES": 4.0,
        "EGFR": 4.0,
        "ENSG00000288534": 4.0,
        "ESR1": 4.0,
        "ETFA": 4.0,
        "ETV6": 4.0,
        "EWSR1": 4.0,
        "GPC3": 4.0,
        "GSDMB": 4.0,
        "HMGA2": 4.0,
        "ISG20": 4.0,
        "KIT": 4.0,
        "LGALS9": 4.0,
        "MDK": 4.0,
        "MKI67": 4.0,
        "MME": 4.0,
        "MMP2": 4.0,
        "MT-CO2": 4.0,
        "MUC1": 4.0,
        "MUC16": 4.0,
        "MVK": 4.0,
        "NBR1": 4.0,
        "NCAM1": 4.0,
        "NRAS": 4.0,
        "PIK3CA": 4.0,
        "PIK3CB": 4.0,
        "PIK3CD": 4.0,
        "PIK3CG": 4.0,
        "PLAU": 4.0,
        "PLAUR": 4.0,
        "POU5F1": 4.0,
        "PRAP1": 4.0,
        "PTEN": 4.0,
        "S100A1": 4.0,
        "S100B": 4.0,
        "SALL4": 4.0,
        "SERPINB3": 4.0,
        "SLC22A3": 4.0,
        "SMARCA4": 4.0,
        "SMARCB1": 4.0,
        "SOX10": 4.0,
        "TERT": 4.0,
        "TGFB1": 4.0,
        "TP53": 4.0,
        "TRPS1": 4.0,
        "VEGFA": 4.0,
        "VIM": 4.0,
        "WEE1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "durvalumab",
        "tremelimumab",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "vulvar_neoplasm-screening-v1",
    "pathway_keywords": [
        "cell",
        "checkpoint",
        "chemokine",
        "cycle",
        "immune",
        "mapk",
        "mast",
        "mtor",
        "pi3k",
        "receptor",
    ],
    "mechanism_keywords": [
        "cell",
        "checkpoint",
        "chemokine",
        "cycle",
        "immune",
        "mapk",
        "mast",
        "mtor",
        "pi3k",
        "receptor",
    ],
    "reference_drug_ids": [
        "CHEMBL2108658",
        "CHEMBL3301587",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_vulvar_neoplasm_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
