"""fibrous dysplasia (FIBROUS_DYSPLASIA) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "fibrous dysplasia (FIBROUS_DYSPLASIA)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Pseudoarthrosis",
    "Autosomal dominant inheritance",
    "Pectus excavatum",
    "Pathologic fracture",
    "Congenital onset",
    "Fibular hypoplasia",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(fibrous dysplasia[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(fibrous dysplasia[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(fibrous dysplasia[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(fibrous dysplasia[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "fibrous dysplasia OR fibrous"
GWAS_SEARCH_TERMS = ["fibrous dysplasia", "fibrous"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ALPP": 4.0,
        "ANO5": 4.0,
        "ASRGL1": 4.0,
        "ATRNL1": 4.0,
        "CASR": 4.0,
        "CCL27": 4.0,
        "COL1A1": 4.0,
        "COL1A2": 4.0,
        "COL2A1": 4.0,
        "CSF1": 4.0,
        "CXXC5": 4.0,
        "CYP27B1": 4.0,
        "DMP1": 4.0,
        "EVC": 4.0,
        "FAM20C": 4.0,
        "FDPS": 4.0,
        "FGF23": 4.0,
        "FGF9": 4.0,
        "FGFR2": 4.0,
        "FGFR3": 4.0,
        "FLNB": 4.0,
        "FOS": 4.0,
        "FSHR": 4.0,
        "GLI2": 4.0,
        "GLI3": 4.0,
        "GLS2": 4.0,
        "GNAS": 4.0,
        "IBSP": 4.0,
        "IFITM5": 4.0,
        "IL6R": 4.0,
        "IL6ST": 4.0,
        "LRRK1": 4.0,
        "MET": 4.0,
        "NABP2": 4.0,
        "NAT10": 4.0,
        "OSTM1": 4.0,
        "PDLIM3": 4.0,
        "PHEX": 4.0,
        "PHOSPHO1": 4.0,
        "POSTN": 4.0,
        "PPIB": 4.0,
        "ROR2": 4.0,
        "RUNX3": 4.0,
        "SCUBE3": 4.0,
        "SLC10A7": 4.0,
        "SLC39A13": 4.0,
        "SLPI": 4.0,
        "SMPD3": 4.0,
        "SNX10": 4.0,
        "SOX9": 4.0,
        "SUCO": 4.0,
        "TCIRG1": 4.0,
        "TENT5A": 4.0,
        "THRA": 4.0,
        "THRB": 4.0,
        "TNFSF11": 4.0,
        "WDR19": 4.0,
        "WWOX": 4.0,
        "ZEB1": 4.0,
        "ZMPSTE24": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "burosumab",
        "denosumab",
        "risedronic acid",
        "tocilizumab",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "fibrous_dysplasia-screening-v1",
    "pathway_keywords": [
        "autophagy",
        "bone",
        "cascade",
        "chemokine",
        "coagulation",
        "dopamine",
        "hedgehog",
        "mapk",
        "remodeling",
        "repair",
    ],
    "mechanism_keywords": [
        "autophagy",
        "bone",
        "cascade",
        "chemokine",
        "coagulation",
        "dopamine",
        "hedgehog",
        "mapk",
        "remodeling",
        "repair",
    ],
    "reference_drug_ids": [
        "CHEMBL923",
        "CHEMBL1237022",
        "CHEMBL3707326",
        "CHEMBL1237023",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_fibrous_dysplasia_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
