"""atypical hemolytic-uremic syndrome (ATYPICAL_HEMOLYTIC_UREMIC_SYNDROME) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'atypical hemolytic-uremic syndrome (ATYPICAL_HEMOLYTIC_UREMIC_SYNDROME)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of atypical hemolytic-uremic syndrome
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(atypical hemolytic-uremic syndrome[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(atypical hemolytic-uremic syndrome[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(atypical hemolytic-uremic syndrome[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(atypical hemolytic-uremic syndrome[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'atypical hemolytic-uremic syndrome OR atypical'
GWAS_SEARCH_TERMS = ['atypical hemolytic-uremic syndrome', 'atypical']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ADAMTS13": 4.0,
        "ADD1": 4.0,
        "AIM2": 4.0,
        "B4GALT1": 4.0,
        "C1GALT1": 4.0,
        "C1GALT1C1": 4.0,
        "C3": 4.0,
        "C3AR1": 4.0,
        "C5": 4.0,
        "C5AR1": 4.0,
        "CD46": 4.0,
        "CD59": 4.0,
        "CEP290": 4.0,
        "CFB": 4.0,
        "CFH": 4.0,
        "CFHR1": 4.0,
        "CFHR3": 4.0,
        "CFHR5": 4.0,
        "CFI": 4.0,
        "CLCN5": 4.0,
        "COL4A1": 4.0,
        "COL4A4": 4.0,
        "COL4A5": 4.0,
        "DGKE": 4.0,
        "EPB41": 4.0,
        "GATA1": 4.0,
        "HBB": 4.0,
        "HK1": 4.0,
        "HLA-DQB1": 4.0,
        "HLA-DQB2": 4.0,
        "KCTD1": 4.0,
        "LDHA": 4.0,
        "LYN": 4.0,
        "MAN2A1": 4.0,
        "MAS1": 4.0,
        "MASP2": 4.0,
        "MMACHC": 4.0,
        "MYH9": 4.0,
        "MYO1E": 4.0,
        "NPHP3": 4.0,
        "PDGFRB": 4.0,
        "PLG": 4.0,
        "PRKAB1": 4.0,
        "PRKAG1": 4.0,
        "PTPRC": 4.0,
        "RASA3": 4.0,
        "RXFP4": 4.0,
        "SLFN14": 4.0,
        "SMAP1": 4.0,
        "SMARCAL1": 4.0,
        "SPTA1": 4.0,
        "THBD": 4.0,
        "TMEM67": 4.0,
        "TNFAIP2": 4.0,
        "TPCN1": 4.0,
        "TPI1": 4.0,
        "TSPAN33": 4.0,
        "UMOD": 4.0,
        "WAS": 4.0,
        "WHAMM": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "avacopan",
        "crovalimab",
        "eculizumab",
        "iptacopan",
        "narsoplimab",
        "ravulizumab",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "atypical_hemolytic_uremic_syndrome-screening-v1",
    "pathway_keywords": [
        "cascade",
        "cell",
        "complement",
        "dopamine",
        "mapk",
        "receptor",
        "remodeling",
        "serotonin",
        "signaling",
    ],
    "mechanism_keywords": [
        "cascade",
        "cell",
        "complement",
        "dopamine",
        "mapk",
        "receptor",
        "remodeling",
        "serotonin",
        "signaling",
    ],
    "reference_drug_ids": [
        "CHEMBL1201828",
        "CHEMBL1201828",
        "CHEMBL3989871",
        "CHEMBL3989986",
        "CHEMBL1201828",
        "CHEMBL4594448",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_atypical_hemolytic_uremic_syndrome_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
