"""suntan (SUNTAN) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'suntan (SUNTAN)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of suntan
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(suntan[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(suntan[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(suntan[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(suntan[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'suntan OR suntan'
GWAS_SEARCH_TERMS = ['suntan', 'suntan']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ATP11A": 4.0,
        "BNC2": 4.0,
        "CPNE7": 4.0,
        "CTU2": 4.0,
        "DBNDD1": 4.0,
        "DCT": 4.0,
        "EIF2S2": 4.0,
        "EMX2": 4.0,
        "EXOC2": 4.0,
        "GAS8": 4.0,
        "GNAL": 4.0,
        "HERC2": 4.0,
        "IL17C": 4.0,
        "IRF4": 4.0,
        "KIAA0930": 4.0,
        "KITLG": 4.0,
        "LURAP1L": 4.0,
        "MC1R": 4.0,
        "MCF2L": 4.0,
        "NUP50": 4.0,
        "OCA2": 4.0,
        "PDE4B": 4.0,
        "PPARGC1B": 4.0,
        "PRDM7": 4.0,
        "RAB11FIP2": 4.0,
        "RALY": 4.0,
        "RNF166": 4.0,
        "RXFP3": 4.0,
        "SGIP1": 4.0,
        "SLC24A4": 4.0,
        "SLC35G4": 4.0,
        "SLC45A2": 4.0,
        "TPCN2": 4.0,
        "TRPS1": 4.0,
        "TUBB3": 4.0,
        "TYR": 4.0,
        "TYRP1": 4.0,
        "ZNF276": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "suntan-screening-v1",
    "pathway_keywords": [
        "autophagy",
        "cascade",
        "cell",
        "coagulation",
        "inflammasome",
        "interferon",
        "lipid",
        "mast",
        "metabolism",
        "pathway",
    ],
    "mechanism_keywords": [
        "autophagy",
        "cascade",
        "cell",
        "coagulation",
        "inflammasome",
        "interferon",
        "lipid",
        "mast",
        "metabolism",
        "pathway",
    ],
    "reference_drug_ids": [
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_suntan_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
