"""cardiomyopathy, dilated, 2H (CARDIOMYOPATHY_DILATED_2H) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "cardiomyopathy, dilated, 2H (CARDIOMYOPATHY_DILATED_2H)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Reduced left ventricular ejection fraction",
    "Feeding difficulties",
    "Tachypnea",
    "Neonatal death",
    "Neonatal onset",
    "Muscular ventricular septal defect",
    "Autosomal recessive inheritance",
    "Secundum atrial septal defect",
    "Cardiorespiratory arrest",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(cardiomyopathy, dilated, 2H[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(cardiomyopathy, dilated, 2H[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(cardiomyopathy, dilated, 2H[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(cardiomyopathy, dilated, 2H[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "cardiomyopathy, dilated, 2H OR cardiomyopathy,"
GWAS_SEARCH_TERMS = ["cardiomyopathy, dilated, 2H", "cardiomyopathy,"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABL1": 4.0,
        "ACKR3": 4.0,
        "ADAM19": 4.0,
        "BAZ1B": 4.0,
        "BMP10": 4.0,
        "CARM1": 4.0,
        "CCN1": 4.0,
        "CHD4": 4.0,
        "DNAH11": 4.0,
        "DSCAM": 4.0,
        "FBLN1": 4.0,
        "FGF19": 4.0,
        "FKBP1A": 4.0,
        "FKBP1C": 4.0,
        "FOXJ1": 4.0,
        "FOXP1": 4.0,
        "GATA4": 4.0,
        "GET3": 4.0,
        "GJA1": 4.0,
        "GJA5": 4.0,
        "GLYR1": 4.0,
        "GYS1": 4.0,
        "HDAC2": 4.0,
        "HEG1": 4.0,
        "HEXIM1": 4.0,
        "HEY2": 4.0,
        "HIC2": 4.0,
        "JARID2": 4.0,
        "KLF3": 4.0,
        "MOSPD3": 4.0,
        "MYH10": 4.0,
        "NFATC1": 4.0,
        "NIPBL": 4.0,
        "NKX2-5": 4.0,
        "NR1D2": 4.0,
        "NSD2": 4.0,
        "NTF3": 4.0,
        "OTUD6B": 4.0,
        "PBX3": 4.0,
        "PDPN": 4.0,
        "PHOX2B": 4.0,
        "PLXND1": 4.0,
        "RBPMS": 4.0,
        "RNF4": 4.0,
        "RXRA": 4.0,
        "SALL4": 4.0,
        "SHROOM3": 4.0,
        "SMAD6": 4.0,
        "SMARCA4": 4.0,
        "SOX6": 4.0,
        "SRSF10": 4.0,
        "TBX3": 4.0,
        "TBX5": 4.0,
        "TIE1": 4.0,
        "TLL1": 4.0,
        "TLX3": 4.0,
        "VCAN": 4.0,
        "YWHAE": 4.0,
        "ZFPM2": 4.0,
        "ZSWIM8": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "arry-797",
        "candesartan",
        "carvedilol",
        "danicamtiv",
        "dapagliflozin",
        "dapagliflozin propanediol",
        "enalaprilat",
        "enalaprilat anhydrous",
        "perindopril",
        "ramipril",
        "ranolazine",
        "rosuvastatin",
        "simvastatin",
        "spironolactone",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "cardiomyopathy_dilated_2h-screening-v1",
    "pathway_keywords": [
        "cascade",
        "chemokine",
        "coagulation",
        "hepcidin",
        "homeostasis",
        "iron",
        "pathway",
        "remodeling",
        "signaling",
    ],
    "mechanism_keywords": [
        "cascade",
        "chemokine",
        "coagulation",
        "hepcidin",
        "homeostasis",
        "iron",
        "pathway",
        "remodeling",
        "signaling",
    ],
    "reference_drug_ids": [
        "CHEMBL1404",
        "CHEMBL1088750",
        "CHEMBL723",
        "CHEMBL1404",
        "CHEMBL4594304",
        "CHEMBL1393",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_cardiomyopathy_dilated_2h_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
