"""docosahexaenoic acid to total fatty acids percentage  (DOCOSAHEXAENOIC_ACID_TO_TOTAL_FATTY_ACIDS_PERCENTAGE) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "docosahexaenoic acid to total fatty acids percentage  (DOCOSAHEXAENOIC_ACID_TO_TOTAL_FATTY_ACIDS_PERCENTAGE)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of docosahexaenoic acid to total fatty acids percentage
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(docosahexaenoic acid to total fatty acids percentage [Title/Abstract]) AND (treatment[Title/Abstract])",
    "(docosahexaenoic acid to total fatty acids percentage [Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(docosahexaenoic acid to total fatty acids percentage [Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(docosahexaenoic acid to total fatty acids percentage [Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "docosahexaenoic acid to total fatty acids percentage  OR docosahexaenoic"
GWAS_SEARCH_TERMS = ["docosahexaenoic acid to total fatty acids percentage ", "docosahexaenoic"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AGPAT4": 4.0,
        "APOA1": 4.0,
        "APOA5": 4.0,
        "APOB": 4.0,
        "APOC1": 4.0,
        "APOC3": 4.0,
        "APOE": 4.0,
        "BFAR": 4.0,
        "BMERB1": 4.0,
        "BUD13": 4.0,
        "CPT1A": 4.0,
        "CRHR1": 4.0,
        "DEFB134": 4.0,
        "DEFB135": 4.0,
        "DEFB136": 4.0,
        "DGAT2": 4.0,
        "FADS1": 4.0,
        "FADS2": 4.0,
        "FADS3": 4.0,
        "FGF21": 4.0,
        "FTO": 4.0,
        "GALNT2": 4.0,
        "GCKR": 4.0,
        "IGHMBP2": 4.0,
        "JMJD1C": 4.0,
        "LIPC": 4.0,
        "LPA": 4.0,
        "LPL": 4.0,
        "MAU2": 4.0,
        "MFHAS1": 4.0,
        "MOGAT2": 4.0,
        "MRGPRD": 4.0,
        "MSRA": 4.0,
        "NOMO1": 4.0,
        "NPIPA1": 4.0,
        "NPIPA5": 4.0,
        "NSF": 4.0,
        "NTAN1": 4.0,
        "PAFAH1B2": 4.0,
        "PARN": 4.0,
        "PDXDC1": 4.0,
        "PGA5": 4.0,
        "PNPLA3": 4.0,
        "PPP1R3B": 4.0,
        "PRKN": 4.0,
        "RASIP1": 4.0,
        "RPGRIP1L": 4.0,
        "SAMM50": 4.0,
        "SCGB1A1": 4.0,
        "SLC18A1": 4.0,
        "SLC22A1": 4.0,
        "SLC22A3": 4.0,
        "SLC22A4": 4.0,
        "SLC22A5": 4.0,
        "SPPL2C": 4.0,
        "TM6SF2": 4.0,
        "TOMM40": 4.0,
        "TRIB1": 4.0,
        "XKR6": 4.0,
        "ZPR1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "docosahexaenoic_acid_to_total_fatty_acids_percentage-screening-v1",
    "pathway_keywords": [
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "glucose",
        "insulin",
        "lipid",
        "mapk",
        "mast",
        "metabolism",
    ],
    "mechanism_keywords": [
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "glucose",
        "insulin",
        "lipid",
        "mapk",
        "mast",
        "metabolism",
    ],
    "reference_drug_ids": [],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_docosahexaenoic_acid_to_total_fatty_acids_percentage_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
