"""galactosemia (GALACTOSEMIA) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "galactosemia (GALACTOSEMIA)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of galactosemia
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(galactosemia[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(galactosemia[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(galactosemia[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(galactosemia[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "galactosemia OR galactosemia"
GWAS_SEARCH_TERMS = ["galactosemia", "galactosemia"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABCB4": 4.0,
        "ABCC12": 4.0,
        "ABCC2": 4.0,
        "ABCD1": 4.0,
        "ACHE": 4.0,
        "ADCY10": 4.0,
        "AGA": 4.0,
        "AGAP1": 4.0,
        "AKR1B1": 4.0,
        "ALB": 4.0,
        "AMH": 4.0,
        "APOA1": 4.0,
        "AR": 4.0,
        "ARF3": 4.0,
        "ART4": 4.0,
        "ATP8B1": 4.0,
        "BCAR1": 4.0,
        "BCAR3": 4.0,
        "BMP15": 4.0,
        "BMP4": 4.0,
        "BRD2": 4.0,
        "BTD": 4.0,
        "CASP1": 4.0,
        "CASP3": 4.0,
        "CLCN5": 4.0,
        "COL4A1": 4.0,
        "COL4A2": 4.0,
        "CRYAA": 4.0,
        "CRYBB2": 4.0,
        "CRYGA": 4.0,
        "CRYGC": 4.0,
        "CRYGD": 4.0,
        "CSE1L": 4.0,
        "CTNND1": 4.0,
        "CYB561A3": 4.0,
        "DUOX2": 4.0,
        "DUOXA2": 4.0,
        "EIF2A": 4.0,
        "EIF3F": 4.0,
        "ENSG00000288534": 4.0,
        "FGF9": 4.0,
        "FMO5": 4.0,
        "FOXC1": 4.0,
        "FOXE3": 4.0,
        "G6PD": 4.0,
        "GAL": 4.0,
        "GALE": 4.0,
        "GALK1": 4.0,
        "GALM": 4.0,
        "GALT": 4.0,
        "GDF9": 4.0,
        "GJA3": 4.0,
        "GJA8": 4.0,
        "GJE1": 4.0,
        "GLB1": 4.0,
        "GNG12": 4.0,
        "GSTM1": 4.0,
        "HNF1A": 4.0,
        "HNF4A": 4.0,
        "HSF4": 4.0,
        "IGBP1": 4.0,
        "IGF1": 4.0,
        "IL11": 4.0,
        "IL11RA": 4.0,
        "IL1B": 4.0,
        "INS": 4.0,
        "INTS15": 4.0,
        "ITGB4": 4.0,
        "LCT": 4.0,
        "LEP": 4.0,
        "LEPR": 4.0,
        "LGALS1": 4.0,
        "LGALS7": 4.0,
        "LGALS7B": 4.0,
        "LGR4": 4.0,
        "LIM2": 4.0,
        "LMX1B": 4.0,
        "ME2": 4.0,
        "MIP": 4.0,
        "MKI67": 4.0,
        "MSX2": 4.0,
        "MTOR": 4.0,
        "NHS": 4.0,
        "NOS2": 4.0,
        "NR3C1": 4.0,
        "OTC": 4.0,
        "PAPPA": 4.0,
        "PAX6": 4.0,
        "PKHD1": 4.0,
        "PON1": 4.0,
        "PPIP5K2": 4.0,
        "PRKCA": 4.0,
        "PRKCB": 4.0,
        "PRKCG": 4.0,
        "PRRT2": 4.0,
        "PXDN": 4.0,
        "SARNP": 4.0,
        "SELENOF": 4.0,
        "SERPINA1": 4.0,
        "SGO1": 4.0,
        "SIPA1L3": 4.0,
        "SLC25A13": 4.0,
        "SLC2A2": 4.0,
        "SLC4A11": 4.0,
        "SOX17": 4.0,
        "SPRYD3": 4.0,
        "SREBF2": 4.0,
        "TDRD7": 4.0,
        "TF": 4.0,
        "TRPM3": 4.0,
        "TSHR": 4.0,
        "UGT8": 4.0,
        "UMOD": 4.0,
        "VEGFA": 4.0,
        "VIP": 4.0,
        "YAE1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "ama0076",
        "batoclimab",
        "cyclosporine",
        "dexamethasone",
        "govorestat",
        "hydrocodone",
        "lifitegrast",
        "mapracorat",
        "phenylephrine",
        "satralizumab",
        "sirolimus",
        "tropicamide",
        "varenicline",
    ],
    "low_risk": [
        "teprotumumab",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "galactosemia-screening-v1",
    "pathway_keywords": [
        "angiogenesis",
        "apoptosis",
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "glucose",
        "hepcidin",
        "homeostasis",
        "hormone",
    ],
    "mechanism_keywords": [
        "angiogenesis",
        "apoptosis",
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "glucose",
        "hepcidin",
        "homeostasis",
        "hormone",
    ],
    "reference_drug_ids": [
        "CHEMBL1215",
        "CHEMBL2095222",
        "CHEMBL2095222",
        "CHEMBL2095222",
        "CHEMBL1457",
        "CHEMBL2095222",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_galactosemia_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
