"""Spinocerebellar ataxia type 42 (SPINOCEREBELLAR_ATAXIA_TYPE_42) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "Spinocerebellar ataxia type 42 (SPINOCEREBELLAR_ATAXIA_TYPE_42)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Diplopia",
    "Abnormal pyramidal sign",
    "Autosomal dominant inheritance",
    "Tremor",
    "Spastic ataxia",
    "Eyelid myokymia",
    "Loss of Purkinje cells in the cerebellar vermis",
    "Impaired vibration sensation at ankles",
    "Unsteady gait",
    "Dysarthria",
    "Dysphagia",
    "Slowly progressive",
    "Spastic gait",
    "Cerebellar atrophy",
    "Hyperreflexia",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(Spinocerebellar ataxia type 42[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(Spinocerebellar ataxia type 42[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(Spinocerebellar ataxia type 42[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(Spinocerebellar ataxia type 42[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "Spinocerebellar ataxia type 42 OR Spinocerebellar"
GWAS_SEARCH_TERMS = ["Spinocerebellar ataxia type 42", "Spinocerebellar"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AGA": 4.0,
        "ANK3": 4.0,
        "ANKFY1": 4.0,
        "ASPA": 4.0,
        "ATP2B2": 4.0,
        "ATXN7": 4.0,
        "BORCS7": 4.0,
        "BORCS7-ASMT": 4.0,
        "CA8": 4.0,
        "CACNA1A": 4.0,
        "CACNA1G": 4.0,
        "CERS1": 4.0,
        "CHP1": 4.0,
        "CLP1": 4.0,
        "CNTNAP1": 4.0,
        "EN1": 4.0,
        "FBXO41": 4.0,
        "FUCA1": 4.0,
        "GDF1": 4.0,
        "GLRA1": 4.0,
        "GRID2": 4.0,
        "GRM1": 4.0,
        "HPRT1": 4.0,
        "INPP4A": 4.0,
        "IREB2": 4.0,
        "KCNJ6": 4.0,
        "KCNMA1": 4.0,
        "KCNN2": 4.0,
        "LMX1A": 4.0,
        "MYH10": 4.0,
        "MYO5A": 4.0,
        "NEUROD4": 4.0,
        "NPC1": 4.0,
        "PI4K2A": 4.0,
        "PLCB4": 4.0,
        "PMP22": 4.0,
        "PRKCG": 4.0,
        "PRNP": 4.0,
        "PSAP": 4.0,
        "RELN": 4.0,
        "RORA": 4.0,
        "RREB1": 4.0,
        "SCN8A": 4.0,
        "SKOR2": 4.0,
        "SLC6A1": 4.0,
        "SPTBN2": 4.0,
        "SPTBN4": 4.0,
        "SRRM3": 4.0,
        "STARD9": 4.0,
        "STUB1": 4.0,
        "SUN1": 4.0,
        "TMEM176B": 4.0,
        "TOR1A": 4.0,
        "TPP1": 4.0,
        "TUBB4A": 4.0,
        "UNC5C": 4.0,
        "WNT1": 4.0,
        "ZFYVE26": 4.0,
        "ZIC1": 4.0,
        "ZNF423": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "spinocerebellar_ataxia_type_42-screening-v1",
    "pathway_keywords": [
        "bone",
        "cardiac",
        "channel",
        "conduction",
        "gaba",
        "glutamate",
        "interferon",
        "pathway",
        "remodeling",
        "signaling",
    ],
    "mechanism_keywords": [
        "bone",
        "cardiac",
        "channel",
        "conduction",
        "gaba",
        "glutamate",
        "interferon",
        "pathway",
        "remodeling",
        "signaling",
    ],
    "reference_drug_ids": [
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_spinocerebellar_ataxia_type_42_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
