"""X-linked intellectual disability-ataxia-apraxia syndrome (X_LINKED_INTELLECTUAL_DISABILITY_ATAXIA_APRAXIA_SYNDROME) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "X-linked intellectual disability-ataxia-apraxia syndrome (X_LINKED_INTELLECTUAL_DISABILITY_ATAXIA_APRAXIA_SYNDROME)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of X-linked intellectual disability-ataxia-apraxia syndrome
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(X-linked intellectual disability-ataxia-apraxia syndrome[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(X-linked intellectual disability-ataxia-apraxia syndrome[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(X-linked intellectual disability-ataxia-apraxia syndrome[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(X-linked intellectual disability-ataxia-apraxia syndrome[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "X-linked intellectual disability-ataxia-apraxia syndrome OR X-linked"
GWAS_SEARCH_TERMS = ["X-linked intellectual disability-ataxia-apraxia syndrome", "X-linked"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AGTPBP1": 4.0,
        "ATCAY": 4.0,
        "CACNA1A": 4.0,
        "CACNA2D2": 4.0,
        "CNTNAP1": 4.0,
        "DAB1": 4.0,
        "DNM1": 4.0,
        "DST": 4.0,
        "EFNB3": 4.0,
        "ETV1": 4.0,
        "GALC": 4.0,
        "GLRA1": 4.0,
        "GRID2": 4.0,
        "HCN2": 4.0,
        "KCNA1": 4.0,
        "KCNV1": 4.0,
        "MTMR9": 4.0,
        "MYO5A": 4.0,
        "NAPB": 4.0,
        "PRNP": 4.0,
        "PSAP": 4.0,
        "ROBO3": 4.0,
        "RREB1": 4.0,
        "SCN1A": 4.0,
        "SCN1B": 4.0,
        "SCN8A": 4.0,
        "SLC2A1": 4.0,
        "SLC9A1": 4.0,
        "SMOC1": 4.0,
        "SULT4A1": 4.0,
        "SYT2": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "dextromethorphan",
        "pimavanserin",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "x_linked_intellectual_disability_ataxia_apraxia_syndrome-screening-v1",
    "pathway_keywords": [
        "angiotensin",
        "cardiac",
        "channel",
        "conduction",
        "glucose",
        "hedgehog",
        "insulin",
        "metabolism",
        "renin",
        "secretion",
    ],
    "mechanism_keywords": [
        "angiotensin",
        "cardiac",
        "channel",
        "conduction",
        "glucose",
        "hedgehog",
        "insulin",
        "metabolism",
        "renin",
        "secretion",
    ],
    "reference_drug_ids": [
        "CHEMBL52440",
        "CHEMBL2111101",
        "CHEMBL52440",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_x_linked_intellectual_disability_ataxia_apraxia_syndrome_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
