"""mucopolysaccharidosis type 6 (MUCOPOLYSACCHARIDOSIS_TYPE_6) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "mucopolysaccharidosis type 6 (MUCOPOLYSACCHARIDOSIS_TYPE_6)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Tricuspid regurgitation",
    "Mitral stenosis",
    "Thickened skin",
    "Avascular necrosis",
    "Restrictive ventilatory defect",
    "Carious teeth",
    "Sinus tachycardia",
    "Intellectual disability",
    "Dermatan sulfate excretion in urine",
    "Reduced leukocyte arylsulfatase B activity",
    "Splenomegaly",
    "Hearing impairment",
    "Epiphyseal dysplasia",
    "Glaucoma",
    "Hepatomegaly",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(mucopolysaccharidosis type 6[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(mucopolysaccharidosis type 6[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(mucopolysaccharidosis type 6[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(mucopolysaccharidosis type 6[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "mucopolysaccharidosis type 6 OR mucopolysaccharidosis"
GWAS_SEARCH_TERMS = ["mucopolysaccharidosis type 6", "mucopolysaccharidosis"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ARSB": 4.0,
        "BMP5": 4.0,
        "CACNA1S": 4.0,
        "CCN2": 4.0,
        "CD34": 4.0,
        "CERT1": 4.0,
        "CHUK": 4.0,
        "CILK1": 4.0,
        "COL10A1": 4.0,
        "COL1A1": 4.0,
        "CPLANE1": 4.0,
        "DMRT2": 4.0,
        "ENPP1": 4.0,
        "EVC": 4.0,
        "FBN2": 4.0,
        "FGF20": 4.0,
        "FGF9": 4.0,
        "FGFR3": 4.0,
        "FGFRL1": 4.0,
        "FLNB": 4.0,
        "FOXC1": 4.0,
        "FSTL1": 4.0,
        "GHR": 4.0,
        "GLI2": 4.0,
        "GLI3": 4.0,
        "GSC": 4.0,
        "GUSB": 4.0,
        "HOXC10": 4.0,
        "HSPG2": 4.0,
        "IDUA": 4.0,
        "IFT140": 4.0,
        "KL": 4.0,
        "LRP6": 4.0,
        "MARVELD3": 4.0,
        "NABP2": 4.0,
        "NPR2": 4.0,
        "NPR3": 4.0,
        "PCSK5": 4.0,
        "PDGFRA": 4.0,
        "PDS5B": 4.0,
        "PHOSPHO1": 4.0,
        "PPP1CB": 4.0,
        "PTHLH": 4.0,
        "RAI1": 4.0,
        "ROR2": 4.0,
        "RPL38": 4.0,
        "SH3PXD2B": 4.0,
        "SLC35A3": 4.0,
        "SOX11": 4.0,
        "SULF1": 4.0,
        "SULF2": 4.0,
        "TENT5A": 4.0,
        "TGFB2": 4.0,
        "TNF": 4.0,
        "TREX1": 4.0,
        "VANGL2": 4.0,
        "WBP11": 4.0,
        "WDR19": 4.0,
        "ZBTB16": 4.0,
        "ZEB1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
        "adalimumab",
    ],
    "moderate_risk": [],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "mucopolysaccharidosis_type_6-screening-v1",
    "pathway_keywords": [
        "autophagy",
        "cardiac",
        "cascade",
        "cell",
        "channel",
        "coagulation",
        "conduction",
        "dopamine",
        "hedgehog",
        "hepcidin",
    ],
    "mechanism_keywords": [
        "autophagy",
        "cardiac",
        "cascade",
        "cell",
        "channel",
        "coagulation",
        "conduction",
        "dopamine",
        "hedgehog",
        "hepcidin",
    ],
    "reference_drug_ids": [
        "CHEMBL1201580",
        "CHEMBL1201621",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_mucopolysaccharidosis_type_6_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
