"""Haim-Munk syndrome (HAIM_MUNK_SYNDROME) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "Haim-Munk syndrome (HAIM_MUNK_SYNDROME)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Congenital palmoplantar hyperkeratosis",
    "Osteolytic defects of the phalanges of the hand",
    "Tapering pointed ends of distal finger phalanges",
    "Autosomal recessive inheritance",
    "Recurrent bacterial skin infections",
    "Severe periodontitis",
    "Pes planus",
    "Arachnodactyly",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(Haim-Munk syndrome[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(Haim-Munk syndrome[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(Haim-Munk syndrome[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(Haim-Munk syndrome[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "Haim-Munk syndrome OR Haim-Munk"
GWAS_SEARCH_TERMS = ["Haim-Munk syndrome", "Haim-Munk"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACAN": 4.0,
        "AGRN": 4.0,
        "ALB": 4.0,
        "ATP1A2": 4.0,
        "CACNA1A": 4.0,
        "CACNA1I": 4.0,
        "CCL17": 4.0,
        "CCL2": 4.0,
        "CCL22": 4.0,
        "CCR4": 4.0,
        "CD4": 4.0,
        "CD40LG": 4.0,
        "CD8A": 4.0,
        "CDKN1C": 4.0,
        "CDKN2A": 4.0,
        "CDKN2B": 4.0,
        "CGA": 4.0,
        "CGB5": 4.0,
        "COL1A1": 4.0,
        "CORO1A": 4.0,
        "CTSC": 4.0,
        "DDX21": 4.0,
        "DDX41": 4.0,
        "DNMT3A": 4.0,
        "ERG": 4.0,
        "ETV6": 4.0,
        "GATA2": 4.0,
        "GLRA2": 4.0,
        "GSDMB": 4.0,
        "HSPA5": 4.0,
        "IFNG": 4.0,
        "IGF1": 4.0,
        "IL10": 4.0,
        "ITPR1": 4.0,
        "JAK2": 4.0,
        "MPO": 4.0,
        "NFKB1": 4.0,
        "NLRP7": 4.0,
        "NOS2": 4.0,
        "PCDHA10": 4.0,
        "PDE4B": 4.0,
        "PLG": 4.0,
        "POLE": 4.0,
        "PPEF2": 4.0,
        "PPP1R13L": 4.0,
        "PRRT2": 4.0,
        "RB1": 4.0,
        "RHCE": 4.0,
        "RHD": 4.0,
        "RUNX1": 4.0,
        "SLC39A5": 4.0,
        "TF": 4.0,
        "TNF": 4.0,
        "TNFRSF21": 4.0,
        "TP53": 4.0,
        "VDR": 4.0,
        "VEGFD": 4.0,
        "YAP1": 4.0,
        "ZNF469": 4.0,
        "ZNF644": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "haim_munk_syndrome-screening-v1",
    "pathway_keywords": [
        "autophagy",
        "cardiac",
        "cascade",
        "cell",
        "channel",
        "chemokine",
        "coagulation",
        "conduction",
        "cycle",
        "inflammasome",
    ],
    "mechanism_keywords": [
        "autophagy",
        "cardiac",
        "cascade",
        "cell",
        "channel",
        "chemokine",
        "coagulation",
        "conduction",
        "cycle",
        "inflammasome",
    ],
    "reference_drug_ids": [
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_haim_munk_syndrome_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
