"""severe combined immunodeficiency (SEVERE_COMBINED_IMMUNODEFICIENCY) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "severe combined immunodeficiency (SEVERE_COMBINED_IMMUNODEFICIENCY)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of severe combined immunodeficiency
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(severe combined immunodeficiency[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(severe combined immunodeficiency[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(severe combined immunodeficiency[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(severe combined immunodeficiency[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "severe combined immunodeficiency OR severe"
GWAS_SEARCH_TERMS = ["severe combined immunodeficiency", "severe"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ADA": 4.0,
        "AK2": 4.0,
        "ATN1": 4.0,
        "CD247": 4.0,
        "CD3D": 4.0,
        "CD3E": 4.0,
        "CD3G": 4.0,
        "CD52": 4.0,
        "CORO1A": 4.0,
        "CYGB": 4.0,
        "DCLRE1C": 4.0,
        "DHFR": 4.0,
        "DOCK8": 4.0,
        "FKBP1A": 4.0,
        "FOXN1": 4.0,
        "IKBKB": 4.0,
        "IL2RG": 4.0,
        "IL7R": 4.0,
        "IMPDH1": 4.0,
        "IMPDH2": 4.0,
        "INPP5D": 4.0,
        "JAK3": 4.0,
        "KDM2B": 4.0,
        "KIT": 4.0,
        "LCK": 4.0,
        "LIG4": 4.0,
        "MALT1": 4.0,
        "MCFD2": 4.0,
        "MTHFD1": 4.0,
        "MYH7": 4.0,
        "MYOC": 4.0,
        "MYOCOS": 4.0,
        "NFKBIA": 4.0,
        "NHEJ1": 4.0,
        "NUDCD3": 4.0,
        "PGM3": 4.0,
        "PKIG": 4.0,
        "PNP": 4.0,
        "POLA1": 4.0,
        "POLA2": 4.0,
        "POLD1": 4.0,
        "POLD2": 4.0,
        "POLD3": 4.0,
        "POLD4": 4.0,
        "POLE": 4.0,
        "POLE2": 4.0,
        "POLE3": 4.0,
        "PRIM1": 4.0,
        "PRIM2": 4.0,
        "PTPRC": 4.0,
        "RAC2": 4.0,
        "RAG1": 4.0,
        "RAG2": 4.0,
        "RRM1": 4.0,
        "STK4": 4.0,
        "TCN2": 4.0,
        "TTC7A": 4.0,
        "VDAC2": 4.0,
        "ZAP70": 4.0,
        "ZBTB25": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
        "alemtuzumab",
    ],
    "moderate_risk": [
        "amg-191",
        "fludarabine phosphate",
        "methotrexate",
        "mycophenolate mofetil",
        "sirolimus",
        "tacrolimus anhydrous",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "severe_combined_immunodeficiency-screening-v1",
    "pathway_keywords": [
        "cell",
        "dopamine",
        "mast",
        "pathway",
        "receptor",
        "serotonin",
        "signaling",
        "stat",
    ],
    "mechanism_keywords": [
        "cell",
        "dopamine",
        "mast",
        "pathway",
        "receptor",
        "serotonin",
        "signaling",
        "stat",
    ],
    "reference_drug_ids": [
        "CHEMBL1096882",
        "CHEMBL1096882",
        "CHEMBL2109325",
        "CHEMBL269732",
        "CHEMBL1096882",
        "CHEMBL1456",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_severe_combined_immunodeficiency_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
