"""infundibulopelvic stenosis-multicystic kidney syndrome (INFUNDIBULOPELVIC_STENOSIS_MULTICYSTIC_KIDNEY_SYNDROME) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'infundibulopelvic stenosis-multicystic kidney syndrome (INFUNDIBULOPELVIC_STENOSIS_MULTICYSTIC_KIDNEY_SYNDROME)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Autosomal dominant inheritance",
    "Microscopic hematuria",
    "Multicystic kidney dysplasia",
    "Abdominal pain",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(infundibulopelvic stenosis-multicystic kidney syndrome[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(infundibulopelvic stenosis-multicystic kidney syndrome[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(infundibulopelvic stenosis-multicystic kidney syndrome[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(infundibulopelvic stenosis-multicystic kidney syndrome[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'infundibulopelvic stenosis-multicystic kidney syndrome OR infundibulopelvic'
GWAS_SEARCH_TERMS = ['infundibulopelvic stenosis-multicystic kidney syndrome', 'infundibulopelvic']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACE": 4.0,
        "ACVR2B": 4.0,
        "ARHGAP35": 4.0,
        "B4GALT1": 4.0,
        "BICC1": 4.0,
        "BMP4": 4.0,
        "BMP7": 4.0,
        "C3AR1": 4.0,
        "CLU": 4.0,
        "COL4A1": 4.0,
        "CRIM1": 4.0,
        "CYS1": 4.0,
        "DDR1": 4.0,
        "DZIP1L": 4.0,
        "EXOSC3": 4.0,
        "FAM72A": 4.0,
        "FAM72B": 4.0,
        "FAM72C": 4.0,
        "FAM72D": 4.0,
        "FMN1": 4.0,
        "FRYL": 4.0,
        "GDNF": 4.0,
        "GLIS2": 4.0,
        "GPC3": 4.0,
        "GPR39": 4.0,
        "JADE3": 4.0,
        "KRT2": 4.0,
        "LAMA5": 4.0,
        "LGR4": 4.0,
        "LIN7C": 4.0,
        "MAFB": 4.0,
        "MITF": 4.0,
        "MTSS1": 4.0,
        "MYO1E": 4.0,
        "NEK8": 4.0,
        "NFIA": 4.0,
        "NPHP3": 4.0,
        "NPHP3-ACAD11": 4.0,
        "NPHS1": 4.0,
        "OVOL1": 4.0,
        "PAX2": 4.0,
        "PCCB": 4.0,
        "PDE1A": 4.0,
        "PKD1": 4.0,
        "PKD2": 4.0,
        "PKHD1": 4.0,
        "RET": 4.0,
        "ROBO2": 4.0,
        "SALL1": 4.0,
        "SLC2A9": 4.0,
        "SLC9A1": 4.0,
        "SPRY1": 4.0,
        "TFAP2B": 4.0,
        "TNS1": 4.0,
        "TSC1": 4.0,
        "TSC2": 4.0,
        "TULP3": 4.0,
        "WNT9B": 4.0,
        "WT1": 4.0,
        "WWTR1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "infundibulopelvic_stenosis_multicystic_kidney_syndrome-screening-v1",
    "pathway_keywords": [
        "angiotensin",
        "cascade",
        "complement",
        "glucose",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "insulin",
        "iron",
        "metabolism",
    ],
    "mechanism_keywords": [
        "angiotensin",
        "cascade",
        "complement",
        "glucose",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "insulin",
        "iron",
        "metabolism",
    ],
    "reference_drug_ids": [
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_infundibulopelvic_stenosis_multicystic_kidney_syndrome_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
