"""lung disease (FAMILIAL_HYPOCALCIURIC_HYPERCALCEMIA_TYPE_3) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "lung disease (FAMILIAL_HYPOCALCIURIC_HYPERCALCEMIA_TYPE_3)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Multiple lipomas",
    "Bone pain",
    "Peptic ulcer",
    "Renal insufficiency",
    "Hypercalcemia",
    "Fatigue",
    "Depression",
    "Hypermagnesemia",
    "Primary hyperparathyroidism",
    "Parathormone-independent increased renal tubular calcium reabsorption",
    "Osteomalacia",
    "Chondrocalcinosis",
    "Muscle weakness",
    "Headache",
    "Kidney stone",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(lung disease[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(lung disease[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(lung disease[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(lung disease[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "lung disease OR lung"
GWAS_SEARCH_TERMS = ["lung disease", "lung"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABCA3": 4.0,
        "ABO": 4.0,
        "ADRA2A": 4.0,
        "ADRA2B": 4.0,
        "ADRA2C": 4.0,
        "ADRB2": 4.0,
        "AP3B1": 4.0,
        "ASXL1": 4.0,
        "CACNA2D1": 4.0,
        "CHI3L1": 4.0,
        "CHRM3": 4.0,
        "ELANE": 4.0,
        "F11": 4.0,
        "F2": 4.0,
        "F5": 4.0,
        "FGG": 4.0,
        "GABRA1": 4.0,
        "GABRA2": 4.0,
        "GABRA3": 4.0,
        "GABRA5": 4.0,
        "GABRG1": 4.0,
        "GABRG2": 4.0,
        "GABRG3": 4.0,
        "GRIN1": 4.0,
        "GRIN2A": 4.0,
        "GRIN2B": 4.0,
        "GRIN2C": 4.0,
        "GRIN2D": 4.0,
        "GRIN3A": 4.0,
        "GRIN3B": 4.0,
        "GUCY1B1": 4.0,
        "HPS1": 4.0,
        "HPS4": 4.0,
        "IL17A": 4.0,
        "KCNK3": 4.0,
        "KCNK9": 4.0,
        "MMP1": 4.0,
        "MMP13": 4.0,
        "MMP7": 4.0,
        "MMP8": 4.0,
        "MS4A1": 4.0,
        "NR3C1": 4.0,
        "OPRM1": 4.0,
        "PDE5A": 4.0,
        "PROC": 4.0,
        "PROS1": 4.0,
        "SLC12A1": 4.0,
        "SLC44A2": 4.0,
        "TLR7": 4.0,
        "TLR9": 4.0,
        "TSPAN15": 4.0,
        "TUBB": 4.0,
        "TUBB1": 4.0,
        "TUBB2A": 4.0,
        "TUBB2B": 4.0,
        "TUBB3": 4.0,
        "TUBB4A": 4.0,
        "TUBB4B": 4.0,
        "TUBB6": 4.0,
        "TUBB8": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
        "interferon gamma-1b",
    ],
    "moderate_risk": [
        "albuterol",
        "bupivacaine",
        "catequentinib",
        "colchicine",
        "cyclosporine",
        "dexmedetomidine",
        "doxapram hydrochloride",
        "doxycycline",
        "doxycycline anhydrous",
        "fentanyl",
        "formoterol",
        "furosemide",
        "indacaterol",
        "indacaterol maleate",
        "ketamine",
        "midazolam",
        "mk-0873",
        "nitric oxide",
        "pf-00610355",
        "prednisone",
        "rituximab",
        "salmeterol",
        "sildenafil",
        "tacrolimus anhydrous",
        "tiotropium",
        "tiotropium bromide",
        "tocilizumab",
        "triamcinolone",
    ],
    "low_risk": [
        "hydroxychloroquine",
        "hydroxychloroquine sulfate",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "familial_hypocalciuric_hypercalcemia_type_3-screening-v1",
    "pathway_keywords": [
        "cardiac",
        "cascade",
        "cell",
        "channel",
        "coagulation",
        "conduction",
        "gaba",
        "glutamate",
        "inflammasome",
        "innate",
    ],
    "mechanism_keywords": [
        "cardiac",
        "cascade",
        "cell",
        "channel",
        "coagulation",
        "conduction",
        "gaba",
        "glutamate",
        "inflammasome",
        "innate",
    ],
    "reference_drug_ids": [
        "CHEMBL1201576",
        "CHEMBL742",
        "CHEMBL714",
        "CHEMBL778",
        "CHEMBL107",
        "CHEMBL742",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_familial_hypocalciuric_hypercalcemia_type_3_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
