"""insulin measurement (INSULIN_MEASUREMENT) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'insulin measurement (INSULIN_MEASUREMENT)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of insulin measurement
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(insulin measurement[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(insulin measurement[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(insulin measurement[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(insulin measurement[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'insulin measurement OR insulin'
GWAS_SEARCH_TERMS = ['insulin measurement', 'insulin']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AHCTF1": 4.0,
        "AMBRA1": 4.0,
        "ARAP1": 4.0,
        "AXDND1": 4.0,
        "C2CD4A": 4.0,
        "CCDC68": 4.0,
        "CCDC85A": 4.0,
        "CDKAL1": 4.0,
        "CHD2": 4.0,
        "DGKH": 4.0,
        "EAPP": 4.0,
        "EIPR1": 4.0,
        "FCHSD2": 4.0,
        "FOLH1": 4.0,
        "FTMT": 4.0,
        "G6PC2": 4.0,
        "GIPR": 4.0,
        "GRB10": 4.0,
        "GRM5": 4.0,
        "IRS2": 4.0,
        "JAKMIP2": 4.0,
        "JMJD1C": 4.0,
        "KANK1": 4.0,
        "KCNC1": 4.0,
        "KIF11": 4.0,
        "KLF4": 4.0,
        "MADD": 4.0,
        "MAFB": 4.0,
        "MICAL2": 4.0,
        "MTNR1B": 4.0,
        "NCAM1": 4.0,
        "NR1H3": 4.0,
        "NRN1": 4.0,
        "OPRM1": 4.0,
        "OR4A5": 4.0,
        "OR4C12": 4.0,
        "OR4C13": 4.0,
        "OR4C46": 4.0,
        "OR4S1": 4.0,
        "PCDH10": 4.0,
        "PCSK1": 4.0,
        "RGS17": 4.0,
        "RMDN2": 4.0,
        "RSPO3": 4.0,
        "SAP130": 4.0,
        "SGSM1": 4.0,
        "SGSM2": 4.0,
        "SLC30A8": 4.0,
        "SNX7": 4.0,
        "SUGCT": 4.0,
        "TBC1D30": 4.0,
        "TCF4": 4.0,
        "TCF7L2": 4.0,
        "THUMPD2": 4.0,
        "TMEM259": 4.0,
        "TRAPPC12": 4.0,
        "TRIM43": 4.0,
        "TRIM51G": 4.0,
        "UNC5A": 4.0,
        "WWP2": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "insulin_measurement-screening-v1",
    "pathway_keywords": [
        "autophagy",
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "dopamine",
        "gaba",
        "glucose",
        "glutamate",
        "insulin",
    ],
    "mechanism_keywords": [
        "autophagy",
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "dopamine",
        "gaba",
        "glucose",
        "glutamate",
        "insulin",
    ],
    "reference_drug_ids": [
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_insulin_measurement_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
