"""Generate an expanded disease registry with ~500 additional diseases.

Produces disease_registry.json with curated disease entries across all
major therapeutic areas. EFO IDs are included where known; the scaffold
will attempt name-based resolution for the rest.
"""

import json
from pathlib import Path

# Diseases already in the registry (batch 1) — will be preserved
EXISTING_PATH = (
    Path(__file__).resolve().parents[1] / "src" / "med_research" / "diseases" / "disease_registry.json"
)

# ── New diseases by category ─────────────────────────────────────────────
# Format: (id, name, efo_id_or_None)

ONCOLOGY = [
    ("small_cell_lung_cancer", "Small cell lung cancer", "EFO_0000702"),
    ("nsclc", "Non-small cell lung cancer", "EFO_0003060"),
    ("triple_neg_breast_cancer", "Triple-negative breast cancer", "EFO_0005537"),
    ("her2_pos_breast_cancer", "HER2-positive breast cancer", None),
    ("ductal_carcinoma_in_situ", "Ductal carcinoma in situ", None),
    ("cervical_cancer", "Cervical cancer", "EFO_0001061"),
    ("cholangiocarcinoma", "Cholangiocarcinoma", "EFO_0005232"),
    ("mesothelioma", "Mesothelioma", "EFO_0000588"),
    ("neuroblastoma", "Neuroblastoma", "EFO_0000621"),
    ("retinoblastoma", "Retinoblastoma", "EFO_0000684"),
    ("wilms_tumor", "Wilms tumor", "EFO_0000731"),
    ("testicular_cancer", "Testicular cancer", "EFO_0000719"),
    ("adrenocortical_carcinoma", "Adrenocortical carcinoma", None),
    ("thymoma", "Thymoma", "EFO_0000727"),
    ("soft_tissue_sarcoma", "Soft tissue sarcoma", "EFO_0000707"),
    ("osteosarcoma", "Osteosarcoma", "EFO_0000637"),
    ("ewing_sarcoma", "Ewing sarcoma", "EFO_0000476"),
    ("rhabdomyosarcoma", "Rhabdomyosarcoma", "EFO_0002918"),
    ("kaposi_sarcoma", "Kaposi sarcoma", "EFO_0000564"),
    ("basal_cell_carcinoma", "Basal cell carcinoma", "EFO_0004193"),
    ("squamous_cell_carcinoma", "Cutaneous squamous cell carcinoma", None),
    ("merkel_cell_carcinoma", "Merkel cell carcinoma", None),
    ("chronic_lymphocytic_leukemia", "Chronic lymphocytic leukemia", "EFO_0000095"),
    ("acute_lymphoblastic_leukemia", "Acute lymphoblastic leukemia", "EFO_0000220"),
    ("hairy_cell_leukemia", "Hairy cell leukemia", "EFO_0000531"),
    ("mantle_cell_lymphoma", "Mantle cell lymphoma", "EFO_0000574"),
    ("follicular_lymphoma", "Follicular lymphoma", "EFO_0000403"),
    ("diffuse_large_b_cell_lymphoma", "Diffuse large B-cell lymphoma", "EFO_0000403"),
    ("burkitt_lymphoma", "Burkitt lymphoma", "EFO_0000309"),
    ("hodgkin_lymphoma", "Hodgkin lymphoma", "EFO_0000183"),
    ("waldenstrom_macroglobulinemia", "Waldenström macroglobulinemia", None),
    ("primary_cns_lymphoma", "Primary CNS lymphoma", None),
    ("cutaneous_t_cell_lymphoma", "Cutaneous T-cell lymphoma", None),
    ("polycythemia_vera", "Polycythemia vera", "EFO_0002429"),
    ("essential_thrombocythemia", "Essential thrombocythemia", "EFO_0000475"),
    ("myelofibrosis", "Myelofibrosis", "EFO_0002430"),
    ("mastocytosis", "Systemic mastocytosis", None),
    ("pheochromocytoma", "Pheochromocytoma", "EFO_0000649"),
    ("carcinoid_tumor", "Carcinoid tumor", None),
    ("gastrointestinal_stromal_tumor", "Gastrointestinal stromal tumor", "EFO_0000513"),
    ("uveal_melanoma", "Uveal melanoma", None),
    ("anal_cancer", "Anal cancer", None),
    ("vulvar_cancer", "Vulvar cancer", None),
    ("penile_cancer", "Penile cancer", None),
    ("nasopharyngeal_carcinoma", "Nasopharyngeal carcinoma", None),
    ("laryngeal_cancer", "Laryngeal cancer", None),
    ("salivary_gland_cancer", "Salivary gland cancer", None),
    ("small_bowel_cancer", "Small bowel adenocarcinoma", None),
    ("appendiceal_cancer", "Appendiceal cancer", None),
    ("peritoneal_mesothelioma", "Peritoneal mesothelioma", None),
]

CARDIOVASCULAR = [
    ("dilated_cardiomyopathy", "Dilated cardiomyopathy", "EFO_0000407"),
    ("hypertrophic_cardiomyopathy", "Hypertrophic cardiomyopathy", "EFO_0000538"),
    ("arrhythmogenic_cardiomyopathy", "Arrhythmogenic right ventricular cardiomyopathy", None),
    ("restrictive_cardiomyopathy", "Restrictive cardiomyopathy", None),
    ("long_qt_syndrome", "Long QT syndrome", "EFO_0003778"),
    ("brugada_syndrome", "Brugada syndrome", None),
    ("wolff_parkinson_white", "Wolff-Parkinson-White syndrome", None),
    ("supraventricular_tachycardia", "Supraventricular tachycardia", None),
    ("ventricular_tachycardia", "Ventricular tachycardia", None),
    ("aortic_stenosis", "Aortic stenosis", None),
    ("mitral_valve_prolapse", "Mitral valve prolapse", None),
    ("mitral_regurgitation", "Mitral regurgitation", None),
    ("infective_endocarditis", "Infective endocarditis", None),
    ("pericarditis", "Pericarditis", None),
    ("myocarditis", "Myocarditis", None),
    ("cardiac_amyloidosis", "Cardiac amyloidosis", None),
    ("takotsubo_cardiomyopathy", "Takotsubo cardiomyopathy", None),
    ("giant_cell_arteritis", "Giant cell arteritis", "EFO_0004236"),
    ("takayasu_arteritis", "Takayasu arteritis", None),
    ("kawasaki_disease", "Kawasaki disease", "EFO_0003777"),
    ("thromboangiitis_obliterans", "Thromboangiitis obliterans", None),
    ("pulmonary_valve_stenosis", "Pulmonary valve stenosis", None),
    ("coarctation_of_aorta", "Coarctation of aorta", None),
    ("tetralogy_of_fallot", "Tetralogy of Fallot", None),
    ("patent_ductus_arteriosus", "Patent ductus arteriosus", None),
    ("atrial_septal_defect", "Atrial septal defect", None),
    ("ventricular_septal_defect", "Ventricular septal defect", None),
    ("eisenmenger_syndrome", "Eisenmenger syndrome", None),
    ("raynauds_disease", "Raynaud disease", None),
    ("chronic_venous_insufficiency", "Chronic venous insufficiency", None),
]

NEUROLOGY = [
    ("frontotemporal_dementia", "Frontotemporal dementia", "EFO_0000504"),
    ("vascular_dementia", "Vascular dementia", None),
    ("lewy_body_dementia", "Dementia with Lewy bodies", None),
    ("progressive_supranuclear_palsy", "Progressive supranuclear palsy", None),
    ("corticobasal_degeneration", "Corticobasal degeneration", None),
    ("multiple_system_atrophy", "Multiple system atrophy", None),
    ("spinocerebellar_ataxia", "Spinocerebellar ataxia", None),
    ("friedreichs_ataxia", "Friedreich ataxia", "EFO_0000503"),
    ("charcot_marie_tooth", "Charcot-Marie-Tooth disease", None),
    ("guillain_barre", "Guillain-Barré syndrome", None),
    ("chronic_inflammatory_demyelinating", "Chronic inflammatory demyelinating polyneuropathy", None),
    ("trigeminal_neuralgia", "Trigeminal neuralgia", None),
    ("bells_palsy", "Bell palsy", None),
    ("narcolepsy", "Narcolepsy", "EFO_0003932"),
    ("restless_legs_syndrome", "Restless legs syndrome", None),
    ("essential_tremor", "Essential tremor", None),
    ("dystonia", "Dystonia", "EFO_0000415"),
    ("tourette_syndrome", "Tourette syndrome", None),
    ("obsessive_compulsive", "Obsessive-compulsive disorder", "EFO_0004246"),
    ("ptsd", "Post-traumatic stress disorder", None),
    ("eating_disorder_an", "Anorexia nervosa", "EFO_0000240"),
    ("eating_disorder_bn", "Bulimia nervosa", None),
    ("substance_use_alcohol", "Alcohol use disorder", None),
    ("substance_use_opioid", "Opioid use disorder", None),
    ("neuropathic_pain", "Neuropathic pain", None),
    ("cluster_headache", "Cluster headache", None),
    ("tension_headache", "Tension-type headache", None),
    ("idiopathic_intracranial_hypertension", "Idiopathic intracranial hypertension", None),
    ("normal_pressure_hydrocephalus", "Normal pressure hydrocephalus", None),
    ("cerebral_palsy", "Cerebral palsy", None),
    ("tuberous_sclerosis_epilepsy", "Tuberous sclerosis complex epilepsy", None),
    ("lennox_gastaut", "Lennox-Gastaut syndrome", None),
    ("dravet_syndrome", "Dravet syndrome", None),
    ("status_epilepticus", "Status epilepticus", None),
    ("neuromyelitis_optica", "Neuromyelitis optica spectrum disorder", None),
    ("transverse_myelitis", "Transverse myelitis", None),
    ("meningitis_bacterial", "Bacterial meningitis", None),
    ("encephalitis_autoimmune", "Autoimmune encephalitis", None),
    ("creutzfeldt_jakob", "Creutzfeldt-Jakob disease", None),
    ("wernicke_encephalopathy", "Wernicke encephalopathy", None),
]

RESPIRATORY = [
    ("bronchiectasis", "Bronchiectasis", None),
    ("allergic_bronchopulmonary_aspergillosis", "Allergic bronchopulmonary aspergillosis", None),
    ("eosinophilic_pneumonia", "Eosinophilic pneumonia", None),
    ("hypersensitivity_pneumonitis", "Hypersensitivity pneumonitis", None),
    ("organizing_pneumonia", "Cryptogenic organizing pneumonia", None),
    ("alpha1_antitrypsin", "Alpha-1 antitrypsin deficiency", None),
    ("lymphangioleiomyomatosis", "Lymphangioleiomyomatosis", None),
    ("primary_ciliary_dyskinesia", "Primary ciliary dyskinesia", None),
    ("pleural_effusion", "Pleural effusion", None),
    ("pneumothorax", "Pneumothorax", None),
    ("ards", "Acute respiratory distress syndrome", None),
    ("community_acquired_pneumonia", "Community-acquired pneumonia", None),
    ("ventilator_pneumonia", "Ventilator-associated pneumonia", None),
    ("aspergillosis_invasive", "Invasive aspergillosis", None),
    ("allergic_rhinitis", "Allergic rhinitis", "EFO_0003785"),
    ("chronic_rhinosinusitis", "Chronic rhinosinusitis", None),
    ("nasal_polyposis", "Nasal polyposis", None),
    ("vocal_cord_dysfunction", "Vocal cord dysfunction", None),
    ("occupational_asthma", "Occupational asthma", None),
    ("eosinophilic_granulomatosis", "Eosinophilic granulomatosis with polyangiitis", None),
]

METABOLIC = [
    ("type3_diabetes", "Maturity-onset diabetes of the young", None),
    ("gestational_diabetes", "Gestational diabetes mellitus", None),
    ("diabetic_neuropathy", "Diabetic neuropathy", None),
    ("diabetic_nephropathy", "Diabetic nephropathy", None),
    ("metabolic_syndrome", "Metabolic syndrome", None),
    ("hyperuricemia", "Hyperuricemia", None),
    ("hyperparathyroidism", "Hyperparathyroidism", None),
    ("hypoparathyroidism", "Hypoparathyroidism", None),
    ("acromegaly", "Acromegaly", "EFO_0000232"),
    ("prolactinoma", "Prolactinoma", None),
    ("diabetes_insipidus", "Diabetes insipidus", None),
    ("adrenal_insufficiency", "Adrenal insufficiency", None),
    ("congenital_adrenal_hyperplasia", "Congenital adrenal hyperplasia", None),
    ("graves_disease", "Graves disease", "EFO_0004234"),
    ("hashimoto_thyroiditis", "Hashimoto thyroiditis", None),
    ("thyroid_nodule", "Thyroid nodule", None),
    ("primary_aldosteronism", "Primary aldosteronism", None),
    ("hemochromatosis", "Hereditary hemochromatosis", "EFO_0000541"),
    ("porphyria", "Porphyria", None),
    ("galactosemia", "Galactosemia", None),
    ("maple_syrup_urine", "Maple syrup urine disease", None),
    ("homocystinuria", "Homocystinuria", None),
    ("tyrosinemia", "Tyrosinemia", None),
    ("glycogen_storage_disease", "Glycogen storage disease", None),
    ("lipodystrophy", "Lipodystrophy", None),
    ("familial_hypercholesterolemia", "Familial hypercholesterolemia", "EFO_0003899"),
    ("hypertriglyceridemia", "Hypertriglyceridemia", None),
    ("sitosterolemia", "Sitosterolemia", None),
    ("carnitine_deficiency", "Carnitine deficiency", None),
    ("biotinidase_deficiency", "Biotinidase deficiency", None),
]

GASTROENTEROLOGY = [
    ("crohns_disease", "Crohn disease", "EFO_0000384"),
    ("ulcerative_colitis", "Ulcerative colitis", "EFO_0000729"),
    ("microscopic_colitis", "Microscopic colitis", None),
    ("eosinophilic_esophagitis", "Eosinophilic esophagitis", None),
    ("achalasia", "Achalasia", None),
    ("barretts_esophagus", "Barrett esophagus", None),
    ("peptic_ulcer", "Peptic ulcer disease", None),
    ("h_pylori_infection", "Helicobacter pylori infection", None),
    ("gastroparesis", "Gastroparesis", None),
    ("irritable_bowel", "Irritable bowel syndrome", None),
    ("diverticular_disease", "Diverticular disease", None),
    ("intestinal_pseudo_obstruction", "Chronic intestinal pseudo-obstruction", None),
    ("short_bowel_syndrome", "Short bowel syndrome", None),
    ("whipple_disease", "Whipple disease", None),
    ("primary_biliary_cholangitis", "Primary biliary cholangitis", None),
    ("primary_sclerosing_cholangitis", "Primary sclerosing cholangitis", None),
    ("autoimmune_hepatitis", "Autoimmune hepatitis", None),
    ("alcoholic_liver_disease", "Alcoholic liver disease", None),
    ("hepatic_encephalopathy", "Hepatic encephalopathy", None),
    ("hepatorenal_syndrome", "Hepatorenal syndrome", None),
    ("budd_chiari_syndrome", "Budd-Chiari syndrome", None),
    ("hereditary_pancreatitis", "Hereditary pancreatitis", None),
    ("autoimmune_pancreatitis", "Autoimmune pancreatitis", None),
    ("exocrine_pancreatic_insufficiency", "Exocrine pancreatic insufficiency", None),
    ("functional_dyspepsia", "Functional dyspepsia", None),
]

NEPHROLOGY = [
    ("minimal_change_disease", "Minimal change disease", None),
    ("focal_segmental_glomerulosclerosis", "Focal segmental glomerulosclerosis", None),
    ("anti_gbm_disease", "Anti-glomerular basement membrane disease", None),
    ("anca_vasculitis_renal", "ANCA-associated vasculitis with renal involvement", None),
    ("diabetic_kidney_disease", "Diabetic kidney disease", None),
    ("hypertensive_nephrosclerosis", "Hypertensive nephrosclerosis", None),
    ("renal_tubular_acidosis", "Renal tubular acidosis", None),
    ("nephrotic_syndrome", "Nephrotic syndrome", None),
    ("alport_syndrome", "Alport syndrome", None),
    ("fabry_nephropathy", "Fabry disease nephropathy", None),
    ("thin_basement_membrane", "Thin basement membrane nephropathy", None),
    ("c3_glomerulopathy", "C3 glomerulopathy", None),
    ("membranoproliferative_gn", "Membranoproliferative glomerulonephritis", None),
    ("acute_kidney_injury", "Acute kidney injury", None),
    ("renal_artery_stenosis", "Renal artery stenosis", None),
    ("interstitial_nephritis", "Tubulointerstitial nephritis", None),
    ("kidney_stones", "Nephrolithiasis", None),
    ("cystinuria", "Cystinuria", None),
    ("bartter_syndrome", "Bartter syndrome", None),
    ("gitelman_syndrome", "Gitelman syndrome", None),
]

HEMATOLOGY = [
    ("von_willebrand_disease", "Von Willebrand disease", None),
    ("hemophilia_b", "Hemophilia B", None),
    ("factor_v_leiden", "Factor V Leiden thrombophilia", None),
    ("antiphospholipid_syndrome", "Antiphospholipid syndrome", None),
    ("heparin_induced_thrombocytopenia", "Heparin-induced thrombocytopenia", None),
    ("thrombotic_thrombocytopenic_purpura", "Thrombotic thrombocytopenic purpura", None),
    ("hemolytic_uremic_syndrome", "Hemolytic uremic syndrome", None),
    ("paroxysmal_nocturnal_hemoglobinuria", "Paroxysmal nocturnal hemoglobinuria", None),
    ("autoimmune_hemolytic_anemia", "Autoimmune hemolytic anemia", None),
    ("warm_agglutinin_disease", "Warm autoimmune hemolytic anemia", None),
    ("cold_agglutinin_disease", "Cold agglutinin disease", None),
    ("iron_deficiency_anemia", "Iron deficiency anemia", None),
    ("pernicious_anemia", "Pernicious anemia", None),
    ("hereditary_spherocytosis", "Hereditary spherocytosis", None),
    ("g6pd_deficiency", "Glucose-6-phosphate dehydrogenase deficiency", None),
    ("alpha_thalassemia", "Alpha-thalassemia", None),
    ("diamond_blackfan_anemia", "Diamond-Blackfan anemia", None),
    ("fanconi_anemia", "Fanconi anemia", None),
    ("chronic_myelomonocytic_leukemia", "Chronic myelomonocytic leukemia", None),
    ("primary_myelofibrosis", "Primary myelofibrosis", None),
    ("systemic_al_amyloidosis", "Systemic AL amyloidosis", None),
    ("light_chain_deposition", "Light chain deposition disease", None),
    ("castleman_disease", "Castleman disease", None),
    ("hemophagocytic_lymphohistiocytosis", "Hemophagocytic lymphohistiocytosis", None),
    ("langerhans_cell_histiocytosis", "Langerhans cell histiocytosis", None),
]

INFECTIOUS = [
    ("hepatitis_a", "Hepatitis A", None),
    ("hepatitis_d", "Hepatitis D", None),
    ("hepatitis_e", "Hepatitis E", None),
    ("ebola", "Ebola virus disease", None),
    ("zika", "Zika virus disease", None),
    ("chikungunya", "Chikungunya fever", None),
    ("west_nile", "West Nile virus infection", None),
    ("yellow_fever", "Yellow fever", None),
    ("rabies", "Rabies", None),
    ("measles", "Measles", None),
    ("rubella", "Rubella", None),
    ("mumps", "Mumps", None),
    ("varicella", "Varicella", None),
    ("herpes_simplex", "Herpes simplex virus infection", None),
    ("cytomegalovirus", "Cytomegalovirus infection", None),
    ("epstein_barr", "Epstein-Barr virus infection", None),
    ("rsv_infection", "Respiratory syncytial virus infection", None),
    ("norovirus", "Norovirus gastroenteritis", None),
    ("rotavirus", "Rotavirus gastroenteritis", None),
    ("mrsa_infection", "Methicillin-resistant Staphylococcus aureus infection", None),
    ("pseudomonas_infection", "Pseudomonas aeruginosa infection", None),
    ("klebsiella_infection", "Klebsiella pneumoniae infection", None),
    ("acinetobacter_infection", "Acinetobacter baumannii infection", None),
    ("enterococcal_infection", "Vancomycin-resistant Enterococcus infection", None),
    ("gonorrhea", "Gonorrhea", None),
    ("syphilis", "Syphilis", None),
    ("chlamydia", "Chlamydia infection", None),
    ("candidiasis_invasive", "Invasive candidiasis", None),
    ("cryptococcal_meningitis", "Cryptococcal meningitis", None),
    ("pneumocystis_pneumonia", "Pneumocystis pneumonia", None),
    ("toxoplasmosis", "Toxoplasmosis", None),
    ("leishmaniasis", "Leishmaniasis", None),
    ("chagas_disease", "Chagas disease", None),
    ("schistosomiasis", "Schistosomiasis", None),
    ("lyme_disease", "Lyme disease", None),
    ("rocky_mountain_spotted_fever", "Rocky Mountain spotted fever", None),
    ("plague", "Plague", None),
    ("anthrax", "Anthrax", None),
    ("brucellosis", "Brucellosis", None),
    ("leprosy", "Leprosy", None),
]

OPHTHALMOLOGY = [
    ("retinitis_pigmentosa", "Retinitis pigmentosa", "EFO_0000678"),
    ("stargardt_disease", "Stargardt disease", None),
    ("keratoconus", "Keratoconus", None),
    ("fuchs_dystrophy", "Fuchs endothelial corneal dystrophy", None),
    ("dry_eye_disease", "Dry eye disease", None),
    ("retinal_vein_occlusion", "Retinal vein occlusion", None),
    ("retinal_detachment", "Retinal detachment", None),
    ("central_serous_chorioretinopathy", "Central serous chorioretinopathy", None),
    ("ocular_hypertension", "Ocular hypertension", None),
    ("optic_neuritis", "Optic neuritis", None),
    ("leber_hereditary_optic_neuropathy", "Leber hereditary optic neuropathy", None),
    ("thyroid_eye_disease", "Thyroid eye disease", None),
    ("vernal_keratoconjunctivitis", "Vernal keratoconjunctivitis", None),
    ("blepharitis", "Blepharitis", None),
    ("macular_edema", "Diabetic macular edema", None),
]

DERMATOLOGY = [
    ("acne_vulgaris", "Acne vulgaris", None),
    ("rosacea", "Rosacea", None),
    ("seborrheic_dermatitis", "Seborrheic dermatitis", None),
    ("contact_dermatitis", "Contact dermatitis", None),
    ("urticaria_chronic", "Chronic spontaneous urticaria", None),
    ("angioedema", "Angioedema", None),
    ("lichen_planus", "Lichen planus", None),
    ("lichen_sclerosus", "Lichen sclerosus", None),
    ("morphea", "Morphea", None),
    ("dermatomyositis", "Dermatomyositis", "EFO_0000405"),
    ("bullous_pemphigoid", "Bullous pemphigoid", None),
    ("epidermolysis_bullosa", "Epidermolysis bullosa", None),
    ("ichthyosis_vulgaris", "Ichthyosis vulgaris", None),
    ("palmoplantar_pustulosis", "Palmoplantar pustulosis", None),
    ("granuloma_annulare", "Granuloma annulare", None),
    ("pyoderma_gangrenosum", "Pyoderma gangrenosum", None),
    ("cutaneous_lupus", "Cutaneous lupus erythematosus", None),
    ("prurigo_nodularis", "Prurigo nodularis", None),
    ("keloid", "Keloid", None),
    ("scleroderma_localized", "Localized scleroderma", None),
]

MUSCULOSKELETAL = [
    ("ankylosing_spondylitis_nr", "Non-radiographic axial spondyloarthritis", None),
    ("reactive_arthritis", "Reactive arthritis", None),
    ("juvenile_idiopathic_arthritis", "Juvenile idiopathic arthritis", None),
    ("polymyalgia_rheumatica", "Polymyalgia rheumatica", None),
    ("polymyositis", "Polymyositis", None),
    ("inclusion_body_myositis", "Inclusion body myositis", None),
    ("sjogrens_associated_arthritis", "Sjögren syndrome-associated arthritis", None),
    ("calcium_pyrophosphate", "Calcium pyrophosphate deposition disease", None),
    ("pagets_disease_bone", "Paget disease of bone", None),
    ("osteogenesis_imperfecta", "Osteogenesis imperfecta", None),
    ("achondroplasia", "Achondroplasia", None),
    ("scoliosis", "Idiopathic scoliosis", None),
    ("rotator_cuff_tendinopathy", "Rotator cuff tendinopathy", None),
    ("plantar_fasciitis", "Plantar fasciitis", None),
    ("tendinosis", "Tendinosis", None),
    ("bursitis", "Bursitis", None),
    ("avascular_necrosis", "Avascular necrosis", None),
    ("spinal_stenosis", "Spinal stenosis", None),
    ("herniated_disc", "Lumbar disc herniation", None),
    ("chronic_low_back_pain", "Chronic low back pain", None),
]

AUTOIMMUNE = [
    ("mixed_connective_tissue", "Mixed connective tissue disease", None),
    ("undifferentiated_ctd", "Undifferentiated connective tissue disease", None),
    ("anti_synthetase_syndrome", "Anti-synthetase syndrome", None),
    ("behcet_disease", "Behçet disease", None),
    ("relapsing_polychondritis", "Relapsing polychondritis", None),
    ("granulomatosis_polyangiitis", "Granulomatosis with polyangiitis", None),
    ("microscopic_polyangiitis", "Microscopic polyangiitis", None),
    ("polyarteritis_nodosa", "Polyarteritis nodosa", None),
    ("iga_vasculitis", "IgA vasculitis", None),
    ("cryoglobulinemic_vasculitis", "Cryoglobulinemic vasculitis", None),
    ("autoimmune_inner_ear", "Autoimmune inner ear disease", None),
    ("autoimmune_gastritis", "Autoimmune gastritis", None),
    ("autoimmune_polyglandular", "Autoimmune polyglandular syndrome", None),
    ("stiff_person_syndrome", "Stiff-person syndrome", None),
    ("neurosarcoidosis", "Neurosarcoidosis", None),
    ("primary_angiitis_cns", "Primary angiitis of the central nervous system", None),
    ("retroperitoneal_fibrosis", "Retroperitoneal fibrosis", None),
    ("igg4_related_disease", "IgG4-related disease", None),
    ("adult_onset_stills", "Adult-onset Still disease", None),
    ("familial_mediterranean_fever", "Familial Mediterranean fever", None),
]

RARE_GENETIC = [
    ("down_syndrome", "Down syndrome", None),
    ("turner_syndrome", "Turner syndrome", None),
    ("klinefelter_syndrome", "Klinefelter syndrome", None),
    ("fragile_x", "Fragile X syndrome", None),
    ("prader_willi", "Prader-Willi syndrome", None),
    ("angelman_syndrome", "Angelman syndrome", None),
    ("williams_syndrome", "Williams syndrome", None),
    ("noonan_syndrome", "Noonan syndrome", None),
    ("rett_syndrome", "Rett syndrome", None),
    ("tay_sachs", "Tay-Sachs disease", None),
    ("niemann_pick", "Niemann-Pick disease", None),
    ("pompe_disease", "Pompe disease", None),
    ("mucopolysaccharidosis_i", "Mucopolysaccharidosis type I", None),
    ("mucopolysaccharidosis_ii", "Mucopolysaccharidosis type II", None),
    ("krabbe_disease", "Krabbe disease", None),
    ("metachromatic_leukodystrophy", "Metachromatic leukodystrophy", None),
    ("adrenoleukodystrophy", "Adrenoleukodystrophy", None),
    ("batten_disease", "Batten disease", None),
    ("ataxia_telangiectasia", "Ataxia-telangiectasia", None),
    ("xeroderma_pigmentosum", "Xeroderma pigmentosum", None),
    ("cockayne_syndrome", "Cockayne syndrome", None),
    ("werner_syndrome", "Werner syndrome", None),
    ("progeria", "Hutchinson-Gilford progeria syndrome", None),
    ("von_hippel_lindau", "Von Hippel-Lindau disease", None),
    ("neurofibromatosis_2", "Neurofibromatosis type 2", None),
    ("li_fraumeni_syndrome", "Li-Fraumeni syndrome", None),
    ("familial_adenomatous_polyposis", "Familial adenomatous polyposis", None),
    ("lynch_syndrome", "Lynch syndrome", None),
    ("beckwith_wiedemann", "Beckwith-Wiedemann syndrome", None),
    ("kabuki_syndrome", "Kabuki syndrome", None),
    ("charge_syndrome", "CHARGE syndrome", None),
    ("cornelia_de_lange", "Cornelia de Lange syndrome", None),
    ("rubinstein_taybi", "Rubinstein-Taybi syndrome", None),
    ("alagille_syndrome", "Alagille syndrome", None),
    ("hereditary_hemorrhagic_telangiectasia", "Hereditary hemorrhagic telangiectasia", None),
    ("loeys_dietz_syndrome", "Loeys-Dietz syndrome", None),
    ("stickler_syndrome", "Stickler syndrome", None),
    ("waardenburg_syndrome", "Waardenburg syndrome", None),
    ("usher_syndrome", "Usher syndrome", None),
    ("pendred_syndrome", "Pendred syndrome", None),
]

ENDOCRINE_REPRODUCTIVE = [
    ("endometriosis", "Endometriosis", "EFO_0001065"),
    ("uterine_fibroids", "Uterine fibroids", None),
    ("adenomyosis", "Adenomyosis", None),
    ("premature_ovarian_insufficiency", "Premature ovarian insufficiency", None),
    ("male_hypogonadism", "Male hypogonadism", None),
    ("benign_prostatic_hyperplasia", "Benign prostatic hyperplasia", None),
    ("erectile_dysfunction", "Erectile dysfunction", None),
    ("preeclampsia", "Preeclampsia", None),
    ("hyperemesis_gravidarum", "Hyperemesis gravidarum", None),
    ("postpartum_depression", "Postpartum depression", None),
]

ENT_DENTAL = [
    ("otitis_media_chronic", "Chronic otitis media", None),
    ("otosclerosis", "Otosclerosis", None),
    ("menieres_disease", "Ménière disease", None),
    ("vestibular_neuritis", "Vestibular neuritis", None),
    ("sudden_sensorineural_hearing_loss", "Sudden sensorineural hearing loss", None),
    ("tinnitus", "Tinnitus", None),
    ("laryngopharyngeal_reflux", "Laryngopharyngeal reflux", None),
    ("oral_lichen_planus", "Oral lichen planus", None),
    ("periodontitis", "Periodontitis", None),
    ("sialolithiasis", "Sialolithiasis", None),
]

OTHER = [
    ("chronic_fatigue_syndrome", "Chronic fatigue syndrome", None),
    ("ehlers_danlos_hypermobile", "Hypermobile Ehlers-Danlos syndrome", None),
    ("mast_cell_activation", "Mast cell activation syndrome", None),
    ("postural_orthostatic_tachycardia", "Postural orthostatic tachycardia syndrome", None),
    ("sarcoid_arthritis", "Sarcoid arthritis", None),
    ("complex_regional_pain", "Complex regional pain syndrome", None),
    ("interstitial_cystitis", "Interstitial cystitis", None),
    ("chronic_pelvic_pain", "Chronic pelvic pain syndrome", None),
    ("vulvodynia", "Vulvodynia", None),
    ("lymphedema", "Lymphedema", None),
]

ALL_CATEGORIES = {
    "oncology": ONCOLOGY,
    "cardiovascular": CARDIOVASCULAR,
    "neurology": NEUROLOGY,
    "respiratory": RESPIRATORY,
    "metabolic": METABOLIC,
    "gastroenterology": GASTROENTEROLOGY,
    "nephrology": NEPHROLOGY,
    "hematology": HEMATOLOGY,
    "infectious": INFECTIOUS,
    "ophthalmology": OPHTHALMOLOGY,
    "dermatology": DERMATOLOGY,
    "musculoskeletal": MUSCULOSKELETAL,
    "autoimmune": AUTOIMMUNE,
    "rare_genetic": RARE_GENETIC,
    "endocrine_reproductive": ENDOCRINE_REPRODUCTIVE,
    "ent_dental": ENT_DENTAL,
    "other": OTHER,
}


def main():
    # Load existing registry
    with open(EXISTING_PATH, encoding="utf-8") as f:
        registry = json.load(f)

    existing_ids = {d["id"] for d in registry["diseases"]}
    added = 0

    for category, diseases in ALL_CATEGORIES.items():
        for did, name, efo in diseases:
            if did in existing_ids:
                continue
            entry = {"id": did, "name": name, "category": category}
            if efo:
                entry["efo_id"] = efo
            registry["diseases"].append(entry)
            existing_ids.add(did)
            added += 1

    # Sort by category then name
    registry["diseases"].sort(key=lambda d: (d.get("category", ""), d["name"]))
    registry["description"] = (
        f"Curated disease registry for batch scaffolding. "
        f"{len(registry['diseases'])} diseases across {len(ALL_CATEGORIES) + 13} therapeutic areas."
    )

    with open(EXISTING_PATH, "w", encoding="utf-8") as f:
        json.dump(registry, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"Added {added} new diseases. Total: {len(registry['diseases'])}")


if __name__ == "__main__":
    main()
