"""urothelial papilloma (UROTHELIAL_PAPILLOMA) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "urothelial papilloma (UROTHELIAL_PAPILLOMA)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of urothelial papilloma
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(urothelial papilloma[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(urothelial papilloma[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(urothelial papilloma[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(urothelial papilloma[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "urothelial papilloma OR urothelial"
GWAS_SEARCH_TERMS = ["urothelial papilloma", "urothelial"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AKT1": 4.0,
        "CCN1": 4.0,
        "CCND1": 4.0,
        "CYP1A1": 4.0,
        "EPRS1": 4.0,
        "EREG": 4.0,
        "ESR1": 4.0,
        "FGF3": 4.0,
        "FGFR3": 4.0,
        "GABPA": 4.0,
        "GUSB": 4.0,
        "HRAS": 4.0,
        "JTB": 4.0,
        "KAT5": 4.0,
        "KRAS": 4.0,
        "KRT18": 4.0,
        "KRT20": 4.0,
        "KRT7": 4.0,
        "LIAT1": 4.0,
        "MCM2": 4.0,
        "MIB1": 4.0,
        "MKI67": 4.0,
        "MST1R": 4.0,
        "MT-CO2": 4.0,
        "MTOR": 4.0,
        "NFE2L2": 4.0,
        "NR1I2": 4.0,
        "PARP1": 4.0,
        "PCNA": 4.0,
        "PIEZO1": 4.0,
        "PLA2G4A": 4.0,
        "PLAUR": 4.0,
        "PRKCA": 4.0,
        "PRKCB": 4.0,
        "PRKCG": 4.0,
        "PRRT2": 4.0,
        "PTGS2": 4.0,
        "PTK2": 4.0,
        "PYGB": 4.0,
        "SLC2A1": 4.0,
        "TERT": 4.0,
        "TP53": 4.0,
        "TP53BP1": 4.0,
        "UPK3A": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "favezelimab",
        "pembrolizumab",
        "vibostolimab",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "urothelial_papilloma-screening-v1",
    "pathway_keywords": [
        "cell",
        "cycle",
        "glucose",
        "hormone",
        "insulin",
        "mapk",
        "metabolism",
        "mtor",
        "pi3k",
        "regulation",
    ],
    "mechanism_keywords": [
        "cell",
        "cycle",
        "glucose",
        "hormone",
        "insulin",
        "mapk",
        "metabolism",
        "mtor",
        "pi3k",
        "regulation",
    ],
    "reference_drug_ids": [
        "CHEMBL3137343",
        "CHEMBL4297784",
        "CHEMBL4297785",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_urothelial_papilloma_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
