"""tympanic membrane perforation (TYMPANIC_MEMBRANE_PERFORATION) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "tympanic membrane perforation (TYMPANIC_MEMBRANE_PERFORATION)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of tympanic membrane perforation
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(tympanic membrane perforation[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(tympanic membrane perforation[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(tympanic membrane perforation[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(tympanic membrane perforation[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "tympanic membrane perforation OR tympanic"
GWAS_SEARCH_TERMS = ["tympanic membrane perforation", "tympanic"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABCB5": 4.0,
        "AGR3": 4.0,
        "AHR": 4.0,
        "FERD3L": 4.0,
        "FGFR2": 4.0,
        "HDAC9": 4.0,
        "ITGB8": 4.0,
        "MACC1": 4.0,
        "PLG": 4.0,
        "POLR1F": 4.0,
        "PRPS1L1": 4.0,
        "SNX13": 4.0,
        "SP8": 4.0,
        "TMEM196": 4.0,
        "TWIST1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "tympanic_membrane_perforation-screening-v1",
    "pathway_keywords": [
        "adhesion",
        "cell",
        "hormone",
        "integrin",
        "mapk",
        "metabolism",
        "signaling",
        "thyroid",
        "xenobiotic",
    ],
    "mechanism_keywords": [
        "adhesion",
        "cell",
        "hormone",
        "integrin",
        "mapk",
        "metabolism",
        "signaling",
        "thyroid",
        "xenobiotic",
    ],
    "reference_drug_ids": [
        "CHEMBL2108081",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_tympanic_membrane_perforation_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
