"""HIV-Associated Lipodystrophy Syndrome (HIV_ASSOCIATED_LIPODYSTROPHY_SYNDROME) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'HIV-Associated Lipodystrophy Syndrome (HIV_ASSOCIATED_LIPODYSTROPHY_SYNDROME)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of HIV-Associated Lipodystrophy Syndrome
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(HIV-Associated Lipodystrophy Syndrome[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(HIV-Associated Lipodystrophy Syndrome[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(HIV-Associated Lipodystrophy Syndrome[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(HIV-Associated Lipodystrophy Syndrome[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'HIV-Associated Lipodystrophy Syndrome OR HIV-Associated'
GWAS_SEARCH_TERMS = ['HIV-Associated Lipodystrophy Syndrome', 'HIV-Associated']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ALOX5AP": 4.0,
        "GHRHR": 4.0,
        "GPD2": 4.0,
        "IGF1R": 4.0,
        "LEPR": 4.0,
        "MT-ND1": 4.0,
        "MT-ND2": 4.0,
        "MT-ND3": 4.0,
        "MT-ND4": 4.0,
        "MT-ND4L": 4.0,
        "MT-ND5": 4.0,
        "MT-ND6": 4.0,
        "NDUFA1": 4.0,
        "NDUFA10": 4.0,
        "NDUFA11": 4.0,
        "NDUFA12": 4.0,
        "NDUFA13": 4.0,
        "NDUFA2": 4.0,
        "NDUFA3": 4.0,
        "NDUFA4": 4.0,
        "NDUFA4L2": 4.0,
        "NDUFA5": 4.0,
        "NDUFA6": 4.0,
        "NDUFA7": 4.0,
        "NDUFA8": 4.0,
        "NDUFA9": 4.0,
        "NDUFAB1": 4.0,
        "NDUFAF1": 4.0,
        "NDUFAF2": 4.0,
        "NDUFAF3": 4.0,
        "NDUFAF4": 4.0,
        "NDUFB1": 4.0,
        "NDUFB10": 4.0,
        "NDUFB11": 4.0,
        "NDUFB2": 4.0,
        "NDUFB3": 4.0,
        "NDUFB4": 4.0,
        "NDUFB5": 4.0,
        "NDUFB6": 4.0,
        "NDUFB7": 4.0,
        "NDUFB8": 4.0,
        "NDUFB9": 4.0,
        "NDUFC1": 4.0,
        "NDUFC2": 4.0,
        "NDUFS1": 4.0,
        "NDUFS2": 4.0,
        "NDUFS3": 4.0,
        "NDUFS4": 4.0,
        "NDUFS5": 4.0,
        "NDUFS6": 4.0,
        "NDUFS7": 4.0,
        "NDUFS8": 4.0,
        "NDUFV1": 4.0,
        "NDUFV2": 4.0,
        "NDUFV3": 4.0,
        "PPARG": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "fiboflapon",
        "fiboflapon sodium",
        "pioglitazone",
    ],
    "low_risk": [
        "mecasermin",
        "metformin",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "hiv_associated_lipodystrophy_syndrome-screening-v1",
    "pathway_keywords": [
        "cascade",
        "coagulation",
        "lipid",
        "metabolism",
        "remodeling",
    ],
    "mechanism_keywords": [
        "cascade",
        "coagulation",
        "lipid",
        "metabolism",
        "remodeling",
    ],
    "reference_drug_ids": [
        "CHEMBL1431",
        "CHEMBL1431",
        "CHEMBL1431",
        "CHEMBL1431",
        "CHEMBL1431",
        "CHEMBL1431",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_hiv_associated_lipodystrophy_syndrome_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
