"""BAFopathy (BAFOPATHY) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'BAFopathy (BAFOPATHY)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of BAFopathy
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(BAFopathy[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(BAFopathy[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(BAFopathy[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(BAFopathy[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'BAFopathy OR BAFopathy'
GWAS_SEARCH_TERMS = ['BAFopathy', 'BAFopathy']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACTL6A": 4.0,
        "ADNP": 4.0,
        "ARID1A": 4.0,
        "ARID1B": 4.0,
        "ARID2": 4.0,
        "BANF1": 4.0,
        "BCL11A": 4.0,
        "BCL11B": 4.0,
        "BICRA": 4.0,
        "CHD7": 4.0,
        "CHD8": 4.0,
        "DNMT1": 4.0,
        "JARID2": 4.0,
        "KDM6A": 4.0,
        "KMT2D": 4.0,
        "PBRM1": 4.0,
        "SMARCA2": 4.0,
        "SMARCA4": 4.0,
        "SMARCB1": 4.0,
        "SMARCC1": 4.0,
        "SMARCC2": 4.0,
        "SOX11": 4.0,
        "TRIP12": 4.0,
        "YY1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "bafopathy-screening-v1",
    "pathway_keywords": [
        "immune",
        "inflammation",
    ],
    "mechanism_keywords": [
        "immune",
        "inflammation",
    ],
    "reference_drug_ids": [
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_bafopathy_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
