"""Gastric Neuroendocrine Tumor G1 (GASTRIC_NEUROENDOCRINE_TUMOR_G1) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'Gastric Neuroendocrine Tumor G1 (GASTRIC_NEUROENDOCRINE_TUMOR_G1)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of Gastric Neuroendocrine Tumor G1
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(Gastric Neuroendocrine Tumor G1[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(Gastric Neuroendocrine Tumor G1[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(Gastric Neuroendocrine Tumor G1[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(Gastric Neuroendocrine Tumor G1[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'Gastric Neuroendocrine Tumor G1 OR Gastric'
GWAS_SEARCH_TERMS = ['Gastric Neuroendocrine Tumor G1', 'Gastric']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ADCYAP1": 4.0,
        "ADCYAP1R1": 4.0,
        "ALK": 4.0,
        "APC": 4.0,
        "ARID1A": 4.0,
        "ATM": 4.0,
        "ATP12A": 4.0,
        "ATP4A": 4.0,
        "ATRX": 4.0,
        "BCL2": 4.0,
        "CASP3": 4.0,
        "CCK": 4.0,
        "CCKBR": 4.0,
        "CCND3": 4.0,
        "CDKN1B": 4.0,
        "CDKN2A": 4.0,
        "CGA": 4.0,
        "CHGA": 4.0,
        "CHL1": 4.0,
        "CREBBP": 4.0,
        "CTNNB1": 4.0,
        "DCTN6": 4.0,
        "DUSP2": 4.0,
        "ERBB2": 4.0,
        "ERBB4": 4.0,
        "FGF2": 4.0,
        "GAST": 4.0,
        "GGH": 4.0,
        "GH1": 4.0,
        "GNAS": 4.0,
        "HDC": 4.0,
        "IFI27": 4.0,
        "KCNQ1": 4.0,
        "KDM6A": 4.0,
        "KLF6": 4.0,
        "KMT2D": 4.0,
        "KRAS": 4.0,
        "MAP3K1": 4.0,
        "MCL1": 4.0,
        "MEN1": 4.0,
        "MTOR": 4.0,
        "MZB1": 4.0,
        "NCAM1": 4.0,
        "NCOR1": 4.0,
        "NFASC": 4.0,
        "NFE2L2": 4.0,
        "PAK2": 4.0,
        "PAX5": 4.0,
        "POMC": 4.0,
        "PSMD9": 4.0,
        "PSMG1": 4.0,
        "RB1": 4.0,
        "SPEN": 4.0,
        "TGM2": 4.0,
        "TMED7": 4.0,
        "TP53": 4.0,
        "TSC2": 4.0,
        "ZNRD2": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "mirtazapine",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "gastric_neuroendocrine_tumor_g1-screening-v1",
    "pathway_keywords": [
        "apoptosis",
        "cardiac",
        "cascade",
        "cell",
        "channel",
        "coagulation",
        "conduction",
        "cycle",
        "hormone",
        "mapk",
    ],
    "mechanism_keywords": [
        "apoptosis",
        "cardiac",
        "cascade",
        "cell",
        "channel",
        "coagulation",
        "conduction",
        "cycle",
        "hormone",
        "mapk",
    ],
    "reference_drug_ids": [
        "CHEMBL654",
        "CHEMBL654",
        "CHEMBL654",
        "CHEMBL654",
        "CHEMBL654",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_gastric_neuroendocrine_tumor_g1_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
