"""mycosis fungoides (MYCOSIS_FUNGOIDES) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'mycosis fungoides (MYCOSIS_FUNGOIDES)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of mycosis fungoides
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(mycosis fungoides[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(mycosis fungoides[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(mycosis fungoides[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(mycosis fungoides[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'mycosis fungoides OR mycosis'
GWAS_SEARCH_TERMS = ['mycosis fungoides', 'mycosis']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "CCL17": 4.0,
        "CCR4": 4.0,
        "CD3E": 4.0,
        "CD4": 4.0,
        "CD52": 4.0,
        "CDKN1A": 4.0,
        "DHFR": 4.0,
        "EEF2": 4.0,
        "ERVW-1": 4.0,
        "FKBP1A": 4.0,
        "HDAC1": 4.0,
        "HDAC2": 4.0,
        "HDAC3": 4.0,
        "HDAC6": 4.0,
        "IMPDH1": 4.0,
        "IMPDH2": 4.0,
        "JAK3": 4.0,
        "MMP1": 4.0,
        "MMP13": 4.0,
        "MMP7": 4.0,
        "MMP8": 4.0,
        "NR3C1": 4.0,
        "NSG1": 4.0,
        "OPRD1": 4.0,
        "OPRK1": 4.0,
        "OPRM1": 4.0,
        "PDCD1": 4.0,
        "POLA1": 4.0,
        "POLA2": 4.0,
        "POLD1": 4.0,
        "POLD2": 4.0,
        "POLD3": 4.0,
        "POLD4": 4.0,
        "POLE": 4.0,
        "POLE2": 4.0,
        "POLE3": 4.0,
        "PPARG": 4.0,
        "PRIM1": 4.0,
        "PRIM2": 4.0,
        "RPL17": 4.0,
        "RPL17-C18orf32": 4.0,
        "RRM1": 4.0,
        "RXRA": 4.0,
        "RXRB": 4.0,
        "RXRG": 4.0,
        "SNCA": 4.0,
        "SPATA2": 4.0,
        "STING1": 4.0,
        "TCEAL1": 4.0,
        "TNFRSF8": 4.0,
        "TOX": 4.0,
        "TUBB": 4.0,
        "TUBB1": 4.0,
        "TUBB2A": 4.0,
        "TUBB2B": 4.0,
        "TUBB3": 4.0,
        "TUBB4A": 4.0,
        "TUBB4B": 4.0,
        "TUBB6": 4.0,
        "TUBB8": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
        "alemtuzumab",
        "gemcitabine",
        "gemcitabine hydrochloride",
    ],
    "moderate_risk": [
        "belinostat",
        "bexarotene",
        "brentuximab vedotin",
        "carmustine",
        "copanlisib hydrochloride",
        "dasatinib",
        "dexamethasone",
        "dexamethasone sodium phosphate",
        "doxycycline",
        "doxycycline anhydrous",
        "duvelisib",
        "methotrexate",
        "mycophenolate mofetil",
        "naloxone",
        "nivolumab",
        "ritlecitinib",
        "rituximab",
        "tacrolimus anhydrous",
        "tanespimycin",
        "vorinostat",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "mycosis_fungoides-screening-v1",
    "pathway_keywords": [
        "cascade",
        "cell",
        "checkpoint",
        "chemokine",
        "coagulation",
        "cycle",
        "immune",
        "lipid",
        "metabolism",
        "opioid",
    ],
    "mechanism_keywords": [
        "cascade",
        "cell",
        "checkpoint",
        "chemokine",
        "coagulation",
        "cycle",
        "immune",
        "lipid",
        "metabolism",
        "opioid",
    ],
    "reference_drug_ids": [
        "CHEMBL1742994",
        "CHEMBL343448",
        "CHEMBL80",
        "CHEMBL109480",
        "CHEMBL1456",
        "CHEMBL1742994",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_mycosis_fungoides_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
