"""Child Behaviour Checklist assessment (CHILD_BEHAVIOUR_CHECKLIST_ASSESSMENT) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'Child Behaviour Checklist assessment (CHILD_BEHAVIOUR_CHECKLIST_ASSESSMENT)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of Child Behaviour Checklist assessment
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(Child Behaviour Checklist assessment[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(Child Behaviour Checklist assessment[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(Child Behaviour Checklist assessment[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(Child Behaviour Checklist assessment[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'Child Behaviour Checklist assessment OR Child'
GWAS_SEARCH_TERMS = ['Child Behaviour Checklist assessment', 'Child']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ALB": 4.0,
        "BCL2": 4.0,
        "BCL3": 4.0,
        "BCL6": 4.0,
        "CCND1": 4.0,
        "CD14": 4.0,
        "CD19": 4.0,
        "CD22": 4.0,
        "CD28": 4.0,
        "CD38": 4.0,
        "CD4": 4.0,
        "CD5": 4.0,
        "CD74": 4.0,
        "CD79A": 4.0,
        "CDKN2A": 4.0,
        "CR2": 4.0,
        "CXCL13": 4.0,
        "CXCR5": 4.0,
        "DAB1": 4.0,
        "FANCA": 4.0,
        "FAS": 4.0,
        "FASLG": 4.0,
        "FBXW7": 4.0,
        "FGF9": 4.0,
        "FXN": 4.0,
        "HLA-G": 4.0,
        "ICAM1": 4.0,
        "IFNG": 4.0,
        "IL10": 4.0,
        "IL6": 4.0,
        "KRT20": 4.0,
        "MME": 4.0,
        "MS4A1": 4.0,
        "MT2A": 4.0,
        "MTNR1B": 4.0,
        "MYC": 4.0,
        "MYD88": 4.0,
        "NFKB2": 4.0,
        "NMRK2": 4.0,
        "PDCD1": 4.0,
        "PEBP1": 4.0,
        "POT1": 4.0,
        "PRDM1": 4.0,
        "RPL17": 4.0,
        "RPL17-C18orf32": 4.0,
        "RUNX1": 4.0,
        "SLC7A4": 4.0,
        "SNCA": 4.0,
        "SOX11": 4.0,
        "SPATA2": 4.0,
        "ST6GAL1": 4.0,
        "TMPRSS6": 4.0,
        "TNFRSF8": 4.0,
        "TOX": 4.0,
        "TP53": 4.0,
        "TRAF3": 4.0,
        "VWF": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "child_behaviour_checklist_assessment-screening-v1",
    "pathway_keywords": [
        "apoptosis",
        "cascade",
        "cell",
        "checkpoint",
        "chemokine",
        "coagulation",
        "complement",
        "cycle",
        "immune",
        "inflammasome",
    ],
    "mechanism_keywords": [
        "apoptosis",
        "cascade",
        "cell",
        "checkpoint",
        "chemokine",
        "coagulation",
        "complement",
        "cycle",
        "immune",
        "inflammasome",
    ],
    "reference_drug_ids": [
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_child_behaviour_checklist_assessment_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
