"""non-acquired combined pituitary hormone deficiency (NON_ACQUIRED_COMBINED_PITUITARY_HORMONE_DEFICIENCY) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "non-acquired combined pituitary hormone deficiency (NON_ACQUIRED_COMBINED_PITUITARY_HORMONE_DEFICIENCY)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of non-acquired combined pituitary hormone deficiency
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(non-acquired combined pituitary hormone deficiency[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(non-acquired combined pituitary hormone deficiency[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(non-acquired combined pituitary hormone deficiency[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(non-acquired combined pituitary hormone deficiency[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "non-acquired combined pituitary hormone deficiency OR non-acquired"
GWAS_SEARCH_TERMS = ["non-acquired combined pituitary hormone deficiency", "non-acquired"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ADIPOQ": 4.0,
        "ANOS1": 4.0,
        "ARID1B": 4.0,
        "ARNT2": 4.0,
        "BMP2": 4.0,
        "BMP4": 4.0,
        "CDH2": 4.0,
        "CDON": 4.0,
        "CHD7": 4.0,
        "CRH": 4.0,
        "FGF8": 4.0,
        "FGFR1": 4.0,
        "FOXA2": 4.0,
        "GCG": 4.0,
        "GGH": 4.0,
        "GH1": 4.0,
        "GHRHR": 4.0,
        "GLI1": 4.0,
        "GLI2": 4.0,
        "GLI4": 4.0,
        "HESX1": 4.0,
        "IGSF1": 4.0,
        "INS": 4.0,
        "KLHL3": 4.0,
        "LEP": 4.0,
        "LHX1": 4.0,
        "LHX3": 4.0,
        "LHX4": 4.0,
        "LIM2": 4.0,
        "MIP": 4.0,
        "OTX2": 4.0,
        "PAX6": 4.0,
        "PITX1": 4.0,
        "PITX2": 4.0,
        "PNPLA6": 4.0,
        "POMC": 4.0,
        "POU1F1": 4.0,
        "PRL": 4.0,
        "PROKR2": 4.0,
        "PROP1": 4.0,
        "RETN": 4.0,
        "RNPC3": 4.0,
        "SHH": 4.0,
        "SIX1": 4.0,
        "SIX5": 4.0,
        "SIX6": 4.0,
        "SLC20A1": 4.0,
        "SOD1": 4.0,
        "SOX2": 4.0,
        "SOX3": 4.0,
        "TBC1D32": 4.0,
        "TGM2": 4.0,
        "WDR11": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "hydrocortisone",
        "methylprednisolone",
        "prednisone",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "non_acquired_combined_pituitary_hormone_deficiency-screening-v1",
    "pathway_keywords": [
        "cascade",
        "coagulation",
        "glucose",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "hormone",
        "insulin",
        "iron",
        "mapk",
    ],
    "mechanism_keywords": [
        "cascade",
        "coagulation",
        "glucose",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "hormone",
        "insulin",
        "iron",
        "mapk",
    ],
    "reference_drug_ids": [
        "CHEMBL1201621",
        "CHEMBL650",
        "CHEMBL389621",
        "CHEMBL635",
        "CHEMBL1201621",
        "CHEMBL1201621",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_non_acquired_combined_pituitary_hormone_deficiency_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
