"""familial atypical multiple mole melanoma syndrome (FAMILIAL_ATYPICAL_MULTIPLE_MOLE_MELANOMA_SYNDROME) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "familial atypical multiple mole melanoma syndrome (FAMILIAL_ATYPICAL_MULTIPLE_MOLE_MELANOMA_SYNDROME)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of familial atypical multiple mole melanoma syndrome
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(familial atypical multiple mole melanoma syndrome[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(familial atypical multiple mole melanoma syndrome[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(familial atypical multiple mole melanoma syndrome[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(familial atypical multiple mole melanoma syndrome[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "familial atypical multiple mole melanoma syndrome OR familial"
GWAS_SEARCH_TERMS = ["familial atypical multiple mole melanoma syndrome", "familial"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACTB": 4.0,
        "APC": 4.0,
        "ATM": 4.0,
        "ATP2C1": 4.0,
        "BAP1": 4.0,
        "BECN1": 4.0,
        "BRCA1": 4.0,
        "CBX7": 4.0,
        "CCDC80": 4.0,
        "CDK4": 4.0,
        "CDKN1A": 4.0,
        "CDKN2A": 4.0,
        "CUL9": 4.0,
        "DCLRE1A": 4.0,
        "DDB2": 4.0,
        "DGKD": 4.0,
        "DPH1": 4.0,
        "EAF2": 4.0,
        "FANCD2": 4.0,
        "FBXO4": 4.0,
        "FHIT": 4.0,
        "HIC1": 4.0,
        "HPRT1": 4.0,
        "HTATIP2": 4.0,
        "KRAS": 4.0,
        "LZTS1": 4.0,
        "MDM2": 4.0,
        "MEN1": 4.0,
        "MET": 4.0,
        "MLH1": 4.0,
        "MSH2": 4.0,
        "MSH6": 4.0,
        "MTF1": 4.0,
        "MUS81": 4.0,
        "MYH14": 4.0,
        "NDRG2": 4.0,
        "NF1": 4.0,
        "NF2": 4.0,
        "PLK1": 4.0,
        "POLD1": 4.0,
        "PRDM2": 4.0,
        "PRF1": 4.0,
        "PRKAR1A": 4.0,
        "PTCH1": 4.0,
        "PTEN": 4.0,
        "PTPRJ": 4.0,
        "RB1": 4.0,
        "ROBO1": 4.0,
        "SAV1": 4.0,
        "SMARCB1": 4.0,
        "SRPX": 4.0,
        "STK11": 4.0,
        "TNK1": 4.0,
        "TP53": 4.0,
        "TP53BP2": 4.0,
        "TP73": 4.0,
        "TRIM62": 4.0,
        "TSC1": 4.0,
        "TSC2": 4.0,
        "TXNIP": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "atezolizumab",
        "cobimetinib",
        "motesanib",
        "tazarotene",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "familial_atypical_multiple_mole_melanoma_syndrome-screening-v1",
    "pathway_keywords": [
        "autophagy",
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "hedgehog",
        "mapk",
        "mtor",
        "pi3k",
        "regulation",
    ],
    "mechanism_keywords": [
        "autophagy",
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "hedgehog",
        "mapk",
        "mtor",
        "pi3k",
        "regulation",
    ],
    "reference_drug_ids": [
        "CHEMBL1680",
        "CHEMBL1657",
        "CHEMBL572881",
        "CHEMBL572881",
        "CHEMBL1657",
        "CHEMBL1657",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_familial_atypical_multiple_mole_melanoma_syndrome_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
