"""combined immunodeficiency and megaloblastic anemia with or without hyperhomocysteinemia (COMBINED_IMMUNODEFICIENCY_AND_MEGALOBLASTIC_ANEMIA_WITH_OR_WITHOUT_HYPERHOMOCYSTEINEMIA) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'combined immunodeficiency and megaloblastic anemia with or without hyperhomocysteinemia (COMBINED_IMMUNODEFICIENCY_AND_MEGALOBLASTIC_ANEMIA_WITH_OR_WITHOUT_HYPERHOMOCYSTEINEMIA)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of combined immunodeficiency and megaloblastic anemia with or without hyperhomocysteinemia
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(combined immunodeficiency and megaloblastic anemia with or without hyperhomocysteinemia[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(combined immunodeficiency and megaloblastic anemia with or without hyperhomocysteinemia[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(combined immunodeficiency and megaloblastic anemia with or without hyperhomocysteinemia[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(combined immunodeficiency and megaloblastic anemia with or without hyperhomocysteinemia[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'combined immunodeficiency and megaloblastic anemia with or without hyperhomocysteinemia OR combined'
GWAS_SEARCH_TERMS = ['combined immunodeficiency and megaloblastic anemia with or without hyperhomocysteinemia', 'combined']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AHSP": 4.0,
        "ANK1": 4.0,
        "ARPC1B": 4.0,
        "ATP11C": 4.0,
        "BACH2": 4.0,
        "C9orf72": 4.0,
        "CARD11": 4.0,
        "CD274": 4.0,
        "CEBPE": 4.0,
        "COG6": 4.0,
        "CXCR2": 4.0,
        "EXOC6": 4.0,
        "FAS": 4.0,
        "FASLG": 4.0,
        "FCGR2A": 4.0,
        "FCGR2B": 4.0,
        "FCGR2C": 4.0,
        "FECH": 4.0,
        "FLT3LG": 4.0,
        "FOXP3": 4.0,
        "HEPH": 4.0,
        "ICOS": 4.0,
        "IFNG": 4.0,
        "IL2": 4.0,
        "IL21R": 4.0,
        "IL2RG": 4.0,
        "IL4": 4.0,
        "IL6ST": 4.0,
        "ITGB2": 4.0,
        "JAK3": 4.0,
        "LAT": 4.0,
        "LMBR1L": 4.0,
        "LYN": 4.0,
        "MTHFD1": 4.0,
        "MYB": 4.0,
        "NFKB1": 4.0,
        "NFKB2": 4.0,
        "NFKBIA": 4.0,
        "PIK3CD": 4.0,
        "PKLR": 4.0,
        "PLCG2": 4.0,
        "POU2AF1": 4.0,
        "PRKDC": 4.0,
        "PTPN22": 4.0,
        "PTPRC": 4.0,
        "RAC2": 4.0,
        "RASGRP1": 4.0,
        "REL": 4.0,
        "RORC": 4.0,
        "SAMD9L": 4.0,
        "SPPL2A": 4.0,
        "SPTA1": 4.0,
        "STEAP3": 4.0,
        "STK4": 4.0,
        "TLR7": 4.0,
        "TNF": 4.0,
        "TNIP1": 4.0,
        "VAV1": 4.0,
        "WAS": 4.0,
        "ZC3H12A": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "combined_immunodeficiency_and_megaloblastic_anemia_with_or_without_hyperhomocysteinemia-screening-v1",
    "pathway_keywords": [
        "(th2)",
        "adhesion",
        "cascade",
        "cell",
        "checkpoint",
        "chemokine",
        "coagulation",
        "complement",
        "immune",
        "integrin",
    ],
    "mechanism_keywords": [
        "(th2)",
        "adhesion",
        "cascade",
        "cell",
        "checkpoint",
        "chemokine",
        "coagulation",
        "complement",
        "immune",
        "integrin",
    ],
    "reference_drug_ids": [
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_combined_immunodeficiency_and_megaloblastic_anemia_with_or_without_hyperhomocysteinemia_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
