"""spinocerebellar ataxia type 1 (SPINOCEREBELLAR_ATAXIA_TYPE_1) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'spinocerebellar ataxia type 1 (SPINOCEREBELLAR_ATAXIA_TYPE_1)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of spinocerebellar ataxia type 1
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(spinocerebellar ataxia type 1[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(spinocerebellar ataxia type 1[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(spinocerebellar ataxia type 1[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(spinocerebellar ataxia type 1[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'spinocerebellar ataxia type 1 OR spinocerebellar'
GWAS_SEARCH_TERMS = ['spinocerebellar ataxia type 1', 'spinocerebellar']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABCB7": 4.0,
        "ABCD2": 4.0,
        "AFG3L2": 4.0,
        "AMER1": 4.0,
        "ANK3": 4.0,
        "ASPA": 4.0,
        "ATP1B2": 4.0,
        "ATP2B1": 4.0,
        "ATP2B2": 4.0,
        "ATP2B3": 4.0,
        "ATXN1": 4.0,
        "BDNF": 4.0,
        "CA8": 4.0,
        "CACNA2D2": 4.0,
        "CANX": 4.0,
        "CCR10": 4.0,
        "CFAP276": 4.0,
        "CLCC1": 4.0,
        "CLP1": 4.0,
        "CNTNAP1": 4.0,
        "DOCK3": 4.0,
        "DST": 4.0,
        "FIG4": 4.0,
        "GALC": 4.0,
        "GRID2": 4.0,
        "GSK3A": 4.0,
        "GSK3B": 4.0,
        "HGS": 4.0,
        "IMPA1": 4.0,
        "IREB2": 4.0,
        "KCNJ6": 4.0,
        "KIF14": 4.0,
        "L1CAM": 4.0,
        "MATR3": 4.0,
        "MDGA2": 4.0,
        "MID1": 4.0,
        "MORC2": 4.0,
        "MYH10": 4.0,
        "NHSL2": 4.0,
        "NTF3": 4.0,
        "OPA1": 4.0,
        "PHKA1": 4.0,
        "PLAA": 4.0,
        "PPT1": 4.0,
        "PSAP": 4.0,
        "RORA": 4.0,
        "RTL9": 4.0,
        "SACS": 4.0,
        "SCN8A": 4.0,
        "SHC1": 4.0,
        "SOD2": 4.0,
        "SPTBN2": 4.0,
        "SPTBN4": 4.0,
        "TARDBP": 4.0,
        "TOR1A": 4.0,
        "TRIM2": 4.0,
        "TTPA": 4.0,
        "UCHL1": 4.0,
        "UNC5C": 4.0,
        "ZNF106": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "lithium carbonate",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "spinocerebellar_ataxia_type_1-screening-v1",
    "pathway_keywords": [
        "cardiac",
        "cascade",
        "channel",
        "chemokine",
        "coagulation",
        "complement",
        "conduction",
        "metabolism",
        "pathway",
        "repair",
    ],
    "mechanism_keywords": [
        "cardiac",
        "cascade",
        "channel",
        "chemokine",
        "coagulation",
        "complement",
        "conduction",
        "metabolism",
        "pathway",
        "repair",
    ],
    "reference_drug_ids": [
        "CHEMBL1200826",
        "CHEMBL1200826",
        "CHEMBL1200826",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_spinocerebellar_ataxia_type_1_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
