"""glycogen storage disorder due to hepatic glycogen synthase deficiency (GLYCOGEN_STORAGE_DISORDER_DUE_TO_HEPATIC_GLYCOGEN_SYNTHASE_DEFICIENCY) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "glycogen storage disorder due to hepatic glycogen synthase deficiency (GLYCOGEN_STORAGE_DISORDER_DUE_TO_HEPATIC_GLYCOGEN_SYNTHASE_DEFICIENCY)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Autosomal recessive inheritance",
    "Fasting hypoglycemia",
    "Seizure",
    "Postprandial hyperglycemia",
    "Neonatal hypoglycemia",
    "Increased circulating lactate concentration",
    "Ketosis",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(glycogen storage disorder due to hepatic glycogen synthase deficiency[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(glycogen storage disorder due to hepatic glycogen synthase deficiency[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(glycogen storage disorder due to hepatic glycogen synthase deficiency[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(glycogen storage disorder due to hepatic glycogen synthase deficiency[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "glycogen storage disorder due to hepatic glycogen synthase deficiency OR glycogen"
GWAS_SEARCH_TERMS = [
    "glycogen storage disorder due to hepatic glycogen synthase deficiency",
    "glycogen",
]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABCC8": 4.0,
        "ADGRF5": 4.0,
        "ADIPOR1": 4.0,
        "ADIPOR2": 4.0,
        "ADORA2B": 4.0,
        "ADRA2A": 4.0,
        "AFMID": 4.0,
        "AGAP2": 4.0,
        "AKT2": 4.0,
        "ALX3": 4.0,
        "ATP8A2": 4.0,
        "CACNA1E": 4.0,
        "CCDC120": 4.0,
        "CREBBP": 4.0,
        "CTSB": 4.0,
        "CTSS": 4.0,
        "CXCR3": 4.0,
        "ERO1B": 4.0,
        "FABP3": 4.0,
        "FBP1": 4.0,
        "GCK": 4.0,
        "GCKR": 4.0,
        "GIPR": 4.0,
        "GLO1": 4.0,
        "GLP1R": 4.0,
        "GYS2": 4.0,
        "HMGN3": 4.0,
        "HPRT1": 4.0,
        "IL10RB": 4.0,
        "ILDR2": 4.0,
        "INS": 4.0,
        "INSR": 4.0,
        "IRS2": 4.0,
        "IRS4": 4.0,
        "KCNIP1": 4.0,
        "KMT2B": 4.0,
        "LDLR": 4.0,
        "LEP": 4.0,
        "LEPR": 4.0,
        "MC4R": 4.0,
        "NR1I3": 4.0,
        "OAS1": 4.0,
        "PDX1": 4.0,
        "PDZD2": 4.0,
        "PFKM": 4.0,
        "PIK3R1": 4.0,
        "PIK3R2": 4.0,
        "PRADC1": 4.0,
        "PREX2": 4.0,
        "PTPN1": 4.0,
        "RAB37": 4.0,
        "RFTN2": 4.0,
        "RGS10": 4.0,
        "SEC61A1": 4.0,
        "SH2B1": 4.0,
        "SLC9B2": 4.0,
        "ST3GAL5": 4.0,
        "STXBP3": 4.0,
        "TCF7L2": 4.0,
        "USP36": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "melatonin",
        "rosiglitazone",
        "rosuvastatin",
    ],
    "low_risk": [
        "metformin",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "glycogen_storage_disorder_due_to_hepatic_glycogen_synthase_deficiency-screening-v1",
    "pathway_keywords": [
        "cardiac",
        "cascade",
        "channel",
        "chemokine",
        "coagulation",
        "conduction",
        "glucose",
        "inflammasome",
        "insulin",
        "interferon",
    ],
    "mechanism_keywords": [
        "cardiac",
        "cascade",
        "channel",
        "chemokine",
        "coagulation",
        "conduction",
        "glucose",
        "inflammasome",
        "insulin",
        "interferon",
    ],
    "reference_drug_ids": [
        "CHEMBL1431",
        "CHEMBL45",
        "CHEMBL1431",
        "CHEMBL1431",
        "CHEMBL1431",
        "CHEMBL1431",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_glycogen_storage_disorder_due_to_hepatic_glycogen_synthase_deficiency_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
