"""spondylosis (SPONDYLOSIS) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'spondylosis (SPONDYLOSIS)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of spondylosis
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(spondylosis[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(spondylosis[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(spondylosis[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(spondylosis[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'spondylosis OR spondylosis'
GWAS_SEARCH_TERMS = ['spondylosis', 'spondylosis']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ABL1": 4.0,
        "ADAMTS17": 4.0,
        "BCL2": 4.0,
        "BGLAP": 4.0,
        "BMP4": 4.0,
        "BMP6": 4.0,
        "BMPR1A": 4.0,
        "BMPR1B": 4.0,
        "CAT": 4.0,
        "CCDC6": 4.0,
        "CLN5": 4.0,
        "CNGA1": 4.0,
        "CRP": 4.0,
        "CTSA": 4.0,
        "DICER1": 4.0,
        "EDN1": 4.0,
        "F9": 4.0,
        "FGF2": 4.0,
        "FGF23": 4.0,
        "GDF5": 4.0,
        "HLA-B": 4.0,
        "HTRA1": 4.0,
        "IHH": 4.0,
        "KL": 4.0,
        "KRT7": 4.0,
        "MKI67": 4.0,
        "MTTP": 4.0,
        "NIPAL1": 4.0,
        "NOTCH3": 4.0,
        "PCDH7": 4.0,
        "PLA2G1B": 4.0,
        "PLA2G2A": 4.0,
        "PLA2G5": 4.0,
        "PLA2G6": 4.0,
        "PTCH1": 4.0,
        "PTH": 4.0,
        "PTH1R": 4.0,
        "PTHLH": 4.0,
        "RET": 4.0,
        "RSPO2": 4.0,
        "TAS2R38": 4.0,
        "TGFB1": 4.0,
        "TNF": 4.0,
        "TNFRSF14": 4.0,
        "TTR": 4.0,
        "VDR": 4.0,
        "WRN": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "alendronic acid",
        "burosumab",
        "denosumab",
        "ibandronic acid",
        "medroxyprogesterone acetate",
        "pamidronic acid",
        "progesterone",
        "risedronic acid",
        "romosozumab",
        "zoledronic acid",
        "zoledronic acid anhydrous",
    ],
    "low_risk": [
        "mecasermin",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "spondylosis-screening-v1",
    "pathway_keywords": [
        "apoptosis",
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "dopamine",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "hormone",
    ],
    "mechanism_keywords": [
        "apoptosis",
        "cascade",
        "cell",
        "coagulation",
        "cycle",
        "dopamine",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "hormone",
    ],
    "reference_drug_ids": [
        "CHEMBL2109171",
        "CHEMBL2108594",
        "CHEMBL2108594",
        "CHEMBL4303669",
        "CHEMBL4303669",
        "CHEMBL2109171",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_spondylosis_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
