"""Benign Thyroid Gland Neoplasm (BENIGN_THYROID_GLAND_NEOPLASM) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "Benign Thyroid Gland Neoplasm (BENIGN_THYROID_GLAND_NEOPLASM)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of Benign Thyroid Gland Neoplasm
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(Benign Thyroid Gland Neoplasm[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(Benign Thyroid Gland Neoplasm[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(Benign Thyroid Gland Neoplasm[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(Benign Thyroid Gland Neoplasm[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "Benign Thyroid Gland Neoplasm OR Benign"
GWAS_SEARCH_TERMS = ["Benign Thyroid Gland Neoplasm", "Benign"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AKT1": 4.0,
        "ALK": 4.0,
        "APC": 4.0,
        "BRAF": 4.0,
        "BRCA2": 4.0,
        "CCDC6": 4.0,
        "CDH1": 4.0,
        "CLTA": 4.0,
        "DICER1": 4.0,
        "EIF1AX": 4.0,
        "ERICH3": 4.0,
        "FCRL4": 4.0,
        "FGFR1": 4.0,
        "FLI1": 4.0,
        "FOSL1": 4.0,
        "FOXE1": 4.0,
        "GNAS": 4.0,
        "GOLGA5": 4.0,
        "GUCY2D": 4.0,
        "HRAS": 4.0,
        "HYAL2": 4.0,
        "IDH1": 4.0,
        "KMT2A": 4.0,
        "KRAS": 4.0,
        "LGALS1": 4.0,
        "LGALS3": 4.0,
        "LMTK3": 4.0,
        "MDM2": 4.0,
        "MMP9": 4.0,
        "MT-CO2": 4.0,
        "NCOA1": 4.0,
        "NCOA2": 4.0,
        "NCOA4": 4.0,
        "NR4A3": 4.0,
        "NRAS": 4.0,
        "NSD1": 4.0,
        "NTRK1": 4.0,
        "NUP98": 4.0,
        "PAX8": 4.0,
        "PIK3CA": 4.0,
        "PPARG": 4.0,
        "PRKAR1A": 4.0,
        "PTEN": 4.0,
        "PTGS2": 4.0,
        "PTPRC": 4.0,
        "RET": 4.0,
        "ROS1": 4.0,
        "SMAD4": 4.0,
        "STRN": 4.0,
        "TFG": 4.0,
        "TG": 4.0,
        "TNIK": 4.0,
        "TP53": 4.0,
        "TPM3": 4.0,
        "TPO": 4.0,
        "TPR": 4.0,
        "TRMO": 4.0,
        "TSHR": 4.0,
        "VEGFA": 4.0,
        "ZNF331": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "alectinib",
        "axitinib",
        "fimepinostat",
        "lenalidomide",
        "liothyronine",
        "liothyronine sodium",
        "ponatinib",
        "selpercatinib",
        "sorafenib",
        "valproic acid",
        "vandetanib",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "benign_thyroid_gland_neoplasm-screening-v1",
    "pathway_keywords": [
        "angiogenesis",
        "hormone",
        "lipid",
        "mapk",
        "metabolism",
        "mtor",
        "pi3k",
        "remodeling",
        "repair",
        "signaling",
    ],
    "mechanism_keywords": [
        "angiogenesis",
        "hormone",
        "lipid",
        "mapk",
        "metabolism",
        "mtor",
        "pi3k",
        "remodeling",
        "repair",
        "signaling",
    ],
    "reference_drug_ids": [
        "CHEMBL1544",
        "CHEMBL24828",
        "CHEMBL3622533",
        "CHEMBL24828",
        "CHEMBL24828",
        "CHEMBL24828",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_benign_thyroid_gland_neoplasm_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
