"""ethylmalonic encephalopathy (HEPATIC_ENCEPHALOPATHY) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "ethylmalonic encephalopathy (HEPATIC_ENCEPHALOPATHY)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of ethylmalonic encephalopathy
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(ethylmalonic encephalopathy[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(ethylmalonic encephalopathy[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(ethylmalonic encephalopathy[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(ethylmalonic encephalopathy[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "ethylmalonic encephalopathy OR ethylmalonic"
GWAS_SEARCH_TERMS = ["ethylmalonic encephalopathy", "ethylmalonic"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACP2": 4.0,
        "AGTPBP1": 4.0,
        "APC2": 4.0,
        "ARCN1": 4.0,
        "ARX": 4.0,
        "ASPA": 4.0,
        "ATP2B2": 4.0,
        "ATXN7": 4.0,
        "BBS4": 4.0,
        "BICD2": 4.0,
        "CACNA1A": 4.0,
        "CACNA2D2": 4.0,
        "CBS": 4.0,
        "CDK5R1": 4.0,
        "CELSR3": 4.0,
        "CLCN3": 4.0,
        "COL11A1": 4.0,
        "COL2A1": 4.0,
        "CSTB": 4.0,
        "CYP7A1": 4.0,
        "DAB1": 4.0,
        "DBNL": 4.0,
        "DDX19A": 4.0,
        "DDX46": 4.0,
        "DHX16": 4.0,
        "DSCAM": 4.0,
        "DST": 4.0,
        "ELP2": 4.0,
        "ELP6": 4.0,
        "EPHA4": 4.0,
        "ETHE1": 4.0,
        "FZD4": 4.0,
        "GAA": 4.0,
        "GM2A": 4.0,
        "GRID2": 4.0,
        "GRN": 4.0,
        "GTF2IRD1": 4.0,
        "HNF1A": 4.0,
        "HTT": 4.0,
        "IDUA": 4.0,
        "KIF12": 4.0,
        "MAPK8IP3": 4.0,
        "MECP2": 4.0,
        "MMUT": 4.0,
        "MOCS2": 4.0,
        "MTREX": 4.0,
        "MYH10": 4.0,
        "MYO5A": 4.0,
        "NAGLU": 4.0,
        "NPC1": 4.0,
        "NR2E1": 4.0,
        "NR2F1": 4.0,
        "PITPNA": 4.0,
        "PMM2": 4.0,
        "PROM1": 4.0,
        "PSAP": 4.0,
        "RELN": 4.0,
        "RORA": 4.0,
        "SKIC2": 4.0,
        "SLC6A5": 4.0,
        "SLC9A6": 4.0,
        "SOD2": 4.0,
        "SPTBN2": 4.0,
        "TNK2": 4.0,
        "TRIM8": 4.0,
        "UNC5C": 4.0,
        "WNT1": 4.0,
        "ZDHHC13": 4.0,
        "ZNF423": 4.0,
        "ZNF575": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "hepatic_encephalopathy-screening-v1",
    "pathway_keywords": [
        "angiotensin",
        "bone",
        "cardiac",
        "cascade",
        "cell",
        "channel",
        "coagulation",
        "conduction",
        "cycle",
        "glucose",
    ],
    "mechanism_keywords": [
        "angiotensin",
        "bone",
        "cardiac",
        "cascade",
        "cell",
        "channel",
        "coagulation",
        "conduction",
        "cycle",
        "glucose",
    ],
    "reference_drug_ids": [
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_hepatic_encephalopathy_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
