"""Xeroderma pigmentosum (XERODERMA_PIGMENTOSUM) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "Xeroderma pigmentosum (XERODERMA_PIGMENTOSUM)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of Xeroderma pigmentosum
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(Xeroderma pigmentosum[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(Xeroderma pigmentosum[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(Xeroderma pigmentosum[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(Xeroderma pigmentosum[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "Xeroderma pigmentosum OR Xeroderma"
GWAS_SEARCH_TERMS = ["Xeroderma pigmentosum", "Xeroderma"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACP2": 4.0,
        "ADAM17": 4.0,
        "ATM": 4.0,
        "ATR": 4.0,
        "AWAT2": 4.0,
        "BAX": 4.0,
        "BMP4": 4.0,
        "CAT": 4.0,
        "CCND1": 4.0,
        "CDH1": 4.0,
        "CDKN1A": 4.0,
        "CDKN2A": 4.0,
        "CRP": 4.0,
        "CRYAB": 4.0,
        "CSH2": 4.0,
        "CSTB": 4.0,
        "DDB1": 4.0,
        "DDB2": 4.0,
        "DNM1L": 4.0,
        "DPT": 4.0,
        "DPYD": 4.0,
        "DSC1": 4.0,
        "DST": 4.0,
        "EDA": 4.0,
        "EDARADD": 4.0,
        "EGFR": 4.0,
        "EIF3F": 4.0,
        "ELOVL3": 4.0,
        "EML1": 4.0,
        "ENDOV": 4.0,
        "ERCC1": 4.0,
        "ERCC2": 4.0,
        "ERCC3": 4.0,
        "ERCC4": 4.0,
        "ERCC5": 4.0,
        "ERCC6": 4.0,
        "ESR1": 4.0,
        "FAR2": 4.0,
        "FOXE3": 4.0,
        "FOXP3": 4.0,
        "FREM1": 4.0,
        "GSDMA": 4.0,
        "GTF2H1": 4.0,
        "GTF2H2": 4.0,
        "GTF2H3": 4.0,
        "GTF2H4": 4.0,
        "GTF2H5": 4.0,
        "GTPBP2": 4.0,
        "HFM1": 4.0,
        "HGF": 4.0,
        "HR": 4.0,
        "HSPA1B": 4.0,
        "IL10": 4.0,
        "IL6": 4.0,
        "KAT7": 4.0,
        "KIF11": 4.0,
        "KLC3": 4.0,
        "LDLR": 4.0,
        "LGR4": 4.0,
        "LIMK2": 4.0,
        "LUM": 4.0,
        "LYST": 4.0,
        "MAP3K1": 4.0,
        "MC1R": 4.0,
        "MITF": 4.0,
        "MKI67": 4.0,
        "MMP13": 4.0,
        "MSX2": 4.0,
        "MYO10": 4.0,
        "MYO5A": 4.0,
        "NFKBIZ": 4.0,
        "NRTN": 4.0,
        "PAX6": 4.0,
        "PCNA": 4.0,
        "PDCD1": 4.0,
        "PLG": 4.0,
        "POLH": 4.0,
        "PPARGC1A": 4.0,
        "PPAT": 4.0,
        "PPP1R13L": 4.0,
        "PRKDC": 4.0,
        "PRSS56": 4.0,
        "PXDN": 4.0,
        "ROCK1": 4.0,
        "RPL17": 4.0,
        "RPL17-C18orf32": 4.0,
        "SCD": 4.0,
        "SH3PXD2B": 4.0,
        "SNCA": 4.0,
        "SOD1": 4.0,
        "SPATA2": 4.0,
        "TGFA": 4.0,
        "THBS1": 4.0,
        "TMEM43": 4.0,
        "TMEM79": 4.0,
        "TNF": 4.0,
        "TP53": 4.0,
        "TYR": 4.0,
        "U2AF1": 4.0,
        "VIM": 4.0,
        "XPA": 4.0,
        "XPC": 4.0,
        "XRCC4": 4.0,
        "ZNF469": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "xeroderma_pigmentosum-screening-v1",
    "pathway_keywords": [
        "apoptosis",
        "autophagy",
        "cascade",
        "cell",
        "checkpoint",
        "coagulation",
        "cycle",
        "immune",
        "inflammasome",
        "lipid",
    ],
    "mechanism_keywords": [
        "apoptosis",
        "autophagy",
        "cascade",
        "cell",
        "checkpoint",
        "coagulation",
        "cycle",
        "immune",
        "inflammasome",
        "lipid",
    ],
    "reference_drug_ids": [
        "CHEMBL441738",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_xeroderma_pigmentosum_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
