"""orofaciodigital syndrome (OROFACIODIGITAL_SYNDROME) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "orofaciodigital syndrome (OROFACIODIGITAL_SYNDROME)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of orofaciodigital syndrome
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(orofaciodigital syndrome[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(orofaciodigital syndrome[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(orofaciodigital syndrome[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(orofaciodigital syndrome[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "orofaciodigital syndrome OR orofaciodigital"
GWAS_SEARCH_TERMS = ["orofaciodigital syndrome", "orofaciodigital"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "BCAR1": 4.0,
        "BMP2": 4.0,
        "C2CD3": 4.0,
        "CC2D2A": 4.0,
        "CDH1": 4.0,
        "CDH2": 4.0,
        "CDK12": 4.0,
        "CEP164": 4.0,
        "CEP83": 4.0,
        "CFAP184": 4.0,
        "CHKA": 4.0,
        "CHKB": 4.0,
        "CMPK1": 4.0,
        "CPLANE1": 4.0,
        "CSE1L": 4.0,
        "CTNND1": 4.0,
        "DAP": 4.0,
        "DDX19A": 4.0,
        "DDX46": 4.0,
        "DDX59": 4.0,
        "DHX16": 4.0,
        "DYNC2H1": 4.0,
        "ENSG00000288534": 4.0,
        "FAM149B1": 4.0,
        "FUZ": 4.0,
        "GGH": 4.0,
        "GH1": 4.0,
        "GLI3": 4.0,
        "GNAS": 4.0,
        "HFM1": 4.0,
        "IFT122": 4.0,
        "IFT56": 4.0,
        "IFT57": 4.0,
        "IFT80": 4.0,
        "INTU": 4.0,
        "KIAA0586": 4.0,
        "KIAA0753": 4.0,
        "LAMB2": 4.0,
        "LGALS3": 4.0,
        "MET": 4.0,
        "NEK1": 4.0,
        "NF1": 4.0,
        "OFD1": 4.0,
        "PACRG": 4.0,
        "PDPN": 4.0,
        "RAB34": 4.0,
        "SCLT1": 4.0,
        "SCNM1": 4.0,
        "SMARCA2": 4.0,
        "STH": 4.0,
        "TADA2B": 4.0,
        "TBC1D32": 4.0,
        "TCTN1": 4.0,
        "TCTN3": 4.0,
        "TGM2": 4.0,
        "TMEM107": 4.0,
        "TMEM231": 4.0,
        "TOPORS": 4.0,
        "TRAF3IP1": 4.0,
        "WDPCP": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "alendronic acid",
        "burosumab",
        "denosumab",
        "ibandronic acid",
        "medroxyprogesterone acetate",
        "pamidronic acid",
        "progesterone",
        "risedronic acid",
        "romosozumab",
        "zoledronic acid",
        "zoledronic acid anhydrous",
    ],
    "low_risk": [
        "mecasermin",
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "orofaciodigital_syndrome-screening-v1",
    "pathway_keywords": [
        "cell",
        "cycle",
        "dopamine",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "hormone",
        "iron",
        "mapk",
        "receptor",
    ],
    "mechanism_keywords": [
        "cell",
        "cycle",
        "dopamine",
        "hedgehog",
        "hepcidin",
        "homeostasis",
        "hormone",
        "iron",
        "mapk",
        "receptor",
    ],
    "reference_drug_ids": [
        "CHEMBL2109171",
        "CHEMBL2108594",
        "CHEMBL2108594",
        "CHEMBL4303669",
        "CHEMBL4303669",
        "CHEMBL2109171",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_orofaciodigital_syndrome_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
