"""isotretinoin-like syndrome (ISOTRETINOIN_LIKE_SYNDROME) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'isotretinoin-like syndrome (ISOTRETINOIN_LIKE_SYNDROME)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of isotretinoin-like syndrome
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(isotretinoin-like syndrome[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(isotretinoin-like syndrome[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(isotretinoin-like syndrome[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(isotretinoin-like syndrome[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'isotretinoin-like syndrome OR isotretinoin-like'
GWAS_SEARCH_TERMS = ['isotretinoin-like syndrome', 'isotretinoin-like']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACKR3": 4.0,
        "AP2B1": 4.0,
        "BMP5": 4.0,
        "C3orf38": 4.0,
        "CCDC39": 4.0,
        "CHRD": 4.0,
        "CITED2": 4.0,
        "CRKL": 4.0,
        "DNAH5": 4.0,
        "DNM2": 4.0,
        "DRC1": 4.0,
        "EDN1": 4.0,
        "EDNRA": 4.0,
        "FBLN1": 4.0,
        "FGFR1": 4.0,
        "FOXH1": 4.0,
        "FOXI3": 4.0,
        "GATA3": 4.0,
        "GATA5": 4.0,
        "GBX2": 4.0,
        "HEY2": 4.0,
        "IDUA": 4.0,
        "IFT25": 4.0,
        "IFT27": 4.0,
        "LEFTY1": 4.0,
        "LEFTY2": 4.0,
        "LUZP1": 4.0,
        "MATR3": 4.0,
        "MEGF8": 4.0,
        "MMP21": 4.0,
        "MUS81": 4.0,
        "MYH10": 4.0,
        "NAT8": 4.0,
        "NAT8B": 4.0,
        "NDST1": 4.0,
        "NPRL3": 4.0,
        "PAX9": 4.0,
        "PDGFRB": 4.0,
        "PIGV": 4.0,
        "PITX2": 4.0,
        "PLXND1": 4.0,
        "PRICKLE1": 4.0,
        "QRICH1": 4.0,
        "RERE": 4.0,
        "RND3": 4.0,
        "RUNX2": 4.0,
        "SEC24B": 4.0,
        "SUFU": 4.0,
        "TBC1D32": 4.0,
        "TBX1": 4.0,
        "TFAP2A": 4.0,
        "TGDS": 4.0,
        "TRAPPC10": 4.0,
        "TULP4": 4.0,
        "VANGL2": 4.0,
        "ZEB1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "isotretinoin_like_syndrome-screening-v1",
    "pathway_keywords": [
        "(th2)",
        "bone",
        "cascade",
        "chemokine",
        "coagulation",
        "hepcidin",
        "homeostasis",
        "hormone",
        "iron",
        "mapk",
    ],
    "mechanism_keywords": [
        "(th2)",
        "bone",
        "cascade",
        "chemokine",
        "coagulation",
        "hepcidin",
        "homeostasis",
        "hormone",
        "iron",
        "mapk",
    ],
    "reference_drug_ids": [
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_isotretinoin_like_syndrome_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
