"""paternal uniparental disomy of chromosome X (PATERNAL_UNIPARENTAL_DISOMY_OF_CHROMOSOME_X) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = (
    "paternal uniparental disomy of chromosome X (PATERNAL_UNIPARENTAL_DISOMY_OF_CHROMOSOME_X)"
)
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of paternal uniparental disomy of chromosome X
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(paternal uniparental disomy of chromosome X[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(paternal uniparental disomy of chromosome X[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(paternal uniparental disomy of chromosome X[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(paternal uniparental disomy of chromosome X[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "paternal uniparental disomy of chromosome X OR paternal"
GWAS_SEARCH_TERMS = ["paternal uniparental disomy of chromosome X", "paternal"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "BMPR1B": 4.0,
        "CBFA2T2": 4.0,
        "CCNB1IP1": 4.0,
        "CDK2": 4.0,
        "CGB1": 4.0,
        "CGB2": 4.0,
        "CGB3": 4.0,
        "CGB5": 4.0,
        "CGB7": 4.0,
        "CGB8": 4.0,
        "DMC1": 4.0,
        "EVX2": 4.0,
        "FSHR": 4.0,
        "GDF5": 4.0,
        "HFM1": 4.0,
        "HOXA11": 4.0,
        "HOXA13": 4.0,
        "HOXD11": 4.0,
        "HOXD13": 4.0,
        "LHB": 4.0,
        "LHX9": 4.0,
        "PTH2": 4.0,
        "RAD51C": 4.0,
        "SPATA22": 4.0,
        "TBX15": 4.0,
        "ZGLP1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "paternal_uniparental_disomy_of_chromosome_x-screening-v1",
    "pathway_keywords": [
        "cell",
        "cycle",
        "dopamine",
        "hepcidin",
        "homeostasis",
        "iron",
        "regulation",
        "repair",
        "serotonin",
        "signaling",
    ],
    "mechanism_keywords": [
        "cell",
        "cycle",
        "dopamine",
        "hepcidin",
        "homeostasis",
        "iron",
        "regulation",
        "repair",
        "serotonin",
        "signaling",
    ],
    "reference_drug_ids": [
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
        "CHEMBL4297744",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_paternal_uniparental_disomy_of_chromosome_x_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
