"""carcinoma of duodenum (CARCINOMA_OF_DUODENUM) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "carcinoma of duodenum (CARCINOMA_OF_DUODENUM)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of carcinoma of duodenum
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(carcinoma of duodenum[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(carcinoma of duodenum[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(carcinoma of duodenum[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(carcinoma of duodenum[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "carcinoma of duodenum OR carcinoma"
GWAS_SEARCH_TERMS = ["carcinoma of duodenum", "carcinoma"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACP5": 4.0,
        "ALK": 4.0,
        "APC": 4.0,
        "APOA2": 4.0,
        "ASGR2": 4.0,
        "BRAF": 4.0,
        "BRCA2": 4.0,
        "CD4": 4.0,
        "CD40LG": 4.0,
        "CD8A": 4.0,
        "CDX2": 4.0,
        "CEACAM5": 4.0,
        "DNAH6": 4.0,
        "ENO2": 4.0,
        "EPCAM": 4.0,
        "FAP": 4.0,
        "FGFR2": 4.0,
        "GJA1": 4.0,
        "GSTM1": 4.0,
        "HLA-C": 4.0,
        "ITLN2": 4.0,
        "KLRK1": 4.0,
        "KRAS": 4.0,
        "KRT7": 4.0,
        "MGMT": 4.0,
        "MLH1": 4.0,
        "MSH2": 4.0,
        "MUC16": 4.0,
        "MUC2": 4.0,
        "MUC5AC": 4.0,
        "MUTYH": 4.0,
        "NBR1": 4.0,
        "NEK1": 4.0,
        "PABPC1": 4.0,
        "PCNA": 4.0,
        "PIGA": 4.0,
        "PTPRT": 4.0,
        "S100A8": 4.0,
        "SCYL1": 4.0,
        "SLC39A8": 4.0,
        "SOX9": 4.0,
        "TDRD7": 4.0,
        "TP53": 4.0,
        "TRAF2": 4.0,
        "TRRAP": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "scopolamine",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "carcinoma_of_duodenum-screening-v1",
    "pathway_keywords": [
        "autophagy",
        "cascade",
        "cell",
        "coagulation",
        "dopamine",
        "mapk",
        "metabolism",
        "receptor",
        "repair",
        "serotonin",
    ],
    "mechanism_keywords": [
        "autophagy",
        "cascade",
        "cell",
        "coagulation",
        "dopamine",
        "mapk",
        "metabolism",
        "receptor",
        "repair",
        "serotonin",
    ],
    "reference_drug_ids": [
        "CHEMBL1201185",
        "CHEMBL569713",
        "CHEMBL1201185",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_carcinoma_of_duodenum_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
