"""mesoblastic nephroma (MESOBLASTIC_NEPHROMA) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "mesoblastic nephroma (MESOBLASTIC_NEPHROMA)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of mesoblastic nephroma
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(mesoblastic nephroma[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(mesoblastic nephroma[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(mesoblastic nephroma[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(mesoblastic nephroma[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "mesoblastic nephroma OR mesoblastic"
GWAS_SEARCH_TERMS = ["mesoblastic nephroma", "mesoblastic"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ACTB": 4.0,
        "ALK": 4.0,
        "ANPEP": 4.0,
        "BCR": 4.0,
        "BIRC5": 4.0,
        "BRAF": 4.0,
        "BRCA1": 4.0,
        "CALCA": 4.0,
        "CCND1": 4.0,
        "DES": 4.0,
        "EGFR": 4.0,
        "EML4": 4.0,
        "ETV6": 4.0,
        "FANCA": 4.0,
        "FAS": 4.0,
        "FN1": 4.0,
        "FXN": 4.0,
        "KIT": 4.0,
        "MKI67": 4.0,
        "NGFR": 4.0,
        "NOTCH1": 4.0,
        "NTRK3": 4.0,
        "PCNA": 4.0,
        "PRCC": 4.0,
        "PTH": 4.0,
        "PTHLH": 4.0,
        "REN": 4.0,
        "TFE3": 4.0,
        "VIM": 4.0,
        "WT1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [],
    "moderate_risk": [
        "ethacrynic acid",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "mesoblastic_nephroma-screening-v1",
    "pathway_keywords": [
        "angiotensin",
        "apoptosis",
        "cell",
        "cycle",
        "dopamine",
        "mapk",
        "mast",
        "notch",
        "regulation",
        "renin",
    ],
    "mechanism_keywords": [
        "angiotensin",
        "apoptosis",
        "cell",
        "cycle",
        "dopamine",
        "mapk",
        "mast",
        "notch",
        "regulation",
        "renin",
    ],
    "reference_drug_ids": [
        "CHEMBL456",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_mesoblastic_nephroma_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
