"""pemphigoid gestationis (PEMPHIGOID_GESTATIONIS) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = "pemphigoid gestationis (PEMPHIGOID_GESTATIONIS)"
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
# TODO: add the clinical symptoms of pemphigoid gestationis
SYMPTOMS = []

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    "(pemphigoid gestationis[Title/Abstract]) AND (treatment[Title/Abstract])",
    "(pemphigoid gestationis[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])",
    "(pemphigoid gestationis[Title/Abstract]) AND (clinical trial[Title/Abstract])",
    "(pemphigoid gestationis[Title/Abstract]) AND (biomarker[Title/Abstract])",
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = "pemphigoid gestationis OR pemphigoid"
GWAS_SEARCH_TERMS = ["pemphigoid gestationis", "pemphigoid"]

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "AGA": 4.0,
        "ARFGEF1": 4.0,
        "ARID2": 4.0,
        "ART4": 4.0,
        "C3": 4.0,
        "C4A": 4.0,
        "CCL11": 4.0,
        "CD53": 4.0,
        "CD79A": 4.0,
        "CFP": 4.0,
        "COL17A1": 4.0,
        "CP": 4.0,
        "CUX1": 4.0,
        "DSP": 4.0,
        "DST": 4.0,
        "GLS2": 4.0,
        "GPNMB": 4.0,
        "HEATR5B": 4.0,
        "HLA-G": 4.0,
        "ITGA6": 4.0,
        "ITGB4": 4.0,
        "KRT5": 4.0,
        "LAMB2": 4.0,
        "LAMB3": 4.0,
        "LAMC2": 4.0,
        "PLAT": 4.0,
        "PLAU": 4.0,
        "PLG": 4.0,
        "PRAP1": 4.0,
        "RNASE3": 4.0,
        "SPINK5": 4.0,
        "TGM2": 4.0,
        "TNC": 4.0,
        "TP63": 4.0,
        "TUFT1": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
        "alemtuzumab",
        "anifrolumab",
        "certolizumab pegol",
        "emapalumab",
        "infliximab",
    ],
    "moderate_risk": [
        "acetaminophen",
        "apremilast",
        "avacopan",
        "azathioprine",
        "belumosudil",
        "bortezomib",
        "briakinumab",
        "canakinumab",
        "deucravacitinib",
        "dimethyl fumarate",
        "eculizumab",
        "everolimus",
        "fingolimod",
        "guselkumab",
        "isatuximab",
        "itacitinib",
        "lenalidomide",
        "methotrexate",
        "methylprednisolone",
        "methylprednisolone hemisuccinate",
        "montelukast",
        "mycophenolic acid",
        "omalizumab",
        "peficitinib",
        "phenytoin",
        "ranitidine",
        "rituximab",
        "satralizumab",
        "secukinumab",
        "siltuximab",
        "siponimod",
        "spesolimab",
        "teriflunomide",
        "thalidomide",
        "tofacitinib",
        "upadacitinib",
        "vedolizumab",
    ],
    "low_risk": [],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "pemphigoid_gestationis-screening-v1",
    "pathway_keywords": [
        "adhesion",
        "cascade",
        "cell",
        "chemokine",
        "coagulation",
        "complement",
        "hormone",
        "integrin",
        "receptor",
        "remodeling",
    ],
    "mechanism_keywords": [
        "adhesion",
        "cascade",
        "cell",
        "chemokine",
        "coagulation",
        "complement",
        "hormone",
        "integrin",
        "receptor",
        "remodeling",
    ],
    "reference_drug_ids": [
        "CHEMBL16",
        "CHEMBL3833307",
        "CHEMBL973",
        "CHEMBL3137308",
        "CHEMBL3137308",
        "CHEMBL1201265",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_pemphigoid_gestationis_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
