"""anal canal carcinoma (ANAL_CANAL_CARCINOMA) disease configuration.

AUTO-GENERATED by `med-research disease add`. Review and fill in the
disease-specific parameters below before running the pipeline.
"""

PIPELINE_LABEL = 'anal canal carcinoma (ANAL_CANAL_CARCINOMA)'
DEFAULT_SAMPLE_SIZE = 50

# ── Symptoms (used by adverse_events/profiler.py) ────────────────────────
SYMPTOMS = [
    "Autosomal dominant inheritance",
    "Anal canal squamous carcinoma",
]

# ── Literature Mining ────────────────────────────────────────────────────
PUBMED_QUERIES = [
    '(anal canal carcinoma[Title/Abstract]) AND (treatment[Title/Abstract])',
    '(anal canal carcinoma[Title/Abstract]) AND (genetics[Title/Abstract] OR genomics[Title/Abstract])',
    '(anal canal carcinoma[Title/Abstract]) AND (clinical trial[Title/Abstract])',
    '(anal canal carcinoma[Title/Abstract]) AND (biomarker[Title/Abstract])',
]

# ── Clinical trials / GWAS search terms (consumed by the web + bio modules) ─
TRIAL_QUERY = 'anal canal carcinoma OR anal'
GWAS_SEARCH_TERMS = ['anal canal carcinoma', 'anal']

# ── CAR-T Scoring Tables (used by car_t_predictor/predictor.py) ──────────
CAR_T_SCORES = {
    "Uncategorized": {
        "ALPI": 4.0,
        "ALPP": 4.0,
        "APC": 4.0,
        "C20orf96": 4.0,
        "CD47": 4.0,
        "CDKN2A": 4.0,
        "CDX2": 4.0,
        "CHKA": 4.0,
        "CHKB": 4.0,
        "CMPK1": 4.0,
        "EGFR": 4.0,
        "FEM1A": 4.0,
        "FGF10": 4.0,
        "GSDMB": 4.0,
        "IAPP": 4.0,
        "ING1": 4.0,
        "KLK3": 4.0,
        "KRT18": 4.0,
        "KRT20": 4.0,
        "KRT7": 4.0,
        "LIAT1": 4.0,
        "MAGT1": 4.0,
        "MIB1": 4.0,
        "MKI67": 4.0,
        "MSH2": 4.0,
        "MUC5AC": 4.0,
        "NME1": 4.0,
        "NPEPPS": 4.0,
        "NQO1": 4.0,
        "OR1E1": 4.0,
        "OR1E2": 4.0,
        "PDCD1": 4.0,
        "PECAM1": 4.0,
        "PIWIL2": 4.0,
        "PIWIL4": 4.0,
        "PLAG1": 4.0,
        "PROS1": 4.0,
        "PROX2": 4.0,
        "RPL17": 4.0,
        "RPL17-C18orf32": 4.0,
        "SLC22A4": 4.0,
        "SMAD4": 4.0,
        "SNCA": 4.0,
        "SPATA2": 4.0,
        "STK11": 4.0,
        "TGFB1": 4.0,
        "THG1L": 4.0,
        "TP53": 4.0,
        "TUBB": 4.0,
        "TUBB1": 4.0,
        "TUBB2A": 4.0,
        "TUBB2B": 4.0,
        "TUBB3": 4.0,
        "TUBB4A": 4.0,
        "TUBB4B": 4.0,
        "TUBB6": 4.0,
        "TUBB8": 4.0,
        "TYMS": 4.0,
        "USH1C": 4.0,
        "VIM": 4.0,
    },
}

# ── Drug safety tiers (used by adverse_events/profiler.py) ───────────────
DRUG_SAFETY_RISK = {
    "high_risk": [
    ],
    "moderate_risk": [
        "capecitabine",
        "docetaxel",
        "docetaxel anhydrous",
        "fluorouracil",
        "panitumumab",
    ],
    "low_risk": [
    ],
}

DISEASE_SPECIFIC_RISK = DRUG_SAFETY_RISK
DRUG_INDUCED_LUPUS_RISK = DRUG_SAFETY_RISK

SCREENING_PROFILE = {
    "strategy_id": "anal_canal_carcinoma-screening-v1",
    "pathway_keywords": [
        "(th2)",
        "angiotensin",
        "cascade",
        "cell",
        "checkpoint",
        "coagulation",
        "cycle",
        "dopamine",
        "immune",
        "mapk",
    ],
    "mechanism_keywords": [
        "(th2)",
        "angiotensin",
        "cascade",
        "cell",
        "checkpoint",
        "coagulation",
        "cycle",
        "dopamine",
        "immune",
        "mapk",
    ],
    "reference_drug_ids": [
        "CHEMBL3545252",
        "CHEMBL3545252",
        "CHEMBL3545252",
        "CHEMBL3545252",
        "CHEMBL92",
        "CHEMBL92",
    ],
    "weights": {
        "binding_estimate": 0.25,
        "druglikeness": 0.15,
        "target_complementarity": 0.35,
        "similarity_score": 0.15,
        "novelty_score": 0.1,
    },
    "source": "scaffold_anal_canal_carcinoma_knowledge_graph",
    "curated_inputs": [
        "pathways",
        "drugs",
        "screening_strategy",
    ],
    "inferred_inputs": [
        "mechanism_keyword_matching",
        "property_based_binding_estimate",
    ],
    "limitations": [
        "Property scores are heuristic prioritization signals and do not establish clinical efficacy or safety.",
    ],
}
